HEADER    VIRAL PROTEIN                           11-SEP-89   2HMG              
TITLE     REFINEMENT OF THE INFLUENZA VIRUS HEMAGGLUTININ BY SIMULATED ANNEALING
COMPND    MOL_ID: 1;                                                            
COMPND   2 MOLECULE: HEMAGGLUTININ (HA1 CHAIN);                                 
COMPND   3 CHAIN: A, C, E;                                                      
COMPND   4 ENGINEERED: YES;                                                     
COMPND   5 MOL_ID: 2;                                                           
COMPND   6 MOLECULE: HEMAGGLUTININ (HA2 CHAIN);                                 
COMPND   7 CHAIN: B, D, F;                                                      
COMPND   8 ENGINEERED: YES                                                      
SOURCE    MOL_ID: 1;                                                            
SOURCE   2 ORGANISM_SCIENTIFIC: INFLUENZA A VIRUS;                              
SOURCE   3 ORGANISM_TAXID: 220997;                                              
SOURCE   4 STRAIN: (A/HONGKONG/19/68(H3N2));                                    
SOURCE   5 VARIANT: (A/HONGKONG/19/68(H3N2));                                   
SOURCE   6 MOL_ID: 2;                                                           
SOURCE   7 ORGANISM_SCIENTIFIC: INFLUENZA A VIRUS;                              
SOURCE   8 ORGANISM_TAXID: 220997;                                              
SOURCE   9 STRAIN: (A/HONGKONG/19/68(H3N2));                                    
SOURCE  10 VARIANT: (A/HONGKONG/19/68(H3N2))                                    
KEYWDS    INFLUENZA VIRUS HEMAGGLUTININ, VIRAL PROTEIN                          
EXPDTA    X-RAY DIFFRACTION                                                     
AUTHOR    W.I.WEIS,A.T.BRUENGER,J.J.SKEHEL,D.C.WILEY                            
REVDAT   5   13-JUL-11 2HMG    1       VERSN                                    
REVDAT   4   24-FEB-09 2HMG    1       VERSN                                    
REVDAT   3   01-APR-03 2HMG    1       JRNL                                     
REVDAT   2   31-OCT-93 2HMG    1       HET                                      
REVDAT   1   15-JAN-91 2HMG    0                                                
SPRSDE     15-JAN-91 2HMG      1HMG                                             
JRNL        AUTH   W.I.WEIS,A.T.BRUNGER,J.J.SKEHEL,D.C.WILEY                    
JRNL        TITL   REFINEMENT OF THE INFLUENZA VIRUS HEMAGGLUTININ BY SIMULATED 
JRNL        TITL 2 ANNEALING.                                                   
JRNL        REF    J.MOL.BIOL.                   V. 212   737 1990              
JRNL        REFN                   ISSN 0022-2836                               
JRNL        PMID   2329580                                                      
JRNL        DOI    10.1016/0022-2836(90)90234-D                                 
REMARK   1                                                                      
REMARK   1 REFERENCE 1                                                          
REMARK   1  AUTH   W.WEIS,J.H.BROWN,S.CUSACK,J.C.PAULSON,J.J.SKEHEL,D.C.WILEY   
REMARK   1  TITL   STRUCTURE OF THE INFLUENZA VIRUS HAEMAGGLUTININ COMPLEXED    
REMARK   1  TITL 2 WITH ITS RECEPTOR, SIALIC ACID                               
REMARK   1  REF    NATURE                        V. 333   426 1988              
REMARK   1  REFN                   ISSN 0028-0836                               
REMARK   1 REFERENCE 2                                                          
REMARK   1  AUTH   M.KNOSSOW,R.S.DANIELS,A.R.DOUGLAS,J.J.SKEHEL,D.C.WILEY       
REMARK   1  TITL   THREE-DIMENSIONAL STRUCTURE OF AN ANTIGENIC MUTANT OF THE    
REMARK   1  TITL 2 INFLUENZA VIRUS HAEMAGGLUTININ                               
REMARK   1  REF    NATURE                        V. 311   678 1984              
REMARK   1  REFN                   ISSN 0028-0836                               
REMARK   1 REFERENCE 3                                                          
REMARK   1  AUTH   I.A.WILSON,J.J.SKEHEL,D.C.WILEY                              
REMARK   1  TITL   STRUCTURE OF THE HAEMAGGLUTININ MEMBRANE GLYCOPROTEIN OF     
REMARK   1  TITL 2 INFLUENZA VIRUS AT 3 ANGSTROMS RESOLUTION                    
REMARK   1  REF    NATURE                        V. 289   366 1981              
REMARK   1  REFN                   ISSN 0028-0836                               
REMARK   1 REFERENCE 4                                                          
REMARK   1  AUTH   D.C.WILEY,I.A.WILSON,J.J.SKEHEL                              
REMARK   1  TITL   STRUCTURAL IDENTIFICATION OF THE ANTIBODY-BINDING SITES OF   
REMARK   1  TITL 2 HONG KONG INFLUENZA HAEMAGGLUTININ AND THEIR INVOLVEMENT IN  
REMARK   1  TITL 3 ANTIGENIC VARIATION                                          
REMARK   1  REF    NATURE                        V. 289   373 1981              
REMARK   1  REFN                   ISSN 0028-0836                               
REMARK   1 REFERENCE 5                                                          
REMARK   1  AUTH   D.C.WILEY,J.J.SKEHEL                                         
REMARK   1  TITL   CRYSTALLIZATION AND X-RAY DIFFRACTION STUDIES ON THE         
REMARK   1  TITL 2 HAEMAGGLUTININ GLYCOPROTEIN FROM THE MEMBRANE OF INFLUENZA   
REMARK   1  TITL 3 VIRUS                                                        
REMARK   1  REF    J.MOL.BIOL.                   V. 112   343 1977              
REMARK   1  REFN                   ISSN 0022-2836                               
REMARK   2                                                                      
REMARK   2 RESOLUTION.    3.00 ANGSTROMS.                                       
REMARK   3                                                                      
REMARK   3 REFINEMENT.                                                          
REMARK   3   PROGRAM     : X-PLOR                                               
REMARK   3   AUTHORS     : BRUNGER                                              
REMARK   3                                                                      
REMARK   3  DATA USED IN REFINEMENT.                                            
REMARK   3   RESOLUTION RANGE HIGH (ANGSTROMS) : 3.00                           
REMARK   3   RESOLUTION RANGE LOW  (ANGSTROMS) : NULL                           
REMARK   3   DATA CUTOFF            (SIGMA(F)) : NULL                           
REMARK   3   DATA CUTOFF HIGH         (ABS(F)) : NULL                           
REMARK   3   DATA CUTOFF LOW          (ABS(F)) : NULL                           
REMARK   3   COMPLETENESS (WORKING+TEST)   (%) : NULL                           
REMARK   3   NUMBER OF REFLECTIONS             : NULL                           
REMARK   3                                                                      
REMARK   3  FIT TO DATA USED IN REFINEMENT.                                     
REMARK   3   CROSS-VALIDATION METHOD          : NULL                            
REMARK   3   FREE R VALUE TEST SET SELECTION  : NULL                            
REMARK   3   R VALUE            (WORKING SET) : 0.222                           
REMARK   3   FREE R VALUE                     : NULL                            
REMARK   3   FREE R VALUE TEST SET SIZE   (%) : NULL                            
REMARK   3   FREE R VALUE TEST SET COUNT      : NULL                            
REMARK   3   ESTIMATED ERROR OF FREE R VALUE  : NULL                            
REMARK   3                                                                      
REMARK   3  FIT IN THE HIGHEST RESOLUTION BIN.                                  
REMARK   3   TOTAL NUMBER OF BINS USED           : NULL                         
REMARK   3   BIN RESOLUTION RANGE HIGH       (A) : NULL                         
REMARK   3   BIN RESOLUTION RANGE LOW        (A) : NULL                         
REMARK   3   BIN COMPLETENESS (WORKING+TEST) (%) : NULL                         
REMARK   3   REFLECTIONS IN BIN    (WORKING SET) : NULL                         
REMARK   3   BIN R VALUE           (WORKING SET) : NULL                         
REMARK   3   BIN FREE R VALUE                    : NULL                         
REMARK   3   BIN FREE R VALUE TEST SET SIZE  (%) : NULL                         
REMARK   3   BIN FREE R VALUE TEST SET COUNT     : NULL                         
REMARK   3   ESTIMATED ERROR OF BIN FREE R VALUE : NULL                         
REMARK   3                                                                      
REMARK   3  NUMBER OF NON-HYDROGEN ATOMS USED IN REFINEMENT.                    
REMARK   3   PROTEIN ATOMS            : 11871                                   
REMARK   3   NUCLEIC ACID ATOMS       : 0                                       
REMARK   3   HETEROGEN ATOMS          : 285                                     
REMARK   3   SOLVENT ATOMS            : 33                                      
REMARK   3                                                                      
REMARK   3  B VALUES.                                                           
REMARK   3   FROM WILSON PLOT           (A**2) : NULL                           
REMARK   3   MEAN B VALUE      (OVERALL, A**2) : NULL                           
REMARK   3   OVERALL ANISOTROPIC B VALUE.                                       
REMARK   3    B11 (A**2) : NULL                                                 
REMARK   3    B22 (A**2) : NULL                                                 
REMARK   3    B33 (A**2) : NULL                                                 
REMARK   3    B12 (A**2) : NULL                                                 
REMARK   3    B13 (A**2) : NULL                                                 
REMARK   3    B23 (A**2) : NULL                                                 
REMARK   3                                                                      
REMARK   3  ESTIMATED COORDINATE ERROR.                                         
REMARK   3   ESD FROM LUZZATI PLOT        (A) : NULL                            
REMARK   3   ESD FROM SIGMAA              (A) : NULL                            
REMARK   3   LOW RESOLUTION CUTOFF        (A) : NULL                            
REMARK   3                                                                      
REMARK   3  CROSS-VALIDATED ESTIMATED COORDINATE ERROR.                         
REMARK   3   ESD FROM C-V LUZZATI PLOT    (A) : NULL                            
REMARK   3   ESD FROM C-V SIGMAA          (A) : NULL                            
REMARK   3                                                                      
REMARK   3  RMS DEVIATIONS FROM IDEAL VALUES.                                   
REMARK   3   BOND LENGTHS                 (A) : 0.015                           
REMARK   3   BOND ANGLES            (DEGREES) : 2.90                            
REMARK   3   DIHEDRAL ANGLES        (DEGREES) : NULL                            
REMARK   3   IMPROPER ANGLES        (DEGREES) : NULL                            
REMARK   3                                                                      
REMARK   3  ISOTROPIC THERMAL MODEL : NULL                                      
REMARK   3                                                                      
REMARK   3  ISOTROPIC THERMAL FACTOR RESTRAINTS.    RMS    SIGMA                
REMARK   3   MAIN-CHAIN BOND              (A**2) : NULL  ; NULL                 
REMARK   3   MAIN-CHAIN ANGLE             (A**2) : NULL  ; NULL                 
REMARK   3   SIDE-CHAIN BOND              (A**2) : NULL  ; NULL                 
REMARK   3   SIDE-CHAIN ANGLE             (A**2) : NULL  ; NULL                 
REMARK   3                                                                      
REMARK   3  NCS MODEL : NULL                                                    
REMARK   3                                                                      
REMARK   3  NCS RESTRAINTS.                         RMS   SIGMA/WEIGHT          
REMARK   3   GROUP  1  POSITIONAL            (A) : NULL  ; NULL                 
REMARK   3   GROUP  1  B-FACTOR           (A**2) : NULL  ; NULL                 
REMARK   3                                                                      
REMARK   3  PARAMETER FILE  1  : NULL                                           
REMARK   3  TOPOLOGY FILE  1   : NULL                                           
REMARK   3                                                                      
REMARK   3  OTHER REFINEMENT REMARKS: A TEMPERATURE FACTOR OF 65.0 OR LARGER    
REMARK   3  SIGNIFIES AN ATOM WHOSE COORDINATES WERE GENERATED USING            
REMARK   3  STEREOCHEMICAL CRITERIA.                                            
REMARK   4                                                                      
REMARK   4 2HMG COMPLIES WITH FORMAT V. 3.30, 13-JUL-11                         
REMARK 100                                                                      
REMARK 100 THIS ENTRY HAS BEEN PROCESSED BY BNL.                                
REMARK 200                                                                      
REMARK 200 EXPERIMENTAL DETAILS                                                 
REMARK 200  EXPERIMENT TYPE                : X-RAY DIFFRACTION                  
REMARK 200  DATE OF DATA COLLECTION        : NULL                               
REMARK 200  TEMPERATURE           (KELVIN) : NULL                               
REMARK 200  PH                             : NULL                               
REMARK 200  NUMBER OF CRYSTALS USED        : NULL                               
REMARK 200                                                                      
REMARK 200  SYNCHROTRON              (Y/N) : NULL                               
REMARK 200  RADIATION SOURCE               : NULL                               
REMARK 200  BEAMLINE                       : NULL                               
REMARK 200  X-RAY GENERATOR MODEL          : NULL                               
REMARK 200  MONOCHROMATIC OR LAUE    (M/L) : NULL                               
REMARK 200  WAVELENGTH OR RANGE        (A) : NULL                               
REMARK 200  MONOCHROMATOR                  : NULL                               
REMARK 200  OPTICS                         : NULL                               
REMARK 200                                                                      
REMARK 200  DETECTOR TYPE                  : NULL                               
REMARK 200  DETECTOR MANUFACTURER          : NULL                               
REMARK 200  INTENSITY-INTEGRATION SOFTWARE : NULL                               
REMARK 200  DATA SCALING SOFTWARE          : NULL                               
REMARK 200                                                                      
REMARK 200  NUMBER OF UNIQUE REFLECTIONS   : NULL                               
REMARK 200  RESOLUTION RANGE HIGH      (A) : NULL                               
REMARK 200  RESOLUTION RANGE LOW       (A) : NULL                               
REMARK 200  REJECTION CRITERIA  (SIGMA(I)) : NULL                               
REMARK 200                                                                      
REMARK 200 OVERALL.                                                             
REMARK 200  COMPLETENESS FOR RANGE     (%) : NULL                               
REMARK 200  DATA REDUNDANCY                : NULL                               
REMARK 200  R MERGE                    (I) : NULL                               
REMARK 200  R SYM                      (I) : NULL                               
REMARK 200  <I/SIGMA(I)> FOR THE DATA SET  : NULL                               
REMARK 200                                                                      
REMARK 200 IN THE HIGHEST RESOLUTION SHELL.                                     
REMARK 200  HIGHEST RESOLUTION SHELL, RANGE HIGH (A) : NULL                     
REMARK 200  HIGHEST RESOLUTION SHELL, RANGE LOW  (A) : NULL                     
REMARK 200  COMPLETENESS FOR SHELL     (%) : NULL                               
REMARK 200  DATA REDUNDANCY IN SHELL       : NULL                               
REMARK 200  R MERGE FOR SHELL          (I) : NULL                               
REMARK 200  R SYM FOR SHELL            (I) : NULL                               
REMARK 200  <I/SIGMA(I)> FOR SHELL         : NULL                               
REMARK 200                                                                      
REMARK 200 DIFFRACTION PROTOCOL: NULL                                           
REMARK 200 METHOD USED TO DETERMINE THE STRUCTURE: NULL                         
REMARK 200 SOFTWARE USED: NULL                                                  
REMARK 200 STARTING MODEL: NULL                                                 
REMARK 200                                                                      
REMARK 200 REMARK: NULL                                                         
REMARK 280                                                                      
REMARK 280 CRYSTAL                                                              
REMARK 280 SOLVENT CONTENT, VS   (%): NULL                                      
REMARK 280 MATTHEWS COEFFICIENT, VM (ANGSTROMS**3/DA): NULL                     
REMARK 280                                                                      
REMARK 280 CRYSTALLIZATION CONDITIONS: NULL                                     
REMARK 290                                                                      
REMARK 290 CRYSTALLOGRAPHIC SYMMETRY                                            
REMARK 290 SYMMETRY OPERATORS FOR SPACE GROUP: P 41                             
REMARK 290                                                                      
REMARK 290      SYMOP   SYMMETRY                                                
REMARK 290     NNNMMM   OPERATOR                                                
REMARK 290       1555   X,Y,Z                                                   
REMARK 290       2555   -X,-Y,Z+1/2                                             
REMARK 290       3555   -Y,X,Z+1/4                                              
REMARK 290       4555   Y,-X,Z+3/4                                              
REMARK 290                                                                      
REMARK 290     WHERE NNN -> OPERATOR NUMBER                                     
REMARK 290           MMM -> TRANSLATION VECTOR                                  
REMARK 290                                                                      
REMARK 290 CRYSTALLOGRAPHIC SYMMETRY TRANSFORMATIONS                            
REMARK 290 THE FOLLOWING TRANSFORMATIONS OPERATE ON THE ATOM/HETATM             
REMARK 290 RECORDS IN THIS ENTRY TO PRODUCE CRYSTALLOGRAPHICALLY                
REMARK 290 RELATED MOLECULES.                                                   
REMARK 290   SMTRY1   1  1.000000  0.000000  0.000000        0.00000            
REMARK 290   SMTRY2   1  0.000000  1.000000  0.000000        0.00000            
REMARK 290   SMTRY3   1  0.000000  0.000000  1.000000        0.00000            
REMARK 290   SMTRY1   2 -1.000000  0.000000  0.000000        0.00000            
REMARK 290   SMTRY2   2  0.000000 -1.000000  0.000000        0.00000            
REMARK 290   SMTRY3   2  0.000000  0.000000  1.000000       88.70000            
REMARK 290   SMTRY1   3  0.000000 -1.000000  0.000000        0.00000            
REMARK 290   SMTRY2   3  1.000000  0.000000  0.000000        0.00000            
REMARK 290   SMTRY3   3  0.000000  0.000000  1.000000       44.35000            
REMARK 290   SMTRY1   4  0.000000  1.000000  0.000000        0.00000            
REMARK 290   SMTRY2   4 -1.000000  0.000000  0.000000        0.00000            
REMARK 290   SMTRY3   4  0.000000  0.000000  1.000000      133.05000            
REMARK 290                                                                      
REMARK 290 REMARK: NULL                                                         
REMARK 300                                                                      
REMARK 300 BIOMOLECULE: 1                                                       
REMARK 300 SEE REMARK 350 FOR THE AUTHOR PROVIDED AND/OR PROGRAM                
REMARK 300 GENERATED ASSEMBLY INFORMATION FOR THE STRUCTURE IN                  
REMARK 300 THIS ENTRY. THE REMARK MAY ALSO PROVIDE INFORMATION ON               
REMARK 300 BURIED SURFACE AREA.                                                 
REMARK 300 REMARK: THERE IS ONE TRIMERIC HEMAGGLUTININ MOLECULE IN THE          
REMARK 300 ASYMMETRIC UNIT, WITH THE MONOMERS RELATED TO EACH OTHER             
REMARK 300 BY A NON-CRYSTALLOGRAPHIC THREE-FOLD AXIS.  EACH MONOMER             
REMARK 300 OF HEMAGGLUTININ CONSISTS OF TWO CHAINS, IDENTIFIED                  
REMARK 300 AS HA1 AND HA2 BY THE DEPOSITORS.  CHAINS HA1 AND HA2 OF             
REMARK 300 MONOMER 1 HAVE BEEN ASSIGNED CHAIN IDENTIFIERS *A* AND *B*,          
REMARK 300 RESPECTIVELY.  CHAINS HA1 AND HA2 OF MONOMER 2 HAVE BEEN             
REMARK 300 ASSIGNED CHAIN IDENTIFIERS *C* AND *D*, RESPECTIVELY.                
REMARK 300 CHAINS HA1 AND HA2 OF MONOMER 3 HAVE BEEN ASSIGNED CHAIN             
REMARK 300 IDENTIFIERS *E* AND *F*, RESPECTIVELY.                               
REMARK 300                                                                      
REMARK 300 IN THE VIRUS, CHAIN HA1 CONSISTS OF 328 RESIDUES AND CHAIN           
REMARK 300 HA2 CONSISTS OF 220 RESIDUES.  HEMAGGLUTININ MAY BE                  
REMARK 300 SOLUBILIZED FROM THE VIRAL MEMBRANE BY BROMELAIN DIGESTION,          
REMARK 300 WHICH REMOVES THE C-TERMINAL HYDROPHOBIC (ANCHORING) DOMAIN          
REMARK 300 FROM CHAIN HA2.  AFTER BROMELAIN DIGESTION CHAIN HA2                 
REMARK 300 CONSISTS OF 175 RESIDUES, AS PRESENTED IN THIS ENTRY.                
REMARK 300                                                                      
REMARK 300 IN THIS ENTRY RESIDUE GLY 146 IN CHAINS *A*, *C*, AND *E*            
REMARK 300 HAS BEEN REPLACED BY ASP.  THE WATERS ASSOCIATED WITH EACH           
REMARK 300 MONOMER ARE PRESENTED IMMEDIATELY FOLLOWING CHAIN HA2 OF             
REMARK 300 THAT MONOMER AND HAVE BEEN ASSIGNED THE SAME CHAIN                   
REMARK 300 INDICATOR (*B*, *D*, AND *F*).                                       
REMARK 300                                                                      
REMARK 300 THE *MTRIX 1* TRANSFORMATION BELOW YIELDS APPROXIMATE                
REMARK 300 COORDINATES FOR CHAINS *A* AND *B* WHEN APPLIED TO CHAINS            
REMARK 300 *C* AND *D*.  THE *MTRIX 2* TRANSFORMATION BELOW YIELDS              
REMARK 300 APPROXIMATE COORDINATES FOR CHAINS *A* AND *B* WHEN APPLIED          
REMARK 300 TO CHAINS *E* AND *F*.  FOR THE RESTRAINED REGIONS,                  
REMARK 300 MONOMERS 1 AND 2 SUPERIMPOSE WITH AN RMS DEVIATION OF 0.030          
REMARK 300 ANGSTROMS AND MONOMERS 1 AND 3 SUPERIMPOSE WITH AN RMS               
REMARK 300 DEVIATION OF 0.029 ANGSTROMS.                                        
REMARK 350                                                                      
REMARK 350 COORDINATES FOR A COMPLETE MULTIMER REPRESENTING THE KNOWN           
REMARK 350 BIOLOGICALLY SIGNIFICANT OLIGOMERIZATION STATE OF THE                
REMARK 350 MOLECULE CAN BE GENERATED BY APPLYING BIOMT TRANSFORMATIONS          
REMARK 350 GIVEN BELOW.  BOTH NON-CRYSTALLOGRAPHIC AND                          
REMARK 350 CRYSTALLOGRAPHIC OPERATIONS ARE GIVEN.                               
REMARK 350                                                                      
REMARK 350 BIOMOLECULE: 1                                                       
REMARK 350 AUTHOR DETERMINED BIOLOGICAL UNIT: HEXAMERIC                         
REMARK 350 SOFTWARE DETERMINED QUATERNARY STRUCTURE: HEXAMERIC                  
REMARK 350 SOFTWARE USED: PISA                                                  
REMARK 350 TOTAL BURIED SURFACE AREA: 38680 ANGSTROM**2                         
REMARK 350 SURFACE AREA OF THE COMPLEX: 58860 ANGSTROM**2                       
REMARK 350 CHANGE IN SOLVENT FREE ENERGY: -80.0 KCAL/MOL                        
REMARK 350 APPLY THE FOLLOWING TO CHAINS: A, B, C, D, E, F                      
REMARK 350   BIOMT1   1  1.000000  0.000000  0.000000        0.00000            
REMARK 350   BIOMT2   1  0.000000  1.000000  0.000000        0.00000            
REMARK 350   BIOMT3   1  0.000000  0.000000  1.000000        0.00000            
REMARK 500                                                                      
REMARK 500 GEOMETRY AND STEREOCHEMISTRY                                         
REMARK 500 SUBTOPIC: COVALENT BOND LENGTHS                                      
REMARK 500                                                                      
REMARK 500 THE STEREOCHEMICAL PARAMETERS OF THE FOLLOWING RESIDUES              
REMARK 500 HAVE VALUES WHICH DEVIATE FROM EXPECTED VALUES BY MORE               
REMARK 500 THAN 6*RMSD (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN               
REMARK 500 IDENTIFIER; SSEQ=SEQUENCE NUMBER; I=INSERTION CODE).                 
REMARK 500                                                                      
REMARK 500 STANDARD TABLE:                                                      
REMARK 500 FORMAT: (10X,I3,1X,2(A3,1X,A1,I4,A1,1X,A4,3X),1X,F6.3)               
REMARK 500                                                                      
REMARK 500 EXPECTED VALUES PROTEIN: ENGH AND HUBER, 1999                        
REMARK 500 EXPECTED VALUES NUCLEIC ACID: CLOWNEY ET AL 1996                     
REMARK 500                                                                      
REMARK 500  M RES CSSEQI ATM1   RES CSSEQI ATM2   DEVIATION                     
REMARK 500    HIS A  17   NE2   HIS A  17   CD2    -0.075                       
REMARK 500    HIS A  56   NE2   HIS A  56   CD2    -0.079                       
REMARK 500    HIS A  75   NE2   HIS A  75   CD2    -0.077                       
REMARK 500    HIS B  64   NE2   HIS B  64   CD2    -0.070                       
REMARK 500    HIS B 159   NE2   HIS B 159   CD2    -0.072                       
REMARK 500    HIS C  17   NE2   HIS C  17   CD2    -0.080                       
REMARK 500    HIS C  56   NE2   HIS C  56   CD2    -0.080                       
REMARK 500    HIS C 184   NE2   HIS C 184   CD2    -0.073                       
REMARK 500    HIS D  26   NE2   HIS D  26   CD2    -0.068                       
REMARK 500    HIS D  64   NE2   HIS D  64   CD2    -0.067                       
REMARK 500    HIS D 106   NE2   HIS D 106   CD2    -0.071                       
REMARK 500    HIS D 159   NE2   HIS D 159   CD2    -0.070                       
REMARK 500    HIS E  17   NE2   HIS E  17   CD2    -0.073                       
REMARK 500    HIS E  56   NE2   HIS E  56   CD2    -0.077                       
REMARK 500    HIS E  75   NE2   HIS E  75   CD2    -0.071                       
REMARK 500    HIS E 184   NE2   HIS E 184   CD2    -0.078                       
REMARK 500    HIS F 142   NE2   HIS F 142   CD2    -0.068                       
REMARK 500    HIS F 159   NE2   HIS F 159   CD2    -0.070                       
REMARK 500                                                                      
REMARK 500 REMARK: NULL                                                         
REMARK 500                                                                      
REMARK 500 GEOMETRY AND STEREOCHEMISTRY                                         
REMARK 500 SUBTOPIC: COVALENT BOND ANGLES                                       
REMARK 500                                                                      
REMARK 500 THE STEREOCHEMICAL PARAMETERS OF THE FOLLOWING RESIDUES              
REMARK 500 HAVE VALUES WHICH DEVIATE FROM EXPECTED VALUES BY MORE               
REMARK 500 THAN 6*RMSD (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN               
REMARK 500 IDENTIFIER; SSEQ=SEQUENCE NUMBER; I=INSERTION CODE).                 
REMARK 500                                                                      
REMARK 500 STANDARD TABLE:                                                      
REMARK 500 FORMAT: (10X,I3,1X,A3,1X,A1,I4,A1,3(1X,A4,2X),12X,F5.1)              
REMARK 500                                                                      
REMARK 500 EXPECTED VALUES PROTEIN: ENGH AND HUBER, 1999                        
REMARK 500 EXPECTED VALUES NUCLEIC ACID: CLOWNEY ET AL 1996                     
REMARK 500                                                                      
REMARK 500  M RES CSSEQI ATM1   ATM2   ATM3                                     
REMARK 500    LYS A  27   CA  -  CB  -  CG  ANGL. DEV. =  13.5 DEGREES          
REMARK 500    TRP A  84   CD1 -  CG  -  CD2 ANGL. DEV. =   5.7 DEGREES          
REMARK 500    TRP A  84   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.3 DEGREES          
REMARK 500    TRP A 127   CD1 -  CG  -  CD2 ANGL. DEV. =   7.3 DEGREES          
REMARK 500    TRP A 127   CG  -  CD1 -  NE1 ANGL. DEV. =  -6.2 DEGREES          
REMARK 500    TRP A 127   CE2 -  CD2 -  CG  ANGL. DEV. =  -6.0 DEGREES          
REMARK 500    TRP A 153   CD1 -  CG  -  CD2 ANGL. DEV. =   5.6 DEGREES          
REMARK 500    TRP A 153   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.3 DEGREES          
REMARK 500    TRP A 180   CD1 -  CG  -  CD2 ANGL. DEV. =   6.2 DEGREES          
REMARK 500    TRP A 180   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.7 DEGREES          
REMARK 500    ARG A 207   NE  -  CZ  -  NH1 ANGL. DEV. =  -3.3 DEGREES          
REMARK 500    ARG A 208   NE  -  CZ  -  NH1 ANGL. DEV. =  -3.4 DEGREES          
REMARK 500    TRP A 222   CD1 -  CG  -  CD2 ANGL. DEV. =   6.8 DEGREES          
REMARK 500    TRP A 222   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.9 DEGREES          
REMARK 500    ARG A 229   NE  -  CZ  -  NH1 ANGL. DEV. =  -4.1 DEGREES          
REMARK 500    ARG A 229   NE  -  CZ  -  NH2 ANGL. DEV. =   3.2 DEGREES          
REMARK 500    TRP A 234   CD1 -  CG  -  CD2 ANGL. DEV. =   5.2 DEGREES          
REMARK 500    TRP A 234   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.0 DEGREES          
REMARK 500    ARG A 255   NE  -  CZ  -  NH1 ANGL. DEV. =  -3.8 DEGREES          
REMARK 500    ARG A 255   NE  -  CZ  -  NH2 ANGL. DEV. =   3.1 DEGREES          
REMARK 500    ARG A 321   NE  -  CZ  -  NH1 ANGL. DEV. =  -4.9 DEGREES          
REMARK 500    LYS A 326   CA  -  CB  -  CG  ANGL. DEV. =  15.2 DEGREES          
REMARK 500    TRP B  14   CD1 -  CG  -  CD2 ANGL. DEV. =   6.7 DEGREES          
REMARK 500    TRP B  14   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.9 DEGREES          
REMARK 500    TRP B  21   CD1 -  CG  -  CD2 ANGL. DEV. =   5.4 DEGREES          
REMARK 500    TRP B  21   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.2 DEGREES          
REMARK 500    GLU B  30   N   -  CA  -  CB  ANGL. DEV. = -11.9 DEGREES          
REMARK 500    ASP B  90   CB  -  CG  -  OD1 ANGL. DEV. =   6.9 DEGREES          
REMARK 500    TRP B  92   CD1 -  CG  -  CD2 ANGL. DEV. =   7.1 DEGREES          
REMARK 500    TRP B  92   CG  -  CD1 -  NE1 ANGL. DEV. =  -6.4 DEGREES          
REMARK 500    TRP B  92   CE2 -  CD2 -  CG  ANGL. DEV. =  -6.0 DEGREES          
REMARK 500    ARG B 124   NE  -  CZ  -  NH1 ANGL. DEV. =  -3.7 DEGREES          
REMARK 500    GLU B 132   CA  -  CB  -  CG  ANGL. DEV. = -15.9 DEGREES          
REMARK 500    LYS C  27   CA  -  CB  -  CG  ANGL. DEV. =  13.7 DEGREES          
REMARK 500    THR C  28   CA  -  CB  -  CG2 ANGL. DEV. =   8.7 DEGREES          
REMARK 500    TRP C  84   CD1 -  CG  -  CD2 ANGL. DEV. =   6.3 DEGREES          
REMARK 500    TRP C  84   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.7 DEGREES          
REMARK 500    TRP C 127   CD1 -  CG  -  CD2 ANGL. DEV. =   7.1 DEGREES          
REMARK 500    TRP C 127   CG  -  CD1 -  NE1 ANGL. DEV. =  -6.1 DEGREES          
REMARK 500    TRP C 127   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.8 DEGREES          
REMARK 500    TRP C 153   CD1 -  CG  -  CD2 ANGL. DEV. =   6.6 DEGREES          
REMARK 500    TRP C 153   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.6 DEGREES          
REMARK 500    TRP C 180   CD1 -  CG  -  CD2 ANGL. DEV. =   6.4 DEGREES          
REMARK 500    TRP C 180   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.8 DEGREES          
REMARK 500    ARG C 207   NE  -  CZ  -  NH1 ANGL. DEV. =  -3.5 DEGREES          
REMARK 500    ARG C 208   NE  -  CZ  -  NH1 ANGL. DEV. =  -3.4 DEGREES          
REMARK 500    TRP C 222   CD1 -  CG  -  CD2 ANGL. DEV. =   6.6 DEGREES          
REMARK 500    TRP C 222   CE2 -  CD2 -  CG  ANGL. DEV. =  -5.7 DEGREES          
REMARK 500    ARG C 229   NE  -  CZ  -  NH1 ANGL. DEV. =  -4.8 DEGREES          
REMARK 500    ARG C 229   NE  -  CZ  -  NH2 ANGL. DEV. =   3.4 DEGREES          
REMARK 500                                                                      
REMARK 500 THIS ENTRY HAS      98 ANGLE DEVIATIONS.                             
REMARK 500                                                                      
REMARK 500 REMARK: NULL                                                         
REMARK 500                                                                      
REMARK 500 GEOMETRY AND STEREOCHEMISTRY                                         
REMARK 500 SUBTOPIC: TORSION ANGLES                                             
REMARK 500                                                                      
REMARK 500 TORSION ANGLES OUTSIDE THE EXPECTED RAMACHANDRAN REGIONS:            
REMARK 500 (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN IDENTIFIER;               
REMARK 500 SSEQ=SEQUENCE NUMBER; I=INSERTION CODE).                             
REMARK 500                                                                      
REMARK 500 STANDARD TABLE:                                                      
REMARK 500 FORMAT:(10X,I3,1X,A3,1X,A1,I4,A1,4X,F7.2,3X,F7.2)                    
REMARK 500                                                                      
REMARK 500 EXPECTED VALUES: GJ KLEYWEGT AND TA JONES (1996). PHI/PSI-           
REMARK 500 CHOLOGY: RAMACHANDRAN REVISITED. STRUCTURE 4, 1395 - 1400            
REMARK 500                                                                      
REMARK 500  M RES CSSEQI        PSI       PHI                                   
REMARK 500    ASN A   8      112.70   -160.65                                   
REMARK 500    ASN A  22      -95.01    -80.30                                   
REMARK 500    ASN A  53       25.91    -78.01                                   
REMARK 500    ILE A  62     -117.84     47.23                                   
REMARK 500    ASN A  96       57.61   -155.15                                   
REMARK 500    CYS A  97     -157.82   -153.19                                   
REMARK 500    ASP A 146     -158.68   -140.75                                   
REMARK 500    VAL A 196      -67.77     63.78                                   
REMARK 500    ALA A 304       96.87    -69.07                                   
REMARK 500    GLN A 327      -81.91     72.99                                   
REMARK 500    ALA B   5      -71.33    -84.24                                   
REMARK 500    GLU B  30       40.74    -85.93                                   
REMARK 500    GLU B  57     -164.06    -62.27                                   
REMARK 500    PHE B  63     -110.53   -112.82                                   
REMARK 500    GLN B  65     -141.31   -123.50                                   
REMARK 500    ARG B 127     -124.66     40.98                                   
REMARK 500    TYR B 141       52.24    -92.15                                   
REMARK 500    PHE B 171       51.67   -102.44                                   
REMARK 500    LYS B 174      126.78    164.67                                   
REMARK 500    ASN C  22      -95.08    -80.51                                   
REMARK 500    ASN C  53       25.65    -78.27                                   
REMARK 500    ILE C  62     -118.23     47.17                                   
REMARK 500    ASN C  96       57.52   -156.33                                   
REMARK 500    CYS C  97     -158.86   -154.17                                   
REMARK 500    ASP C 146     -158.44   -140.25                                   
REMARK 500    VAL C 196      -66.95     65.14                                   
REMARK 500    GLN C 327      -73.56    137.19                                   
REMARK 500    ALA D   5      -70.98    -83.05                                   
REMARK 500    GLU D  57     -163.66    -62.27                                   
REMARK 500    PHE D  63     -109.97   -111.83                                   
REMARK 500    GLN D  65     -140.87   -124.87                                   
REMARK 500    ARG D 127     -122.27     41.00                                   
REMARK 500    TYR D 141       50.77    -92.46                                   
REMARK 500    PHE D 171       51.25   -102.21                                   
REMARK 500    LYS D 174      126.55    163.79                                   
REMARK 500    ASN E  22      -94.65    -80.70                                   
REMARK 500    ASN E  53       25.66    -77.48                                   
REMARK 500    ILE E  62     -117.59     45.80                                   
REMARK 500    ASN E  96       57.69   -155.48                                   
REMARK 500    CYS E  97     -158.74   -154.51                                   
REMARK 500    ASP E 146     -158.76   -141.17                                   
REMARK 500    VAL E 196      -66.39     63.26                                   
REMARK 500    LYS E 326      -74.82    -93.81                                   
REMARK 500    GLN E 327      170.21    177.35                                   
REMARK 500    GLU F  57     -163.41    -62.46                                   
REMARK 500    PHE F  63     -109.24   -112.76                                   
REMARK 500    GLN F  65     -140.38   -125.51                                   
REMARK 500    ARG F 127     -123.96     40.67                                   
REMARK 500    TYR F 141       51.53    -90.48                                   
REMARK 500    PHE F 171       50.41   -102.87                                   
REMARK 500                                                                      
REMARK 500 THIS ENTRY HAS      51 RAMACHANDRAN OUTLIERS.                        
REMARK 500                                                                      
REMARK 500 REMARK: NULL                                                         
REMARK 500                                                                      
REMARK 500 GEOMETRY AND STEREOCHEMISTRY                                         
REMARK 500 SUBTOPIC: PLANAR GROUPS                                              
REMARK 500                                                                      
REMARK 500 PLANAR GROUPS IN THE FOLLOWING RESIDUES HAVE A TOTAL                 
REMARK 500 RMS DISTANCE OF ALL ATOMS FROM THE BEST-FIT PLANE                    
REMARK 500 BY MORE THAN AN EXPECTED VALUE OF 6*RMSD, WITH AN                    
REMARK 500 RMSD 0.02 ANGSTROMS, OR AT LEAST ONE ATOM HAS                        
REMARK 500 AN RMSD GREATER THAN THIS VALUE                                      
REMARK 500 (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN IDENTIFIER;               
REMARK 500 SSEQ=SEQUENCE NUMBER; I=INSERTION CODE).                             
REMARK 500                                                                      
REMARK 500  M RES CSSEQI        RMS     TYPE                                    
REMARK 500    TYR C 161         0.07    SIDE CHAIN                              
REMARK 500                                                                      
REMARK 500 REMARK: NULL                                                         
REMARK 800                                                                      
REMARK 800 SITE                                                                 
REMARK 800 SITE_IDENTIFIER: AC1                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG A 329                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC2                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG A 334                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC3                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG A 339                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC4                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG A 340                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC5                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE BMA A 341                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC6                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG A 348                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC7                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG B 401                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC8                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG C 329                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: AC9                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG C 334                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC1                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG C 339                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC2                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG C 340                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC3                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE BMA C 341                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC4                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG C 348                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC5                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG D 401                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC6                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG E 329                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC7                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG E 334                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC8                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG E 339                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: BC9                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG E 340                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: CC1                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE BMA E 341                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: CC2                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG E 348                 
REMARK 800                                                                      
REMARK 800 SITE_IDENTIFIER: CC3                                                 
REMARK 800 EVIDENCE_CODE: SOFTWARE                                              
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE NAG F 401                 
DBREF  2HMG A    1   328  UNP    P03437   HEMA_IAAIC      17    344             
DBREF  2HMG B    1   175  UNP    P03437   HEMA_IAAIC     346    520             
DBREF  2HMG C    1   328  UNP    P03437   HEMA_IAAIC      17    344             
DBREF  2HMG D    1   175  UNP    P03437   HEMA_IAAIC     346    520             
DBREF  2HMG E    1   328  UNP    P03437   HEMA_IAAIC      17    344             
DBREF  2HMG F    1   175  UNP    P03437   HEMA_IAAIC     346    520             
SEQADV 2HMG ASP A  146  UNP  P03437    GLY   162 CONFLICT                       
SEQADV 2HMG ASP C  146  UNP  P03437    GLY   162 CONFLICT                       
SEQADV 2HMG ASP E  146  UNP  P03437    GLY   162 CONFLICT                       
SEQRES   1 A  328  GLN ASP LEU PRO GLY ASN ASP ASN SER THR ALA THR LEU          
SEQRES   2 A  328  CYS LEU GLY HIS HIS ALA VAL PRO ASN GLY THR LEU VAL          
SEQRES   3 A  328  LYS THR ILE THR ASP ASP GLN ILE GLU VAL THR ASN ALA          
SEQRES   4 A  328  THR GLU LEU VAL GLN SER SER SER THR GLY LYS ILE CYS          
SEQRES   5 A  328  ASN ASN PRO HIS ARG ILE LEU ASP GLY ILE ASP CYS THR          
SEQRES   6 A  328  LEU ILE ASP ALA LEU LEU GLY ASP PRO HIS CYS ASP VAL          
SEQRES   7 A  328  PHE GLN ASN GLU THR TRP ASP LEU PHE VAL GLU ARG SER          
SEQRES   8 A  328  LYS ALA PHE SER ASN CYS TYR PRO TYR ASP VAL PRO ASP          
SEQRES   9 A  328  TYR ALA SER LEU ARG SER LEU VAL ALA SER SER GLY THR          
SEQRES  10 A  328  LEU GLU PHE ILE THR GLU GLY PHE THR TRP THR GLY VAL          
SEQRES  11 A  328  THR GLN ASN GLY GLY SER ASN ALA CYS LYS ARG GLY PRO          
SEQRES  12 A  328  GLY SER ASP PHE PHE SER ARG LEU ASN TRP LEU THR LYS          
SEQRES  13 A  328  SER GLY SER THR TYR PRO VAL LEU ASN VAL THR MET PRO          
SEQRES  14 A  328  ASN ASN ASP ASN PHE ASP LYS LEU TYR ILE TRP GLY ILE          
SEQRES  15 A  328  HIS HIS PRO SER THR ASN GLN GLU GLN THR SER LEU TYR          
SEQRES  16 A  328  VAL GLN ALA SER GLY ARG VAL THR VAL SER THR ARG ARG          
SEQRES  17 A  328  SER GLN GLN THR ILE ILE PRO ASN ILE GLY SER ARG PRO          
SEQRES  18 A  328  TRP VAL ARG GLY LEU SER SER ARG ILE SER ILE TYR TRP          
SEQRES  19 A  328  THR ILE VAL LYS PRO GLY ASP VAL LEU VAL ILE ASN SER          
SEQRES  20 A  328  ASN GLY ASN LEU ILE ALA PRO ARG GLY TYR PHE LYS MET          
SEQRES  21 A  328  ARG THR GLY LYS SER SER ILE MET ARG SER ASP ALA PRO          
SEQRES  22 A  328  ILE ASP THR CYS ILE SER GLU CYS ILE THR PRO ASN GLY          
SEQRES  23 A  328  SER ILE PRO ASN ASP LYS PRO PHE GLN ASN VAL ASN LYS          
SEQRES  24 A  328  ILE THR TYR GLY ALA CYS PRO LYS TYR VAL LYS GLN ASN          
SEQRES  25 A  328  THR LEU LYS LEU ALA THR GLY MET ARG ASN VAL PRO GLU          
SEQRES  26 A  328  LYS GLN THR                                                  
SEQRES   1 B  175  GLY LEU PHE GLY ALA ILE ALA GLY PHE ILE GLU ASN GLY          
SEQRES   2 B  175  TRP GLU GLY MET ILE ASP GLY TRP TYR GLY PHE ARG HIS          
SEQRES   3 B  175  GLN ASN SER GLU GLY THR GLY GLN ALA ALA ASP LEU LYS          
SEQRES   4 B  175  SER THR GLN ALA ALA ILE ASP GLN ILE ASN GLY LYS LEU          
SEQRES   5 B  175  ASN ARG VAL ILE GLU LYS THR ASN GLU LYS PHE HIS GLN          
SEQRES   6 B  175  ILE GLU LYS GLU PHE SER GLU VAL GLU GLY ARG ILE GLN          
SEQRES   7 B  175  ASP LEU GLU LYS TYR VAL GLU ASP THR LYS ILE ASP LEU          
SEQRES   8 B  175  TRP SER TYR ASN ALA GLU LEU LEU VAL ALA LEU GLU ASN          
SEQRES   9 B  175  GLN HIS THR ILE ASP LEU THR ASP SER GLU MET ASN LYS          
SEQRES  10 B  175  LEU PHE GLU LYS THR ARG ARG GLN LEU ARG GLU ASN ALA          
SEQRES  11 B  175  GLU GLU MET GLY ASN GLY CYS PHE LYS ILE TYR HIS LYS          
SEQRES  12 B  175  CYS ASP ASN ALA CYS ILE GLU SER ILE ARG ASN GLY THR          
SEQRES  13 B  175  TYR ASP HIS ASP VAL TYR ARG ASP GLU ALA LEU ASN ASN          
SEQRES  14 B  175  ARG PHE GLN ILE LYS GLY                                      
SEQRES   1 C  328  GLN ASP LEU PRO GLY ASN ASP ASN SER THR ALA THR LEU          
SEQRES   2 C  328  CYS LEU GLY HIS HIS ALA VAL PRO ASN GLY THR LEU VAL          
SEQRES   3 C  328  LYS THR ILE THR ASP ASP GLN ILE GLU VAL THR ASN ALA          
SEQRES   4 C  328  THR GLU LEU VAL GLN SER SER SER THR GLY LYS ILE CYS          
SEQRES   5 C  328  ASN ASN PRO HIS ARG ILE LEU ASP GLY ILE ASP CYS THR          
SEQRES   6 C  328  LEU ILE ASP ALA LEU LEU GLY ASP PRO HIS CYS ASP VAL          
SEQRES   7 C  328  PHE GLN ASN GLU THR TRP ASP LEU PHE VAL GLU ARG SER          
SEQRES   8 C  328  LYS ALA PHE SER ASN CYS TYR PRO TYR ASP VAL PRO ASP          
SEQRES   9 C  328  TYR ALA SER LEU ARG SER LEU VAL ALA SER SER GLY THR          
SEQRES  10 C  328  LEU GLU PHE ILE THR GLU GLY PHE THR TRP THR GLY VAL          
SEQRES  11 C  328  THR GLN ASN GLY GLY SER ASN ALA CYS LYS ARG GLY PRO          
SEQRES  12 C  328  GLY SER ASP PHE PHE SER ARG LEU ASN TRP LEU THR LYS          
SEQRES  13 C  328  SER GLY SER THR TYR PRO VAL LEU ASN VAL THR MET PRO          
SEQRES  14 C  328  ASN ASN ASP ASN PHE ASP LYS LEU TYR ILE TRP GLY ILE          
SEQRES  15 C  328  HIS HIS PRO SER THR ASN GLN GLU GLN THR SER LEU TYR          
SEQRES  16 C  328  VAL GLN ALA SER GLY ARG VAL THR VAL SER THR ARG ARG          
SEQRES  17 C  328  SER GLN GLN THR ILE ILE PRO ASN ILE GLY SER ARG PRO          
SEQRES  18 C  328  TRP VAL ARG GLY LEU SER SER ARG ILE SER ILE TYR TRP          
SEQRES  19 C  328  THR ILE VAL LYS PRO GLY ASP VAL LEU VAL ILE ASN SER          
SEQRES  20 C  328  ASN GLY ASN LEU ILE ALA PRO ARG GLY TYR PHE LYS MET          
SEQRES  21 C  328  ARG THR GLY LYS SER SER ILE MET ARG SER ASP ALA PRO          
SEQRES  22 C  328  ILE ASP THR CYS ILE SER GLU CYS ILE THR PRO ASN GLY          
SEQRES  23 C  328  SER ILE PRO ASN ASP LYS PRO PHE GLN ASN VAL ASN LYS          
SEQRES  24 C  328  ILE THR TYR GLY ALA CYS PRO LYS TYR VAL LYS GLN ASN          
SEQRES  25 C  328  THR LEU LYS LEU ALA THR GLY MET ARG ASN VAL PRO GLU          
SEQRES  26 C  328  LYS GLN THR                                                  
SEQRES   1 D  175  GLY LEU PHE GLY ALA ILE ALA GLY PHE ILE GLU ASN GLY          
SEQRES   2 D  175  TRP GLU GLY MET ILE ASP GLY TRP TYR GLY PHE ARG HIS          
SEQRES   3 D  175  GLN ASN SER GLU GLY THR GLY GLN ALA ALA ASP LEU LYS          
SEQRES   4 D  175  SER THR GLN ALA ALA ILE ASP GLN ILE ASN GLY LYS LEU          
SEQRES   5 D  175  ASN ARG VAL ILE GLU LYS THR ASN GLU LYS PHE HIS GLN          
SEQRES   6 D  175  ILE GLU LYS GLU PHE SER GLU VAL GLU GLY ARG ILE GLN          
SEQRES   7 D  175  ASP LEU GLU LYS TYR VAL GLU ASP THR LYS ILE ASP LEU          
SEQRES   8 D  175  TRP SER TYR ASN ALA GLU LEU LEU VAL ALA LEU GLU ASN          
SEQRES   9 D  175  GLN HIS THR ILE ASP LEU THR ASP SER GLU MET ASN LYS          
SEQRES  10 D  175  LEU PHE GLU LYS THR ARG ARG GLN LEU ARG GLU ASN ALA          
SEQRES  11 D  175  GLU GLU MET GLY ASN GLY CYS PHE LYS ILE TYR HIS LYS          
SEQRES  12 D  175  CYS ASP ASN ALA CYS ILE GLU SER ILE ARG ASN GLY THR          
SEQRES  13 D  175  TYR ASP HIS ASP VAL TYR ARG ASP GLU ALA LEU ASN ASN          
SEQRES  14 D  175  ARG PHE GLN ILE LYS GLY                                      
SEQRES   1 E  328  GLN ASP LEU PRO GLY ASN ASP ASN SER THR ALA THR LEU          
SEQRES   2 E  328  CYS LEU GLY HIS HIS ALA VAL PRO ASN GLY THR LEU VAL          
SEQRES   3 E  328  LYS THR ILE THR ASP ASP GLN ILE GLU VAL THR ASN ALA          
SEQRES   4 E  328  THR GLU LEU VAL GLN SER SER SER THR GLY LYS ILE CYS          
SEQRES   5 E  328  ASN ASN PRO HIS ARG ILE LEU ASP GLY ILE ASP CYS THR          
SEQRES   6 E  328  LEU ILE ASP ALA LEU LEU GLY ASP PRO HIS CYS ASP VAL          
SEQRES   7 E  328  PHE GLN ASN GLU THR TRP ASP LEU PHE VAL GLU ARG SER          
SEQRES   8 E  328  LYS ALA PHE SER ASN CYS TYR PRO TYR ASP VAL PRO ASP          
SEQRES   9 E  328  TYR ALA SER LEU ARG SER LEU VAL ALA SER SER GLY THR          
SEQRES  10 E  328  LEU GLU PHE ILE THR GLU GLY PHE THR TRP THR GLY VAL          
SEQRES  11 E  328  THR GLN ASN GLY GLY SER ASN ALA CYS LYS ARG GLY PRO          
SEQRES  12 E  328  GLY SER ASP PHE PHE SER ARG LEU ASN TRP LEU THR LYS          
SEQRES  13 E  328  SER GLY SER THR TYR PRO VAL LEU ASN VAL THR MET PRO          
SEQRES  14 E  328  ASN ASN ASP ASN PHE ASP LYS LEU TYR ILE TRP GLY ILE          
SEQRES  15 E  328  HIS HIS PRO SER THR ASN GLN GLU GLN THR SER LEU TYR          
SEQRES  16 E  328  VAL GLN ALA SER GLY ARG VAL THR VAL SER THR ARG ARG          
SEQRES  17 E  328  SER GLN GLN THR ILE ILE PRO ASN ILE GLY SER ARG PRO          
SEQRES  18 E  328  TRP VAL ARG GLY LEU SER SER ARG ILE SER ILE TYR TRP          
SEQRES  19 E  328  THR ILE VAL LYS PRO GLY ASP VAL LEU VAL ILE ASN SER          
SEQRES  20 E  328  ASN GLY ASN LEU ILE ALA PRO ARG GLY TYR PHE LYS MET          
SEQRES  21 E  328  ARG THR GLY LYS SER SER ILE MET ARG SER ASP ALA PRO          
SEQRES  22 E  328  ILE ASP THR CYS ILE SER GLU CYS ILE THR PRO ASN GLY          
SEQRES  23 E  328  SER ILE PRO ASN ASP LYS PRO PHE GLN ASN VAL ASN LYS          
SEQRES  24 E  328  ILE THR TYR GLY ALA CYS PRO LYS TYR VAL LYS GLN ASN          
SEQRES  25 E  328  THR LEU LYS LEU ALA THR GLY MET ARG ASN VAL PRO GLU          
SEQRES  26 E  328  LYS GLN THR                                                  
SEQRES   1 F  175  GLY LEU PHE GLY ALA ILE ALA GLY PHE ILE GLU ASN GLY          
SEQRES   2 F  175  TRP GLU GLY MET ILE ASP GLY TRP TYR GLY PHE ARG HIS          
SEQRES   3 F  175  GLN ASN SER GLU GLY THR GLY GLN ALA ALA ASP LEU LYS          
SEQRES   4 F  175  SER THR GLN ALA ALA ILE ASP GLN ILE ASN GLY LYS LEU          
SEQRES   5 F  175  ASN ARG VAL ILE GLU LYS THR ASN GLU LYS PHE HIS GLN          
SEQRES   6 F  175  ILE GLU LYS GLU PHE SER GLU VAL GLU GLY ARG ILE GLN          
SEQRES   7 F  175  ASP LEU GLU LYS TYR VAL GLU ASP THR LYS ILE ASP LEU          
SEQRES   8 F  175  TRP SER TYR ASN ALA GLU LEU LEU VAL ALA LEU GLU ASN          
SEQRES   9 F  175  GLN HIS THR ILE ASP LEU THR ASP SER GLU MET ASN LYS          
SEQRES  10 F  175  LEU PHE GLU LYS THR ARG ARG GLN LEU ARG GLU ASN ALA          
SEQRES  11 F  175  GLU GLU MET GLY ASN GLY CYS PHE LYS ILE TYR HIS LYS          
SEQRES  12 F  175  CYS ASP ASN ALA CYS ILE GLU SER ILE ARG ASN GLY THR          
SEQRES  13 F  175  TYR ASP HIS ASP VAL TYR ARG ASP GLU ALA LEU ASN ASN          
SEQRES  14 F  175  ARG PHE GLN ILE LYS GLY                                      
MODRES 2HMG ASN A   38  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN A   81  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN A  165  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN A  285  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN B  154  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN C   38  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN C   81  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN C  165  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN C  285  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN D  154  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN E   38  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN E   81  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN E  165  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN E  285  ASN  GLYCOSYLATION SITE                                 
MODRES 2HMG ASN F  154  ASN  GLYCOSYLATION SITE                                 
HET    NAG  A 329      14                                                       
HET    NAG  A 334      14                                                       
HET    NAG  A 339      14                                                       
HET    NAG  A 340      14                                                       
HET    BMA  A 341      11                                                       
HET    NAG  A 348      14                                                       
HET    NAG  B 401      14                                                       
HET    NAG  C 329      14                                                       
HET    NAG  C 334      14                                                       
HET    NAG  C 339      14                                                       
HET    NAG  C 340      14                                                       
HET    BMA  C 341      11                                                       
HET    NAG  C 348      14                                                       
HET    NAG  D 401      14                                                       
HET    NAG  E 329      14                                                       
HET    NAG  E 334      14                                                       
HET    NAG  E 339      14                                                       
HET    NAG  E 340      14                                                       
HET    BMA  E 341      11                                                       
HET    NAG  E 348      14                                                       
HET    NAG  F 401      14                                                       
HETNAM     NAG N-ACETYL-D-GLUCOSAMINE                                           
HETNAM     BMA BETA-D-MANNOSE                                                   
FORMUL   7  NAG    18(C8 H15 N O6)                                              
FORMUL   9  BMA    3(C6 H12 O6)                                                 
FORMUL  22  HOH   *33(H2 O)                                                     
HELIX    1 HAA LEU A   66  LEU A   71  1                                   6    
HELIX    2 HBA TYR A  105  SER A  115  1                                  11    
HELIX    3 HCA ASN A  188  LEU A  194  1                                   7    
HELIX    4 HDB LEU B   38  VAL B   55  1                                  18    
HELIX    5 HEB ARG B   76  GLN B  125  1                                  50    
HELIX    6 HFB ASN B  146  ARG B  153  1                                   8    
HELIX    7 HGB ARG B  163  ASN B  168  1                                   6    
HELIX    8 HAC LEU C   66  LEU C   71  1                                   6    
HELIX    9 HBC TYR C  105  SER C  115  1                                  11    
HELIX   10 HCC ASN C  188  LEU C  194  1                                   7    
HELIX   11 HDD LEU D   38  VAL D   55  1                                  18    
HELIX   12 HED ARG D   76  GLN D  125  1                                  50    
HELIX   13 HFD ASN D  146  ARG D  153  1                                   8    
HELIX   14 HGD ARG D  163  ASN D  168  1                                   6    
HELIX   15 HAE LEU E   66  LEU E   71  1                                   6    
HELIX   16 HBE TYR E  105  SER E  115  1                                  11    
HELIX   17 HCE ASN E  188  LEU E  194  1                                   7    
HELIX   18 HDF LEU F   38  VAL F   55  1                                  18    
HELIX   19 HEF ARG F   76  GLN F  125  1                                  50    
HELIX   20 HFF ASN F  146  ARG F  153  1                                   8    
HELIX   21 HGF ARG F  163  ASN F  168  1                                   6    
SHEET    1 B1A 9 GLU A 119  ILE A 121  0                                        
SHEET    2 B1A 9 LEU A 251  LYS A 259 -1                                        
SHEET    3 B1A 9 LYS A 176  HIS A 184 -1                                        
SHEET    4 B1A 9 ARG A 229  VAL A 237 -1                                        
SHEET    5 B1A 9 GLN A 210  ILE A 213 -1                                        
SHEET    6 B1A 9 ARG A 201  SER A 205 -1                                        
SHEET    7 B1A 9 ASP A 241  SER A 247 -1                                        
SHEET    8 B1A 9 LEU A 164  ASN A 170 -1                                        
SHEET    9 B1A 9 GLU A 119  ILE A 121 -1                                        
SHEET    1 B2A 9 ASN A 152  LEU A 154  0                                        
SHEET    2 B2A 9 LEU A 251  LYS A 259 -1                                        
SHEET    3 B2A 9 LYS A 176  HIS A 184 -1                                        
SHEET    4 B2A 9 ARG A 229  VAL A 237 -1                                        
SHEET    5 B2A 9 GLN A 210  ILE A 213 -1                                        
SHEET    6 B2A 9 ARG A 201  SER A 205 -1                                        
SHEET    7 B2A 9 ASP A 241  SER A 247 -1                                        
SHEET    8 B2A 9 LEU A 164  ASN A 170 -1                                        
SHEET    9 B2A 9 ASN A 152  LEU A 154 -1                                        
SHEET    1 B1C 9 GLU C 119  ILE C 121  0                                        
SHEET    2 B1C 9 LEU C 251  LYS C 259 -1                                        
SHEET    3 B1C 9 LYS C 176  HIS C 184 -1                                        
SHEET    4 B1C 9 ARG C 229  VAL C 237 -1                                        
SHEET    5 B1C 9 GLN C 210  ILE C 213 -1                                        
SHEET    6 B1C 9 ARG C 201  SER C 205 -1                                        
SHEET    7 B1C 9 ASP C 241  SER C 247 -1                                        
SHEET    8 B1C 9 LEU C 164  ASN C 170 -1                                        
SHEET    9 B1C 9 GLU C 119  ILE C 121 -1                                        
SHEET    1 B2C 9 ASN C 152  LEU C 154  0                                        
SHEET    2 B2C 9 LEU C 251  LYS C 259 -1                                        
SHEET    3 B2C 9 LYS C 176  HIS C 184 -1                                        
SHEET    4 B2C 9 ARG C 229  VAL C 237 -1                                        
SHEET    5 B2C 9 GLN C 210  ILE C 213 -1                                        
SHEET    6 B2C 9 ARG C 201  SER C 205 -1                                        
SHEET    7 B2C 9 ASP C 241  SER C 247 -1                                        
SHEET    8 B2C 9 LEU C 164  ASN C 170 -1                                        
SHEET    9 B2C 9 ASN C 152  LEU C 154 -1                                        
SHEET    1 B1E 9 GLU E 119  ILE E 121  0                                        
SHEET    2 B1E 9 LEU E 251  LYS E 259 -1                                        
SHEET    3 B1E 9 LYS E 176  HIS E 184 -1                                        
SHEET    4 B1E 9 ARG E 229  VAL E 237 -1                                        
SHEET    5 B1E 9 GLN E 210  ILE E 213 -1                                        
SHEET    6 B1E 9 ARG E 201  SER E 205 -1                                        
SHEET    7 B1E 9 ASP E 241  SER E 247 -1                                        
SHEET    8 B1E 9 LEU E 164  ASN E 170 -1                                        
SHEET    9 B1E 9 GLU E 119  ILE E 121 -1                                        
SHEET    1 B2E 9 ASN E 152  LEU E 154  0                                        
SHEET    2 B2E 9 LEU E 251  LYS E 259 -1                                        
SHEET    3 B2E 9 LYS E 176  HIS E 184 -1                                        
SHEET    4 B2E 9 ARG E 229  VAL E 237 -1                                        
SHEET    5 B2E 9 GLN E 210  ILE E 213 -1                                        
SHEET    6 B2E 9 ARG E 201  SER E 205 -1                                        
SHEET    7 B2E 9 ASP E 241  SER E 247 -1                                        
SHEET    8 B2E 9 LEU E 164  ASN E 170 -1                                        
SHEET    9 B2E 9 ASN E 152  LEU E 154 -1                                        
SHEET    1 SAB 5 GLY B  31  ASP B  37  0                                        
SHEET    2 SAB 5 TYR B  22  ASN B  28 -1                                        
SHEET    3 SAB 5 ALA A  11  HIS A  17 -1                                        
SHEET    4 SAB 5 GLY B 136  ILE B 140 -1                                        
SHEET    5 SAB 5 ASN B 129  MET B 133 -1                                        
SHEET    1 SCD 5 GLY D  31  ASP D  37  0                                        
SHEET    2 SCD 5 TYR D  22  ASN D  28 -1                                        
SHEET    3 SCD 5 ALA C  11  HIS C  17 -1                                        
SHEET    4 SCD 5 GLY D 136  ILE D 140 -1                                        
SHEET    5 SCD 5 ASN D 129  MET D 133 -1                                        
SHEET    1 SEF 5 GLY F  31  ASP F  37  0                                        
SHEET    2 SEF 5 TYR F  22  ASN F  28 -1                                        
SHEET    3 SEF 5 ALA E  11  HIS E  17 -1                                        
SHEET    4 SEF 5 GLY F 136  ILE F 140 -1                                        
SHEET    5 SEF 5 ASN F 129  MET F 133 -1                                        
SSBOND   1 CYS A   14    CYS B  137                          1555   1555  2.00  
SSBOND   2 CYS A   52    CYS A  277                          1555   1555  2.00  
SSBOND   3 CYS A   64    CYS A   76                          1555   1555  2.01  
SSBOND   4 CYS A   97    CYS A  139                          1555   1555  1.97  
SSBOND   5 CYS A  281    CYS A  305                          1555   1555  2.01  
SSBOND   6 CYS B  144    CYS B  148                          1555   1555  2.03  
SSBOND   7 CYS C   14    CYS D  137                          1555   1555  2.01  
SSBOND   8 CYS C   52    CYS C  277                          1555   1555  2.02  
SSBOND   9 CYS C   64    CYS C   76                          1555   1555  2.00  
SSBOND  10 CYS C   97    CYS C  139                          1555   1555  2.01  
SSBOND  11 CYS C  281    CYS C  305                          1555   1555  2.00  
SSBOND  12 CYS D  144    CYS D  148                          1555   1555  2.00  
SSBOND  13 CYS E   14    CYS F  137                          1555   1555  1.98  
SSBOND  14 CYS E   52    CYS E  277                          1555   1555  2.02  
SSBOND  15 CYS E   64    CYS E   76                          1555   1555  1.99  
SSBOND  16 CYS E   97    CYS E  139                          1555   1555  1.98  
SSBOND  17 CYS E  281    CYS E  305                          1555   1555  1.98  
SSBOND  18 CYS F  144    CYS F  148                          1555   1555  2.00  
LINK         ND2 ASN A  38                 C1  NAG A 329     1555   1555  1.45  
LINK         ND2 ASN A  81                 C1  NAG A 334     1555   1555  1.46  
LINK         ND2 ASN A 165                 C1  NAG A 339     1555   1555  1.46  
LINK         ND2 ASN A 285                 C1  NAG A 348     1555   1555  1.45  
LINK         ND2 ASN B 154                 C1  NAG B 401     1555   1555  1.44  
LINK         ND2 ASN C  38                 C1  NAG C 329     1555   1555  1.45  
LINK         ND2 ASN C  81                 C1  NAG C 334     1555   1555  1.46  
LINK         ND2 ASN C 165                 C1  NAG C 339     1555   1555  1.46  
LINK         ND2 ASN C 285                 C1  NAG C 348     1555   1555  1.44  
LINK         ND2 ASN D 154                 C1  NAG D 401     1555   1555  1.46  
LINK         ND2 ASN E  38                 C1  NAG E 329     1555   1555  1.44  
LINK         ND2 ASN E  81                 C1  NAG E 334     1555   1555  1.46  
LINK         ND2 ASN E 165                 C1  NAG E 339     1555   1555  1.47  
LINK         ND2 ASN E 285                 C1  NAG E 348     1555   1555  1.44  
LINK         ND2 ASN F 154                 C1  NAG F 401     1555   1555  1.45  
LINK         O4  NAG A 339                 C1  NAG A 340     1555   1555  1.44  
LINK         O4  NAG A 340                 C1  BMA A 341     1555   1555  1.40  
LINK         O4  NAG C 339                 C1  NAG C 340     1555   1555  1.43  
LINK         O4  NAG C 340                 C1  BMA C 341     1555   1555  1.44  
LINK         O4  NAG E 339                 C1  NAG E 340     1555   1555  1.43  
LINK         O4  NAG E 340                 C1  BMA E 341     1555   1555  1.44  
CISPEP   1 ASN A   54    PRO A   55          0        -0.07                     
CISPEP   2 ASN C   54    PRO C   55          0        -0.22                     
CISPEP   3 ASN E   54    PRO E   55          0        -0.35                     
SITE     1 AC1  3 ASN A  38  THR A 318  LEU B  52                               
SITE     1 AC2  4 GLN A  80  ASN A  81  PHE A 120  ILE A 121                    
SITE     1 AC3  4 ASN A 165  THR A 167  NAG A 340  SER E 219                    
SITE     1 AC4  4 NAG A 339  BMA A 341  PRO E 221  TRP E 222                    
SITE     1 AC5  2 NAG A 340  TRP E 222                                          
SITE     1 AC6  3 SER A  45  ASN A 285  VAL A 297                               
SITE     1 AC7  4 ALA B 147  GLU B 150  ASN B 154  THR B 156                    
SITE     1 AC8  3 ASN C  38  THR C 318  LEU D  52                               
SITE     1 AC9  4 GLN C  80  ASN C  81  PHE C 120  ILE C 121                    
SITE     1 BC1  4 SER A 219  ASN C 165  THR C 167  NAG C 340                    
SITE     1 BC2  4 PRO A 221  TRP A 222  NAG C 339  BMA C 341                    
SITE     1 BC3  1 NAG C 340                                                     
SITE     1 BC4  4 SER C  45  ASN C 285  VAL C 297  ASN C 298                    
SITE     1 BC5  4 ALA D 147  GLU D 150  ASN D 154  THR D 156                    
SITE     1 BC6  3 ASN E  38  THR E 318  LEU F  52                               
SITE     1 BC7  4 GLN E  80  ASN E  81  PHE E 120  ILE E 121                    
SITE     1 BC8  5 SER C 219  ASN E 165  THR E 167  NAG E 340                    
SITE     2 BC8  5 SER F  29                                                     
SITE     1 BC9  5 PRO C 221  TRP C 222  NAG E 339  BMA E 341                    
SITE     2 BC9  5 SER F  29                                                     
SITE     1 CC1  1 NAG E 340                                                     
SITE     1 CC2  4 SER E  45  ASN E 285  VAL E 297  ASN E 298                    
SITE     1 CC3  4 ALA F 147  GLU F 150  ASN F 154  THR F 156                    
CRYST1  162.600  162.600  177.400  90.00  90.00  90.00 P 41         12          
ORIGX1      1.000000  0.000000  0.000000        0.00000                         
ORIGX2      0.000000  1.000000  0.000000        0.00000                         
ORIGX3      0.000000  0.000000  1.000000        0.00000                         
SCALE1      0.006150  0.000000  0.000000        0.00000                         
SCALE2      0.000000  0.006150  0.000000        0.00000                         
SCALE3      0.000000  0.000000  0.005637        0.00000                         
MTRIX1   1  0.034333 -0.550874  0.833882       41.41870    1                    
MTRIX2   1 -0.851708  0.420417  0.312800       45.28070    1                    
MTRIX3   1 -0.522891 -0.720963 -0.454749       61.88980    1                    
MTRIX1   2  0.034333 -0.851708 -0.522891       69.50550    1                    
MTRIX2   2 -0.550874  0.420417 -0.720963       48.39990    1                    
MTRIX3   2  0.833882  0.312800 -0.454749      -20.55770    1                    
ATOM   2538  N   GLY B   1      42.998   7.613  20.823  1.00 15.41           N  
ATOM   2539  CA  GLY B   1      43.353   8.847  20.162  1.00 14.34           C  
ATOM   2540  C   GLY B   1      44.590   8.611  19.295  1.00 13.18           C  
ATOM   2541  O   GLY B   1      44.833   7.457  18.891  1.00 13.78           O  
ATOM   2542  N   LEU B   2      45.393   9.645  19.051  1.00 11.52           N  
ATOM   2543  CA  LEU B   2      46.484   9.543  18.122  1.00 10.52           C  
ATOM   2544  C   LEU B   2      47.559   8.582  18.566  1.00 10.41           C  
ATOM   2545  O   LEU B   2      48.283   8.075  17.701  1.00 11.02           O  
ATOM   2546  CB  LEU B   2      47.154  10.915  17.868  1.00 10.02           C  
ATOM   2547  CG  LEU B   2      46.517  12.023  17.055  1.00  9.19           C  
ATOM   2548  CD1 LEU B   2      47.459  13.184  17.006  1.00  8.27           C  
ATOM   2549  CD2 LEU B   2      46.307  11.607  15.633  1.00  9.69           C  
ATOM   2550  N   PHE B   3      47.700   8.281  19.850  1.00  9.33           N  
ATOM   2551  CA  PHE B   3      48.828   7.442  20.193  1.00  9.29           C  
ATOM   2552  C   PHE B   3      48.432   5.996  20.406  1.00 10.35           C  
ATOM   2553  O   PHE B   3      49.255   5.085  20.281  1.00 11.93           O  
ATOM   2554  CB  PHE B   3      49.498   8.051  21.411  1.00  7.71           C  
ATOM   2555  CG  PHE B   3      50.052   9.414  21.057  1.00  5.04           C  
ATOM   2556  CD1 PHE B   3      49.227  10.511  21.056  1.00  4.73           C  
ATOM   2557  CD2 PHE B   3      51.358   9.533  20.682  1.00  4.23           C  
ATOM   2558  CE1 PHE B   3      49.704  11.740  20.665  1.00  5.01           C  
ATOM   2559  CE2 PHE B   3      51.818  10.764  20.292  1.00  5.33           C  
ATOM   2560  CZ  PHE B   3      51.003  11.869  20.279  1.00  5.32           C  
ATOM   2561  N   GLY B   4      47.158   5.732  20.676  1.00 10.17           N  
ATOM   2562  CA  GLY B   4      46.714   4.356  20.741  1.00 10.19           C  
ATOM   2563  C   GLY B   4      47.053   3.639  22.025  1.00  9.37           C  
ATOM   2564  O   GLY B   4      47.050   2.410  22.049  1.00  9.05           O  
ATOM   2565  N   ALA B   5      47.363   4.366  23.095  1.00  9.06           N  
ATOM   2566  CA  ALA B   5      47.542   3.778  24.397  1.00  7.30           C  
ATOM   2567  C   ALA B   5      46.159   3.665  24.998  1.00  6.93           C  
ATOM   2568  O   ALA B   5      45.621   2.554  25.032  1.00  6.21           O  
ATOM   2569  CB  ALA B   5      48.406   4.670  25.255  1.00  6.05           C  
ATOM   2570  N   ILE B   6      45.532   4.790  25.387  1.00  7.77           N  
ATOM   2571  CA  ILE B   6      44.202   4.772  26.015  1.00  8.96           C  
ATOM   2572  C   ILE B   6      43.206   4.283  24.983  1.00 10.28           C  
ATOM   2573  O   ILE B   6      43.187   4.768  23.840  1.00 11.37           O  
ATOM   2574  CB  ILE B   6      43.744   6.190  26.493  1.00  7.57           C  
ATOM   2575  CG1 ILE B   6      44.519   6.568  27.690  1.00  7.99           C  
ATOM   2576  CG2 ILE B   6      42.282   6.210  26.867  1.00  6.79           C  
ATOM   2577  CD1 ILE B   6      44.278   7.987  28.149  1.00  8.54           C  
ATOM   2578  N   ALA B   7      42.363   3.362  25.412  1.00 10.82           N  
ATOM   2579  CA  ALA B   7      41.394   2.740  24.542  1.00 12.34           C  
ATOM   2580  C   ALA B   7      42.079   2.172  23.312  1.00 12.64           C  
ATOM   2581  O   ALA B   7      41.518   2.242  22.215  1.00 13.71           O  
ATOM   2582  CB  ALA B   7      40.340   3.756  24.096  1.00 12.81           C  
ATOM   2583  N   GLY B   8      43.284   1.639  23.526  1.00 12.27           N  
ATOM   2584  CA  GLY B   8      44.063   1.087  22.461  1.00 14.18           C  
ATOM   2585  C   GLY B   8      44.796  -0.084  23.035  1.00 15.01           C  
ATOM   2586  O   GLY B   8      44.144  -0.995  23.542  1.00 15.83           O  
ATOM   2587  N   PHE B   9      46.128  -0.042  23.092  1.00 15.24           N  
ATOM   2588  CA  PHE B   9      46.860  -1.185  23.589  1.00 14.82           C  
ATOM   2589  C   PHE B   9      46.614  -1.445  25.038  1.00 15.96           C  
ATOM   2590  O   PHE B   9      47.030  -2.482  25.546  1.00 17.89           O  
ATOM   2591  CB  PHE B   9      48.383  -1.063  23.380  1.00 14.15           C  
ATOM   2592  CG  PHE B   9      49.276  -0.015  24.010  1.00 13.49           C  
ATOM   2593  CD1 PHE B   9      49.733  -0.181  25.286  1.00 13.73           C  
ATOM   2594  CD2 PHE B   9      49.631   1.092  23.283  1.00 13.05           C  
ATOM   2595  CE1 PHE B   9      50.556   0.771  25.842  1.00 13.22           C  
ATOM   2596  CE2 PHE B   9      50.456   2.027  23.863  1.00 13.19           C  
ATOM   2597  CZ  PHE B   9      50.919   1.878  25.144  1.00 12.61           C  
ATOM   2598  N   ILE B  10      46.024  -0.485  25.752  1.00 16.09           N  
ATOM   2599  CA  ILE B  10      45.627  -0.676  27.123  1.00 15.16           C  
ATOM   2600  C   ILE B  10      44.130  -0.876  27.024  1.00 17.66           C  
ATOM   2601  O   ILE B  10      43.370   0.097  26.858  1.00 16.76           O  
ATOM   2602  CB  ILE B  10      46.069   0.592  27.879  1.00 14.05           C  
ATOM   2603  CG1 ILE B  10      47.587   0.581  27.953  1.00 13.34           C  
ATOM   2604  CG2 ILE B  10      45.441   0.668  29.253  1.00 13.30           C  
ATOM   2605  CD1 ILE B  10      48.201   1.759  28.699  1.00 13.25           C  
ATOM   2606  N   GLU B  11      43.702  -2.134  27.104  1.00 21.09           N  
ATOM   2607  CA  GLU B  11      42.309  -2.480  26.886  1.00 25.00           C  
ATOM   2608  C   GLU B  11      41.310  -1.619  27.631  1.00 24.39           C  
ATOM   2609  O   GLU B  11      40.335  -1.163  27.037  1.00 25.43           O  
ATOM   2610  CB  GLU B  11      42.056  -3.949  27.245  1.00 30.58           C  
ATOM   2611  CG  GLU B  11      43.043  -5.020  26.678  1.00 38.04           C  
ATOM   2612  CD  GLU B  11      43.406  -4.975  25.163  1.00 42.01           C  
ATOM   2613  OE1 GLU B  11      42.567  -5.414  24.357  1.00 44.13           O  
ATOM   2614  OE2 GLU B  11      44.521  -4.527  24.813  1.00 43.11           O  
ATOM   2615  N   ASN B  12      41.516  -1.247  28.889  1.00 23.49           N  
ATOM   2616  CA  ASN B  12      40.519  -0.430  29.579  1.00 22.80           C  
ATOM   2617  C   ASN B  12      41.108   0.260  30.782  1.00 21.53           C  
ATOM   2618  O   ASN B  12      42.286   0.096  31.089  1.00 22.38           O  
ATOM   2619  CB  ASN B  12      39.349  -1.231  30.061  1.00 24.02           C  
ATOM   2620  CG  ASN B  12      39.799  -2.415  30.885  1.00 26.36           C  
ATOM   2621  OD1 ASN B  12      40.107  -3.471  30.333  1.00 27.42           O  
ATOM   2622  ND2 ASN B  12      39.872  -2.312  32.207  1.00 27.25           N  
ATOM   2623  N   GLY B  13      40.306   1.086  31.411  1.00 19.84           N  
ATOM   2624  CA  GLY B  13      40.743   1.887  32.520  1.00 19.14           C  
ATOM   2625  C   GLY B  13      40.446   1.161  33.806  1.00 19.24           C  
ATOM   2626  O   GLY B  13      39.824   0.097  33.781  1.00 19.67           O  
ATOM   2627  N   TRP B  14      40.886   1.728  34.917  1.00 18.40           N  
ATOM   2628  CA  TRP B  14      40.704   1.116  36.203  1.00 18.01           C  
ATOM   2629  C   TRP B  14      39.808   2.007  37.024  1.00 20.28           C  
ATOM   2630  O   TRP B  14      40.227   3.085  37.451  1.00 19.30           O  
ATOM   2631  CB  TRP B  14      42.023   0.963  36.920  1.00 15.05           C  
ATOM   2632  CG  TRP B  14      43.031   0.023  36.291  1.00 13.26           C  
ATOM   2633  CD1 TRP B  14      42.631  -1.050  35.543  1.00 13.17           C  
ATOM   2634  CD2 TRP B  14      44.388   0.118  36.403  1.00 12.16           C  
ATOM   2635  NE1 TRP B  14      43.738  -1.636  35.177  1.00 13.62           N  
ATOM   2636  CE2 TRP B  14      44.799  -0.975  35.669  1.00 12.69           C  
ATOM   2637  CE3 TRP B  14      45.307   0.941  36.991  1.00 11.81           C  
ATOM   2638  CZ2 TRP B  14      46.134  -1.266  35.497  1.00 12.63           C  
ATOM   2639  CZ3 TRP B  14      46.655   0.658  36.829  1.00 12.76           C  
ATOM   2640  CH2 TRP B  14      47.070  -0.431  36.086  1.00 12.90           C  
ATOM   2641  N   GLU B  15      38.570   1.578  37.252  1.00 24.04           N  
ATOM   2642  CA  GLU B  15      37.649   2.315  38.100  1.00 27.14           C  
ATOM   2643  C   GLU B  15      38.160   2.292  39.519  1.00 27.08           C  
ATOM   2644  O   GLU B  15      37.876   3.136  40.356  1.00 26.16           O  
ATOM   2645  CB  GLU B  15      36.291   1.681  38.054  1.00 30.48           C  
ATOM   2646  CG  GLU B  15      35.645   1.884  36.692  1.00 35.29           C  
ATOM   2647  CD  GLU B  15      34.432   0.979  36.437  1.00 38.91           C  
ATOM   2648  OE1 GLU B  15      34.456   0.280  35.417  1.00 39.75           O  
ATOM   2649  OE2 GLU B  15      33.476   0.985  37.239  1.00 40.44           O  
ATOM   2650  N   GLY B  16      38.939   1.272  39.822  1.00 28.33           N  
ATOM   2651  CA  GLY B  16      39.544   1.176  41.129  1.00 29.57           C  
ATOM   2652  C   GLY B  16      40.624   2.216  41.417  1.00 30.24           C  
ATOM   2653  O   GLY B  16      40.980   2.403  42.582  1.00 31.36           O  
ATOM   2654  N   MET B  17      41.212   2.907  40.439  1.00 30.27           N  
ATOM   2655  CA  MET B  17      42.308   3.790  40.789  1.00 30.60           C  
ATOM   2656  C   MET B  17      41.759   5.115  41.251  1.00 31.08           C  
ATOM   2657  O   MET B  17      41.443   5.979  40.436  1.00 32.37           O  
ATOM   2658  CB  MET B  17      43.221   3.961  39.584  1.00 30.01           C  
ATOM   2659  CG  MET B  17      44.376   4.853  39.957  1.00 29.75           C  
ATOM   2660  SD  MET B  17      45.651   4.536  38.760  1.00 31.07           S  
ATOM   2661  CE  MET B  17      46.311   3.093  39.586  1.00 31.50           C  
ATOM   2662  N   ILE B  18      41.612   5.335  42.549  1.00 31.66           N  
ATOM   2663  CA  ILE B  18      41.024   6.620  42.917  1.00 32.24           C  
ATOM   2664  C   ILE B  18      42.091   7.632  43.313  1.00 32.26           C  
ATOM   2665  O   ILE B  18      41.766   8.794  43.546  1.00 32.90           O  
ATOM   2666  CB  ILE B  18      39.922   6.480  44.091  1.00 32.13           C  
ATOM   2667  CG1 ILE B  18      40.492   6.335  45.510  1.00 32.52           C  
ATOM   2668  CG2 ILE B  18      39.062   5.259  43.737  1.00 31.43           C  
ATOM   2669  CD1 ILE B  18      41.348   5.076  45.859  1.00 33.47           C  
ATOM   2670  N   ASP B  19      43.367   7.271  43.344  1.00 32.28           N  
ATOM   2671  CA  ASP B  19      44.379   8.204  43.805  1.00 32.44           C  
ATOM   2672  C   ASP B  19      45.186   8.905  42.703  1.00 30.99           C  
ATOM   2673  O   ASP B  19      46.141   9.648  42.973  1.00 31.73           O  
ATOM   2674  CB  ASP B  19      45.293   7.440  44.782  1.00 35.10           C  
ATOM   2675  CG  ASP B  19      45.998   6.184  44.255  1.00 38.37           C  
ATOM   2676  OD1 ASP B  19      47.185   6.013  44.569  1.00 39.78           O  
ATOM   2677  OD2 ASP B  19      45.379   5.355  43.552  1.00 40.28           O  
ATOM   2678  N   GLY B  20      44.827   8.786  41.423  1.00 28.38           N  
ATOM   2679  CA  GLY B  20      45.568   9.485  40.379  1.00 24.33           C  
ATOM   2680  C   GLY B  20      45.003   9.122  39.027  1.00 22.06           C  
ATOM   2681  O   GLY B  20      44.082   8.284  38.957  1.00 22.96           O  
ATOM   2682  N   TRP B  21      45.523   9.730  37.952  1.00 18.01           N  
ATOM   2683  CA  TRP B  21      44.958   9.479  36.646  1.00 15.03           C  
ATOM   2684  C   TRP B  21      45.622   8.338  35.912  1.00 14.41           C  
ATOM   2685  O   TRP B  21      44.937   7.633  35.156  1.00 15.55           O  
ATOM   2686  CB  TRP B  21      45.057  10.688  35.787  1.00 13.76           C  
ATOM   2687  CG  TRP B  21      44.057  11.803  36.017  1.00 13.43           C  
ATOM   2688  CD1 TRP B  21      43.354  11.987  37.176  1.00 13.53           C  
ATOM   2689  CD2 TRP B  21      43.784  12.780  35.099  1.00 12.64           C  
ATOM   2690  NE1 TRP B  21      42.653  13.088  36.994  1.00 12.68           N  
ATOM   2691  CE2 TRP B  21      42.881  13.576  35.781  1.00 11.95           C  
ATOM   2692  CE3 TRP B  21      44.178  13.100  33.813  1.00 11.33           C  
ATOM   2693  CZ2 TRP B  21      42.345  14.691  35.198  1.00 11.50           C  
ATOM   2694  CZ3 TRP B  21      43.635  14.230  33.229  1.00 11.16           C  
ATOM   2695  CH2 TRP B  21      42.730  15.022  33.908  1.00 11.08           C  
ATOM   2696  N   TYR B  22      46.922   8.185  36.094  1.00 12.63           N  
ATOM   2697  CA  TYR B  22      47.701   7.135  35.464  1.00 11.92           C  
ATOM   2698  C   TYR B  22      48.386   6.364  36.593  1.00 12.20           C  
ATOM   2699  O   TYR B  22      48.497   6.900  37.697  1.00 11.48           O  
ATOM   2700  CB  TYR B  22      48.767   7.743  34.544  1.00 10.74           C  
ATOM   2701  CG  TYR B  22      48.209   8.677  33.470  1.00  8.96           C  
ATOM   2702  CD1 TYR B  22      47.622   8.189  32.309  1.00  7.89           C  
ATOM   2703  CD2 TYR B  22      48.289  10.025  33.672  1.00  7.72           C  
ATOM   2704  CE1 TYR B  22      47.118   9.050  31.363  1.00  6.65           C  
ATOM   2705  CE2 TYR B  22      47.781  10.880  32.723  1.00  6.88           C  
ATOM   2706  CZ  TYR B  22      47.204  10.388  31.588  1.00  6.23           C  
ATOM   2707  OH  TYR B  22      46.688  11.275  30.681  1.00  6.35           O  
ATOM   2708  N   GLY B  23      48.830   5.122  36.426  1.00 12.74           N  
ATOM   2709  CA  GLY B  23      49.411   4.411  37.554  1.00 13.12           C  
ATOM   2710  C   GLY B  23      49.878   3.019  37.220  1.00 14.14           C  
ATOM   2711  O   GLY B  23      49.751   2.591  36.059  1.00 15.78           O  
ATOM   2712  N   PHE B  24      50.400   2.331  38.238  1.00 14.11           N  
ATOM   2713  CA  PHE B  24      51.010   1.020  38.083  1.00 14.61           C  
ATOM   2714  C   PHE B  24      50.303  -0.015  38.932  1.00 17.06           C  
ATOM   2715  O   PHE B  24      49.985   0.303  40.070  1.00 16.71           O  
ATOM   2716  CB  PHE B  24      52.432   1.008  38.556  1.00 11.54           C  
ATOM   2717  CG  PHE B  24      53.285   2.078  37.964  1.00 10.10           C  
ATOM   2718  CD1 PHE B  24      53.314   3.303  38.559  1.00  9.18           C  
ATOM   2719  CD2 PHE B  24      54.052   1.795  36.851  1.00  9.81           C  
ATOM   2720  CE1 PHE B  24      54.144   4.263  38.032  1.00  9.39           C  
ATOM   2721  CE2 PHE B  24      54.873   2.753  36.329  1.00  9.01           C  
ATOM   2722  CZ  PHE B  24      54.918   3.993  36.925  1.00  9.65           C  
ATOM   2723  N   ARG B  25      50.119  -1.266  38.522  1.00 20.58           N  
ATOM   2724  CA  ARG B  25      49.512  -2.313  39.330  1.00 21.63           C  
ATOM   2725  C   ARG B  25      50.441  -3.490  39.080  1.00 24.04           C  
ATOM   2726  O   ARG B  25      50.684  -3.873  37.939  1.00 25.42           O  
ATOM   2727  CB  ARG B  25      48.120  -2.386  38.767  1.00 20.53           C  
ATOM   2728  CG  ARG B  25      47.192  -3.456  39.177  1.00 21.57           C  
ATOM   2729  CD  ARG B  25      45.902  -3.261  38.401  1.00 22.14           C  
ATOM   2730  NE  ARG B  25      44.960  -2.345  39.027  1.00 22.85           N  
ATOM   2731  CZ  ARG B  25      43.626  -2.476  38.835  1.00 24.14           C  
ATOM   2732  NH1 ARG B  25      42.787  -1.629  39.461  1.00 24.38           N  
ATOM   2733  NH2 ARG B  25      43.109  -3.434  38.021  1.00 23.96           N  
ATOM   2734  N   HIS B  26      51.082  -4.007  40.112  1.00 27.70           N  
ATOM   2735  CA  HIS B  26      52.152  -5.000  40.016  1.00 31.24           C  
ATOM   2736  C   HIS B  26      51.775  -6.331  40.615  1.00 32.77           C  
ATOM   2737  O   HIS B  26      50.976  -6.394  41.545  1.00 32.70           O  
ATOM   2738  CB  HIS B  26      53.400  -4.521  40.771  1.00 33.31           C  
ATOM   2739  CG  HIS B  26      53.264  -4.493  42.314  1.00 35.17           C  
ATOM   2740  ND1 HIS B  26      52.572  -3.618  43.043  1.00 35.54           N  
ATOM   2741  CD2 HIS B  26      53.836  -5.397  43.186  1.00 36.14           C  
ATOM   2742  CE1 HIS B  26      52.697  -3.940  44.305  1.00 35.86           C  
ATOM   2743  NE2 HIS B  26      53.458  -5.007  44.377  1.00 36.86           N  
ATOM   2744  N   GLN B  27      52.400  -7.410  40.202  1.00 35.85           N  
ATOM   2745  CA  GLN B  27      52.239  -8.675  40.883  1.00 39.40           C  
ATOM   2746  C   GLN B  27      53.659  -9.147  41.102  1.00 39.91           C  
ATOM   2747  O   GLN B  27      54.479  -9.027  40.193  1.00 40.19           O  
ATOM   2748  CB  GLN B  27      51.469  -9.650  40.020  1.00 41.67           C  
ATOM   2749  CG  GLN B  27      51.017 -10.858  40.838  1.00 45.71           C  
ATOM   2750  CD  GLN B  27      49.845 -11.659  40.253  1.00 47.97           C  
ATOM   2751  OE1 GLN B  27      49.378 -11.370  39.155  1.00 49.80           O  
ATOM   2752  NE2 GLN B  27      49.301 -12.701  40.889  1.00 48.34           N  
ATOM   2753  N   ASN B  28      54.005  -9.595  42.304  1.00 41.77           N  
ATOM   2754  CA  ASN B  28      55.383  -9.986  42.601  1.00 43.26           C  
ATOM   2755  C   ASN B  28      55.434 -10.972  43.754  1.00 44.92           C  
ATOM   2756  O   ASN B  28      54.381 -11.423  44.227  1.00 45.00           O  
ATOM   2757  CB  ASN B  28      56.249  -8.767  42.965  1.00 42.18           C  
ATOM   2758  CG  ASN B  28      56.053  -8.103  44.316  1.00 41.20           C  
ATOM   2759  OD1 ASN B  28      57.009  -7.514  44.798  1.00 41.17           O  
ATOM   2760  ND2 ASN B  28      54.923  -8.133  45.024  1.00 39.93           N  
ATOM   2761  N   SER B  29      56.651 -11.326  44.188  1.00 46.61           N  
ATOM   2762  CA  SER B  29      56.827 -12.261  45.299  1.00 48.10           C  
ATOM   2763  C   SER B  29      56.048 -11.862  46.552  1.00 48.82           C  
ATOM   2764  O   SER B  29      55.245 -12.631  47.085  1.00 49.14           O  
ATOM   2765  CB  SER B  29      58.351 -12.400  45.632  1.00 48.20           C  
ATOM   2766  OG  SER B  29      59.232 -11.263  45.475  1.00 48.05           O  
ATOM   2767  N   GLU B  30      56.173 -10.601  46.944  1.00 49.03           N  
ATOM   2768  CA  GLU B  30      55.593 -10.136  48.174  1.00 49.86           C  
ATOM   2769  C   GLU B  30      54.120  -9.700  48.024  1.00 49.91           C  
ATOM   2770  O   GLU B  30      53.677  -8.684  48.581  1.00 50.51           O  
ATOM   2771  CB  GLU B  30      56.612  -9.093  48.525  1.00 50.93           C  
ATOM   2772  CG  GLU B  30      56.750  -8.660  49.948  1.00 53.66           C  
ATOM   2773  CD  GLU B  30      58.054  -7.897  50.132  1.00 55.69           C  
ATOM   2774  OE1 GLU B  30      58.260  -6.862  49.502  1.00 56.18           O  
ATOM   2775  OE2 GLU B  30      58.882  -8.354  50.907  1.00 57.68           O  
ATOM   2776  N   GLY B  31      53.307 -10.449  47.251  1.00 49.23           N  
ATOM   2777  CA  GLY B  31      51.897 -10.121  46.991  1.00 47.47           C  
ATOM   2778  C   GLY B  31      51.626  -9.389  45.670  1.00 46.32           C  
ATOM   2779  O   GLY B  31      52.316  -9.563  44.655  1.00 46.18           O  
ATOM   2780  N   THR B  32      50.624  -8.510  45.662  1.00 45.12           N  
ATOM   2781  CA  THR B  32      50.234  -7.748  44.486  1.00 43.27           C  
ATOM   2782  C   THR B  32      49.759  -6.348  44.910  1.00 40.92           C  
ATOM   2783  O   THR B  32      49.879  -5.985  46.086  1.00 41.75           O  
ATOM   2784  CB  THR B  32      49.140  -8.548  43.771  1.00 43.91           C  
ATOM   2785  OG1 THR B  32      48.925  -7.892  42.527  1.00 45.74           O  
ATOM   2786  CG2 THR B  32      47.851  -8.625  44.555  1.00 44.09           C  
ATOM   2787  N   GLY B  33      49.299  -5.488  44.004  1.00 37.50           N  
ATOM   2788  CA  GLY B  33      48.858  -4.167  44.407  1.00 33.61           C  
ATOM   2789  C   GLY B  33      49.128  -3.090  43.380  1.00 30.86           C  
ATOM   2790  O   GLY B  33      49.981  -3.203  42.509  1.00 31.10           O  
ATOM   2791  N   GLN B  34      48.565  -1.917  43.548  1.00 28.14           N  
ATOM   2792  CA  GLN B  34      48.659  -0.847  42.572  1.00 27.06           C  
ATOM   2793  C   GLN B  34      49.078   0.461  43.221  1.00 25.19           C  
ATOM   2794  O   GLN B  34      49.087   0.530  44.440  1.00 24.75           O  
ATOM   2795  CB  GLN B  34      47.324  -0.637  41.897  1.00 27.82           C  
ATOM   2796  CG  GLN B  34      46.242   0.032  42.683  1.00 28.48           C  
ATOM   2797  CD  GLN B  34      45.047   0.389  41.796  1.00 29.79           C  
ATOM   2798  OE1 GLN B  34      44.553  -0.367  40.928  1.00 28.92           O  
ATOM   2799  NE2 GLN B  34      44.569   1.609  42.019  1.00 29.54           N  
ATOM   2800  N   ALA B  35      49.404   1.498  42.467  1.00 24.47           N  
ATOM   2801  CA  ALA B  35      49.872   2.763  43.021  1.00 22.77           C  
ATOM   2802  C   ALA B  35      49.715   3.802  41.931  1.00 21.37           C  
ATOM   2803  O   ALA B  35      50.087   3.471  40.794  1.00 22.48           O  
ATOM   2804  CB  ALA B  35      51.342   2.645  43.376  1.00 22.97           C  
ATOM   2805  N   ALA B  36      49.138   4.973  42.180  1.00 19.67           N  
ATOM   2806  CA  ALA B  36      49.005   5.970  41.128  1.00 20.10           C  
ATOM   2807  C   ALA B  36      50.330   6.615  40.831  1.00 20.68           C  
ATOM   2808  O   ALA B  36      51.201   6.596  41.695  1.00 21.08           O  
ATOM   2809  CB  ALA B  36      48.116   7.109  41.492  1.00 19.40           C  
ATOM   2810  N   ASP B  37      50.520   7.120  39.611  1.00 21.66           N  
ATOM   2811  CA  ASP B  37      51.734   7.816  39.238  1.00 22.27           C  
ATOM   2812  C   ASP B  37      51.383   9.275  39.365  1.00 22.74           C  
ATOM   2813  O   ASP B  37      50.458   9.764  38.696  1.00 22.17           O  
ATOM   2814  CB  ASP B  37      52.136   7.568  37.803  1.00 23.08           C  
ATOM   2815  CG  ASP B  37      53.407   8.346  37.464  1.00 24.78           C  
ATOM   2816  OD1 ASP B  37      54.469   7.759  37.409  1.00 26.96           O  
ATOM   2817  OD2 ASP B  37      53.388   9.559  37.252  1.00 24.92           O  
ATOM   2818  N   LEU B  38      52.098  10.036  40.184  1.00 23.63           N  
ATOM   2819  CA  LEU B  38      51.698  11.427  40.315  1.00 24.88           C  
ATOM   2820  C   LEU B  38      52.289  12.389  39.312  1.00 24.26           C  
ATOM   2821  O   LEU B  38      51.602  13.354  38.987  1.00 24.02           O  
ATOM   2822  CB  LEU B  38      51.991  11.927  41.721  1.00 26.73           C  
ATOM   2823  CG  LEU B  38      51.081  11.258  42.771  1.00 28.16           C  
ATOM   2824  CD1 LEU B  38      51.400  11.881  44.110  1.00 28.37           C  
ATOM   2825  CD2 LEU B  38      49.584  11.434  42.443  1.00 28.48           C  
ATOM   2826  N   LYS B  39      53.468  12.150  38.733  1.00 23.70           N  
ATOM   2827  CA  LYS B  39      54.013  13.110  37.790  1.00 23.50           C  
ATOM   2828  C   LYS B  39      53.211  13.152  36.504  1.00 21.41           C  
ATOM   2829  O   LYS B  39      52.879  14.248  36.056  1.00 21.59           O  
ATOM   2830  CB  LYS B  39      55.424  12.794  37.403  1.00 27.54           C  
ATOM   2831  CG  LYS B  39      56.447  13.424  38.305  1.00 31.59           C  
ATOM   2832  CD  LYS B  39      57.775  13.306  37.579  1.00 35.96           C  
ATOM   2833  CE  LYS B  39      58.766  14.285  38.238  1.00 39.69           C  
ATOM   2834  NZ  LYS B  39      60.027  14.414  37.491  1.00 41.76           N  
ATOM   2835  N   SER B  40      52.853  12.022  35.895  1.00 18.02           N  
ATOM   2836  CA  SER B  40      52.043  12.057  34.717  1.00 15.83           C  
ATOM   2837  C   SER B  40      50.657  12.523  35.044  1.00 14.10           C  
ATOM   2838  O   SER B  40      50.080  13.260  34.250  1.00 12.90           O  
ATOM   2839  CB  SER B  40      51.982  10.701  34.083  1.00 17.29           C  
ATOM   2840  OG  SER B  40      51.654   9.680  35.000  1.00 18.49           O  
ATOM   2841  N   THR B  41      50.106  12.169  36.206  1.00 13.74           N  
ATOM   2842  CA  THR B  41      48.811  12.730  36.554  1.00 14.13           C  
ATOM   2843  C   THR B  41      48.865  14.251  36.608  1.00 15.99           C  
ATOM   2844  O   THR B  41      47.984  14.900  36.036  1.00 16.19           O  
ATOM   2845  CB  THR B  41      48.344  12.216  37.868  1.00 12.48           C  
ATOM   2846  OG1 THR B  41      48.160  10.821  37.702  1.00 14.03           O  
ATOM   2847  CG2 THR B  41      47.018  12.776  38.261  1.00 11.18           C  
ATOM   2848  N   GLN B  42      49.922  14.844  37.185  1.00 17.28           N  
ATOM   2849  CA  GLN B  42      50.024  16.282  37.202  1.00 18.45           C  
ATOM   2850  C   GLN B  42      50.224  16.854  35.827  1.00 17.76           C  
ATOM   2851  O   GLN B  42      49.495  17.774  35.495  1.00 18.50           O  
ATOM   2852  CB  GLN B  42      51.164  16.776  38.052  1.00 21.44           C  
ATOM   2853  CG  GLN B  42      50.658  17.111  39.444  1.00 25.51           C  
ATOM   2854  CD  GLN B  42      49.518  18.145  39.484  1.00 28.23           C  
ATOM   2855  OE1 GLN B  42      48.573  18.018  40.289  1.00 29.09           O  
ATOM   2856  NE2 GLN B  42      49.563  19.196  38.660  1.00 28.30           N  
ATOM   2857  N   ALA B  43      51.096  16.294  34.990  1.00 16.27           N  
ATOM   2858  CA  ALA B  43      51.291  16.791  33.635  1.00 14.93           C  
ATOM   2859  C   ALA B  43      49.986  16.862  32.879  1.00 14.66           C  
ATOM   2860  O   ALA B  43      49.675  17.892  32.283  1.00 14.83           O  
ATOM   2861  CB  ALA B  43      52.179  15.886  32.839  1.00 15.98           C  
ATOM   2862  N   ALA B  44      49.177  15.793  32.932  1.00 13.91           N  
ATOM   2863  CA  ALA B  44      47.890  15.801  32.278  1.00 12.32           C  
ATOM   2864  C   ALA B  44      47.005  16.857  32.904  1.00 11.97           C  
ATOM   2865  O   ALA B  44      46.489  17.704  32.156  1.00 12.10           O  
ATOM   2866  CB  ALA B  44      47.210  14.462  32.412  1.00 11.76           C  
ATOM   2867  N   ILE B  45      46.895  16.897  34.248  1.00 11.45           N  
ATOM   2868  CA  ILE B  45      46.009  17.876  34.913  1.00 11.18           C  
ATOM   2869  C   ILE B  45      46.374  19.352  34.681  1.00 12.20           C  
ATOM   2870  O   ILE B  45      45.485  20.145  34.336  1.00 11.60           O  
ATOM   2871  CB  ILE B  45      45.957  17.555  36.407  1.00  8.29           C  
ATOM   2872  CG1 ILE B  45      45.060  16.382  36.513  1.00  7.04           C  
ATOM   2873  CG2 ILE B  45      45.410  18.661  37.251  1.00  7.41           C  
ATOM   2874  CD1 ILE B  45      44.897  15.823  37.892  1.00  8.05           C  
ATOM   2875  N   ASP B  46      47.650  19.717  34.771  1.00 12.77           N  
ATOM   2876  CA  ASP B  46      48.082  21.068  34.501  1.00 13.93           C  
ATOM   2877  C   ASP B  46      47.725  21.525  33.100  1.00 13.68           C  
ATOM   2878  O   ASP B  46      47.118  22.593  32.926  1.00 13.22           O  
ATOM   2879  CB  ASP B  46      49.576  21.197  34.673  1.00 15.58           C  
ATOM   2880  CG  ASP B  46      50.059  21.160  36.113  1.00 18.77           C  
ATOM   2881  OD1 ASP B  46      49.303  21.492  37.040  1.00 20.71           O  
ATOM   2882  OD2 ASP B  46      51.215  20.768  36.326  1.00 19.62           O  
ATOM   2883  N   GLN B  47      48.029  20.722  32.066  1.00 12.95           N  
ATOM   2884  CA  GLN B  47      47.720  21.085  30.687  1.00 11.66           C  
ATOM   2885  C   GLN B  47      46.246  21.350  30.508  1.00 11.57           C  
ATOM   2886  O   GLN B  47      45.882  22.347  29.892  1.00  9.74           O  
ATOM   2887  CB  GLN B  47      48.081  19.993  29.754  1.00 12.64           C  
ATOM   2888  CG  GLN B  47      49.548  19.881  29.765  1.00 14.91           C  
ATOM   2889  CD  GLN B  47      50.023  18.749  28.883  1.00 16.57           C  
ATOM   2890  OE1 GLN B  47      49.986  18.878  27.656  1.00 16.99           O  
ATOM   2891  NE2 GLN B  47      50.486  17.641  29.472  1.00 17.79           N  
ATOM   2892  N   ILE B  48      45.379  20.472  31.054  1.00 12.11           N  
ATOM   2893  CA  ILE B  48      43.950  20.669  30.939  1.00 11.58           C  
ATOM   2894  C   ILE B  48      43.530  21.930  31.689  1.00 13.47           C  
ATOM   2895  O   ILE B  48      42.695  22.686  31.187  1.00 13.30           O  
ATOM   2896  CB  ILE B  48      43.254  19.427  31.463  1.00 10.73           C  
ATOM   2897  CG1 ILE B  48      43.533  18.310  30.509  1.00 10.29           C  
ATOM   2898  CG2 ILE B  48      41.751  19.611  31.523  1.00 11.11           C  
ATOM   2899  CD1 ILE B  48      42.869  16.980  30.872  1.00 11.13           C  
ATOM   2900  N   ASN B  49      44.131  22.262  32.845  1.00 15.68           N  
ATOM   2901  CA  ASN B  49      43.766  23.492  33.545  1.00 15.83           C  
ATOM   2902  C   ASN B  49      44.211  24.676  32.755  1.00 14.04           C  
ATOM   2903  O   ASN B  49      43.538  25.695  32.749  1.00 14.12           O  
ATOM   2904  CB  ASN B  49      44.411  23.644  34.902  1.00 18.51           C  
ATOM   2905  CG  ASN B  49      43.819  22.713  35.946  1.00 21.75           C  
ATOM   2906  OD1 ASN B  49      44.547  22.198  36.806  1.00 24.18           O  
ATOM   2907  ND2 ASN B  49      42.510  22.434  35.960  1.00 22.18           N  
ATOM   2908  N   GLY B  50      45.322  24.530  32.069  1.00 12.34           N  
ATOM   2909  CA  GLY B  50      45.871  25.590  31.289  1.00 11.66           C  
ATOM   2910  C   GLY B  50      44.921  25.953  30.188  1.00 11.86           C  
ATOM   2911  O   GLY B  50      44.573  27.132  30.082  1.00 12.51           O  
ATOM   2912  N   LYS B  51      44.418  24.966  29.426  1.00 11.85           N  
ATOM   2913  CA  LYS B  51      43.501  25.328  28.355  1.00 11.11           C  
ATOM   2914  C   LYS B  51      42.238  25.833  28.971  1.00 10.83           C  
ATOM   2915  O   LYS B  51      41.745  26.867  28.541  1.00 11.05           O  
ATOM   2916  CB  LYS B  51      43.100  24.187  27.388  1.00 10.50           C  
ATOM   2917  CG  LYS B  51      43.019  22.787  27.902  1.00  8.97           C  
ATOM   2918  CD  LYS B  51      42.104  21.853  27.147  1.00  7.49           C  
ATOM   2919  CE  LYS B  51      42.341  21.532  25.697  1.00  5.88           C  
ATOM   2920  NZ  LYS B  51      43.639  21.069  25.350  1.00  5.05           N  
ATOM   2921  N   LEU B  52      41.801  25.238  30.066  1.00 11.23           N  
ATOM   2922  CA  LEU B  52      40.580  25.687  30.697  1.00 13.68           C  
ATOM   2923  C   LEU B  52      40.616  27.142  31.110  1.00 15.03           C  
ATOM   2924  O   LEU B  52      39.664  27.866  30.830  1.00 15.69           O  
ATOM   2925  CB  LEU B  52      40.285  24.840  31.911  1.00 13.53           C  
ATOM   2926  CG  LEU B  52      38.976  25.015  32.644  1.00 13.87           C  
ATOM   2927  CD1 LEU B  52      37.760  25.140  31.764  1.00 13.41           C  
ATOM   2928  CD2 LEU B  52      38.829  23.753  33.439  1.00 15.06           C  
ATOM   2929  N   ASN B  53      41.710  27.627  31.672  1.00 17.12           N  
ATOM   2930  CA  ASN B  53      41.762  29.009  32.120  1.00 18.81           C  
ATOM   2931  C   ASN B  53      41.770  29.959  30.958  1.00 17.82           C  
ATOM   2932  O   ASN B  53      41.153  31.011  30.992  1.00 18.14           O  
ATOM   2933  CB  ASN B  53      42.999  29.326  32.920  1.00 22.19           C  
ATOM   2934  CG  ASN B  53      43.111  28.563  34.235  1.00 25.73           C  
ATOM   2935  OD1 ASN B  53      42.130  28.185  34.891  1.00 27.22           O  
ATOM   2936  ND2 ASN B  53      44.344  28.286  34.686  1.00 27.41           N  
ATOM   2937  N   ARG B  54      42.422  29.583  29.884  1.00 16.78           N  
ATOM   2938  CA  ARG B  54      42.525  30.435  28.725  1.00 15.67           C  
ATOM   2939  C   ARG B  54      41.154  30.622  28.115  1.00 15.75           C  
ATOM   2940  O   ARG B  54      40.837  31.689  27.655  1.00 12.80           O  
ATOM   2941  CB  ARG B  54      43.520  29.729  27.841  1.00 15.31           C  
ATOM   2942  CG  ARG B  54      44.107  30.504  26.704  1.00 15.17           C  
ATOM   2943  CD  ARG B  54      45.579  30.822  26.878  1.00 15.82           C  
ATOM   2944  NE  ARG B  54      46.138  31.197  25.581  1.00 17.25           N  
ATOM   2945  CZ  ARG B  54      45.839  32.373  24.975  1.00 18.20           C  
ATOM   2946  NH1 ARG B  54      46.306  32.592  23.741  1.00 18.70           N  
ATOM   2947  NH2 ARG B  54      45.149  33.353  25.598  1.00 18.12           N  
ATOM   2948  N   VAL B  55      40.296  29.600  28.131  1.00 19.26           N  
ATOM   2949  CA  VAL B  55      38.921  29.654  27.629  1.00 22.13           C  
ATOM   2950  C   VAL B  55      38.074  30.519  28.532  1.00 26.09           C  
ATOM   2951  O   VAL B  55      37.197  31.233  28.080  1.00 26.56           O  
ATOM   2952  CB  VAL B  55      38.308  28.248  27.594  1.00 21.45           C  
ATOM   2953  CG1 VAL B  55      36.854  28.247  27.207  1.00 21.99           C  
ATOM   2954  CG2 VAL B  55      38.991  27.469  26.531  1.00 21.32           C  
ATOM   2955  N   ILE B  56      38.292  30.410  29.826  1.00 31.30           N  
ATOM   2956  CA  ILE B  56      37.565  31.154  30.819  1.00 36.55           C  
ATOM   2957  C   ILE B  56      38.172  32.547  31.039  1.00 42.39           C  
ATOM   2958  O   ILE B  56      37.775  33.229  31.992  1.00 44.06           O  
ATOM   2959  CB  ILE B  56      37.581  30.159  32.016  1.00 36.03           C  
ATOM   2960  CG1 ILE B  56      36.162  29.800  32.218  1.00 36.47           C  
ATOM   2961  CG2 ILE B  56      38.175  30.640  33.307  1.00 36.49           C  
ATOM   2962  CD1 ILE B  56      35.820  28.587  31.342  1.00 36.48           C  
ATOM   2963  N   GLU B  57      39.127  33.016  30.186  1.00 48.43           N  
ATOM   2964  CA  GLU B  57      39.778  34.336  30.300  1.00 53.49           C  
ATOM   2965  C   GLU B  57      38.806  35.515  30.162  1.00 56.20           C  
ATOM   2966  O   GLU B  57      37.577  35.389  30.209  1.00 57.66           O  
ATOM   2967  CB  GLU B  57      40.899  34.500  29.234  1.00 55.38           C  
ATOM   2968  CG  GLU B  57      42.397  34.346  29.640  1.00 57.56           C  
ATOM   2969  CD  GLU B  57      43.413  34.107  28.495  1.00 58.77           C  
ATOM   2970  OE1 GLU B  57      43.139  34.418  27.330  1.00 59.38           O  
ATOM   2971  OE2 GLU B  57      44.519  33.598  28.726  1.00 59.48           O  
ATOM   2972  N   LYS B  58      39.309  36.727  29.926  1.00 58.68           N  
ATOM   2973  CA  LYS B  58      38.477  37.927  30.045  1.00 59.96           C  
ATOM   2974  C   LYS B  58      37.193  38.014  29.216  1.00 58.12           C  
ATOM   2975  O   LYS B  58      37.189  37.833  27.992  1.00 57.94           O  
ATOM   2976  CB  LYS B  58      39.367  39.175  29.759  1.00 62.44           C  
ATOM   2977  CG  LYS B  58      38.744  40.532  30.134  1.00 65.19           C  
ATOM   2978  CD  LYS B  58      38.303  40.566  31.616  1.00 67.31           C  
ATOM   2979  CE  LYS B  58      37.442  41.802  31.959  1.00 69.20           C  
ATOM   2980  NZ  LYS B  58      38.230  43.033  32.041  1.00 70.80           N  
ATOM   2981  N   THR B  59      36.093  38.248  29.941  1.00 56.27           N  
ATOM   2982  CA  THR B  59      34.834  38.600  29.311  1.00 54.54           C  
ATOM   2983  C   THR B  59      34.978  40.035  28.832  1.00 52.08           C  
ATOM   2984  O   THR B  59      35.483  40.904  29.566  1.00 52.31           O  
ATOM   2985  CB  THR B  59      33.593  38.538  30.291  1.00 55.05           C  
ATOM   2986  OG1 THR B  59      33.947  39.305  31.444  1.00 55.73           O  
ATOM   2987  CG2 THR B  59      33.166  37.109  30.646  1.00 54.73           C  
ATOM   2988  N   ASN B  60      34.538  40.295  27.619  1.00 49.16           N  
ATOM   2989  CA  ASN B  60      34.522  41.653  27.127  1.00 46.27           C  
ATOM   2990  C   ASN B  60      33.230  42.255  27.688  1.00 41.39           C  
ATOM   2991  O   ASN B  60      32.230  41.545  27.848  1.00 40.98           O  
ATOM   2992  CB  ASN B  60      34.540  41.662  25.563  1.00 49.97           C  
ATOM   2993  CG  ASN B  60      33.553  40.745  24.787  1.00 52.79           C  
ATOM   2994  OD1 ASN B  60      33.011  39.744  25.300  1.00 53.46           O  
ATOM   2995  ND2 ASN B  60      33.366  40.919  23.469  1.00 53.51           N  
ATOM   2996  N   GLU B  61      33.251  43.512  28.115  1.00 35.30           N  
ATOM   2997  CA  GLU B  61      32.029  44.123  28.576  1.00 30.90           C  
ATOM   2998  C   GLU B  61      31.527  45.131  27.584  1.00 25.99           C  
ATOM   2999  O   GLU B  61      32.301  45.773  26.883  1.00 26.50           O  
ATOM   3000  CB  GLU B  61      32.219  44.811  29.903  1.00 32.97           C  
ATOM   3001  CG  GLU B  61      33.272  45.870  30.196  1.00 34.06           C  
ATOM   3002  CD  GLU B  61      33.301  46.301  31.664  1.00 35.56           C  
ATOM   3003  OE1 GLU B  61      32.474  45.847  32.468  1.00 37.41           O  
ATOM   3004  OE2 GLU B  61      34.163  47.102  32.019  1.00 36.36           O  
ATOM   3005  N   LYS B  62      30.238  45.207  27.394  1.00 20.26           N  
ATOM   3006  CA  LYS B  62      29.697  46.155  26.466  1.00 16.55           C  
ATOM   3007  C   LYS B  62      28.584  46.864  27.206  1.00 15.46           C  
ATOM   3008  O   LYS B  62      27.939  46.291  28.101  1.00 16.30           O  
ATOM   3009  CB  LYS B  62      29.141  45.447  25.234  1.00 15.16           C  
ATOM   3010  CG  LYS B  62      30.138  44.602  24.439  1.00 13.88           C  
ATOM   3011  CD  LYS B  62      31.063  45.381  23.536  1.00 13.78           C  
ATOM   3012  CE  LYS B  62      32.276  44.548  23.186  1.00 13.44           C  
ATOM   3013  NZ  LYS B  62      33.098  45.181  22.164  1.00 14.58           N  
ATOM   3014  N   PHE B  63      28.396  48.141  26.902  1.00 12.31           N  
ATOM   3015  CA  PHE B  63      27.371  48.898  27.556  1.00 10.45           C  
ATOM   3016  C   PHE B  63      26.291  49.268  26.566  1.00  8.69           C  
ATOM   3017  O   PHE B  63      25.615  48.372  26.092  1.00  9.34           O  
ATOM   3018  CB  PHE B  63      28.064  50.078  28.193  1.00 10.20           C  
ATOM   3019  CG  PHE B  63      29.044  49.630  29.258  1.00 10.05           C  
ATOM   3020  CD1 PHE B  63      28.587  49.059  30.426  1.00 10.72           C  
ATOM   3021  CD2 PHE B  63      30.388  49.783  29.041  1.00  9.84           C  
ATOM   3022  CE1 PHE B  63      29.485  48.632  31.382  1.00 11.38           C  
ATOM   3023  CE2 PHE B  63      31.277  49.356  30.002  1.00 10.60           C  
ATOM   3024  CZ  PHE B  63      30.839  48.780  31.171  1.00 10.82           C  
ATOM   3025  N   HIS B  64      26.093  50.511  26.156  1.00  7.88           N  
ATOM   3026  CA  HIS B  64      25.001  50.879  25.235  1.00  7.63           C  
ATOM   3027  C   HIS B  64      25.254  50.283  23.886  1.00  7.08           C  
ATOM   3028  O   HIS B  64      26.336  50.521  23.392  1.00  7.94           O  
ATOM   3029  CB  HIS B  64      24.919  52.381  25.091  1.00  6.63           C  
ATOM   3030  CG  HIS B  64      23.665  52.914  24.464  1.00  5.68           C  
ATOM   3031  ND1 HIS B  64      22.428  52.624  24.790  1.00  6.04           N  
ATOM   3032  CD2 HIS B  64      23.621  53.859  23.486  1.00  6.92           C  
ATOM   3033  CE1 HIS B  64      21.636  53.373  24.046  1.00  6.82           C  
ATOM   3034  NE2 HIS B  64      22.362  54.111  23.264  1.00  7.21           N  
ATOM   3035  N   GLN B  65      24.358  49.465  23.332  1.00  7.49           N  
ATOM   3036  CA  GLN B  65      24.564  48.862  22.008  1.00  6.28           C  
ATOM   3037  C   GLN B  65      23.406  49.210  21.081  1.00  5.67           C  
ATOM   3038  O   GLN B  65      22.911  50.313  21.124  1.00  7.83           O  
ATOM   3039  CB  GLN B  65      24.664  47.381  22.177  1.00  5.43           C  
ATOM   3040  CG  GLN B  65      25.875  46.957  22.921  1.00  5.73           C  
ATOM   3041  CD  GLN B  65      25.629  45.631  23.604  1.00  6.95           C  
ATOM   3042  OE1 GLN B  65      25.549  44.533  22.983  1.00  7.28           O  
ATOM   3043  NE2 GLN B  65      25.476  45.785  24.919  1.00  6.35           N  
ATOM   3044  N   ILE B  66      22.905  48.359  20.225  1.00  4.79           N  
ATOM   3045  CA  ILE B  66      21.722  48.657  19.442  1.00  4.72           C  
ATOM   3046  C   ILE B  66      20.542  47.949  20.072  1.00  6.08           C  
ATOM   3047  O   ILE B  66      20.758  47.002  20.847  1.00  7.18           O  
ATOM   3048  CB  ILE B  66      21.905  48.143  18.030  1.00  3.71           C  
ATOM   3049  CG1 ILE B  66      22.236  46.688  17.980  1.00  2.00           C  
ATOM   3050  CG2 ILE B  66      23.028  48.932  17.410  1.00  4.66           C  
ATOM   3051  CD1 ILE B  66      22.196  46.232  16.547  1.00  2.00           C  
ATOM   3052  N   GLU B  67      19.314  48.329  19.717  1.00  7.57           N  
ATOM   3053  CA  GLU B  67      18.127  47.661  20.246  1.00  9.19           C  
ATOM   3054  C   GLU B  67      17.964  46.315  19.614  1.00  9.47           C  
ATOM   3055  O   GLU B  67      18.367  46.101  18.487  1.00 11.20           O  
ATOM   3056  CB  GLU B  67      16.881  48.408  19.961  1.00 10.02           C  
ATOM   3057  CG  GLU B  67      16.773  49.662  20.797  1.00 11.82           C  
ATOM   3058  CD  GLU B  67      16.623  49.473  22.280  1.00 13.33           C  
ATOM   3059  OE1 GLU B  67      15.991  48.496  22.701  1.00 15.70           O  
ATOM   3060  OE2 GLU B  67      17.070  50.359  23.012  1.00 14.31           O  
ATOM   3061  N   LYS B  68      17.404  45.341  20.289  1.00  9.44           N  
ATOM   3062  CA  LYS B  68      17.367  44.023  19.698  1.00  9.26           C  
ATOM   3063  C   LYS B  68      15.985  43.416  19.739  1.00 11.98           C  
ATOM   3064  O   LYS B  68      15.839  42.215  19.468  1.00 12.58           O  
ATOM   3065  CB  LYS B  68      18.337  43.111  20.417  1.00  6.73           C  
ATOM   3066  CG  LYS B  68      19.720  43.715  20.486  1.00  5.31           C  
ATOM   3067  CD  LYS B  68      20.765  42.693  20.806  1.00  4.05           C  
ATOM   3068  CE  LYS B  68      22.057  43.410  21.041  1.00  4.34           C  
ATOM   3069  NZ  LYS B  68      23.044  42.411  21.372  1.00  5.29           N  
ATOM   3070  N   GLU B  69      14.988  44.204  20.121  1.00 14.01           N  
ATOM   3071  CA  GLU B  69      13.621  43.772  20.161  1.00 16.30           C  
ATOM   3072  C   GLU B  69      12.818  44.988  19.734  1.00 16.43           C  
ATOM   3073  O   GLU B  69      13.143  46.116  20.135  1.00 16.72           O  
ATOM   3074  CB  GLU B  69      13.314  43.329  21.561  1.00 19.49           C  
ATOM   3075  CG  GLU B  69      13.500  41.818  21.538  1.00 24.41           C  
ATOM   3076  CD  GLU B  69      13.767  41.151  22.884  1.00 27.64           C  
ATOM   3077  OE1 GLU B  69      14.716  40.308  22.937  1.00 28.56           O  
ATOM   3078  OE2 GLU B  69      13.040  41.508  23.830  1.00 28.34           O  
ATOM   3079  N   PHE B  70      11.818  44.820  18.864  1.00 15.78           N  
ATOM   3080  CA  PHE B  70      11.084  45.950  18.318  1.00 15.71           C  
ATOM   3081  C   PHE B  70       9.607  45.725  18.484  1.00 17.70           C  
ATOM   3082  O   PHE B  70       9.153  44.598  18.378  1.00 18.35           O  
ATOM   3083  CB  PHE B  70      11.383  46.105  16.837  1.00 14.25           C  
ATOM   3084  CG  PHE B  70      12.880  46.181  16.560  1.00 12.72           C  
ATOM   3085  CD1 PHE B  70      13.509  47.403  16.559  1.00 11.24           C  
ATOM   3086  CD2 PHE B  70      13.605  45.018  16.429  1.00 12.25           C  
ATOM   3087  CE1 PHE B  70      14.866  47.460  16.438  1.00 10.87           C  
ATOM   3088  CE2 PHE B  70      14.960  45.093  16.312  1.00 11.72           C  
ATOM   3089  CZ  PHE B  70      15.592  46.313  16.325  1.00 11.31           C  
ATOM   3090  N   SER B  71       8.797  46.737  18.712  1.00 20.88           N  
ATOM   3091  CA  SER B  71       7.376  46.481  18.865  1.00 23.01           C  
ATOM   3092  C   SER B  71       6.579  47.173  17.803  1.00 24.69           C  
ATOM   3093  O   SER B  71       5.366  47.317  17.951  1.00 26.70           O  
ATOM   3094  CB  SER B  71       6.952  46.965  20.215  1.00 23.75           C  
ATOM   3095  OG  SER B  71       7.379  48.323  20.314  1.00 25.39           O  
ATOM   3096  N   GLU B  72       7.207  47.661  16.748  1.00 26.64           N  
ATOM   3097  CA  GLU B  72       6.504  48.374  15.714  1.00 27.37           C  
ATOM   3098  C   GLU B  72       7.102  47.919  14.410  1.00 24.92           C  
ATOM   3099  O   GLU B  72       8.218  47.404  14.418  1.00 25.52           O  
ATOM   3100  CB  GLU B  72       6.706  49.852  15.975  1.00 31.93           C  
ATOM   3101  CG  GLU B  72       5.414  50.653  15.755  1.00 38.43           C  
ATOM   3102  CD  GLU B  72       4.785  50.475  14.351  1.00 41.84           C  
ATOM   3103  OE1 GLU B  72       5.150  51.209  13.417  1.00 42.60           O  
ATOM   3104  OE2 GLU B  72       3.955  49.549  14.209  1.00 44.03           O  
ATOM   3105  N   VAL B  73       6.416  47.997  13.294  1.00 22.67           N  
ATOM   3106  CA  VAL B  73       7.001  47.551  12.051  1.00 21.26           C  
ATOM   3107  C   VAL B  73       7.521  48.754  11.321  1.00 20.90           C  
ATOM   3108  O   VAL B  73       6.760  49.651  10.937  1.00 22.64           O  
ATOM   3109  CB  VAL B  73       5.955  46.835  11.237  1.00 21.25           C  
ATOM   3110  CG1 VAL B  73       6.335  46.585   9.787  1.00 21.07           C  
ATOM   3111  CG2 VAL B  73       5.820  45.501  11.902  1.00 22.22           C  
ATOM   3112  N   GLU B  74       8.818  48.718  11.052  1.00 18.76           N  
ATOM   3113  CA  GLU B  74       9.435  49.901  10.498  1.00 17.39           C  
ATOM   3114  C   GLU B  74      10.059  49.720   9.125  1.00 16.62           C  
ATOM   3115  O   GLU B  74      10.239  50.697   8.399  1.00 18.15           O  
ATOM   3116  CB  GLU B  74      10.500  50.396  11.467  1.00 17.08           C  
ATOM   3117  CG  GLU B  74      10.065  50.597  12.904  1.00 16.04           C  
ATOM   3118  CD  GLU B  74      11.198  51.152  13.703  1.00 16.25           C  
ATOM   3119  OE1 GLU B  74      11.419  52.340  13.634  1.00 17.11           O  
ATOM   3120  OE2 GLU B  74      11.926  50.412  14.345  1.00 16.50           O  
ATOM   3121  N   GLY B  75      10.449  48.519   8.699  1.00 14.75           N  
ATOM   3122  CA  GLY B  75      11.066  48.405   7.381  1.00 12.09           C  
ATOM   3123  C   GLY B  75      12.588  48.442   7.385  1.00 10.96           C  
ATOM   3124  O   GLY B  75      13.268  47.935   8.280  1.00 11.33           O  
ATOM   3125  N   ARG B  76      13.156  49.215   6.485  1.00  9.73           N  
ATOM   3126  CA  ARG B  76      14.569  49.135   6.170  1.00  7.18           C  
ATOM   3127  C   ARG B  76      15.557  49.274   7.324  1.00  7.25           C  
ATOM   3128  O   ARG B  76      16.402  48.385   7.487  1.00  7.48           O  
ATOM   3129  CB  ARG B  76      14.849  50.164   5.104  1.00  6.04           C  
ATOM   3130  CG  ARG B  76      16.285  50.162   4.628  1.00  6.40           C  
ATOM   3131  CD  ARG B  76      16.443  51.146   3.487  1.00  5.31           C  
ATOM   3132  NE  ARG B  76      17.731  51.037   2.857  1.00  4.64           N  
ATOM   3133  CZ  ARG B  76      18.036  51.772   1.779  1.00  4.71           C  
ATOM   3134  NH1 ARG B  76      19.219  51.623   1.180  1.00  4.25           N  
ATOM   3135  NH2 ARG B  76      17.195  52.693   1.301  1.00  3.54           N  
ATOM   3136  N   ILE B  77      15.519  50.318   8.162  1.00  6.60           N  
ATOM   3137  CA  ILE B  77      16.533  50.380   9.214  1.00  7.10           C  
ATOM   3138  C   ILE B  77      16.381  49.218  10.212  1.00  7.06           C  
ATOM   3139  O   ILE B  77      17.368  48.595  10.593  1.00  6.82           O  
ATOM   3140  CB  ILE B  77      16.456  51.741   9.947  1.00  8.12           C  
ATOM   3141  CG1 ILE B  77      17.412  51.808  11.117  1.00  7.25           C  
ATOM   3142  CG2 ILE B  77      15.045  51.939  10.484  1.00 10.12           C  
ATOM   3143  CD1 ILE B  77      18.725  52.437  10.652  1.00  7.35           C  
ATOM   3144  N   GLN B  78      15.149  48.807  10.528  1.00  6.32           N  
ATOM   3145  CA  GLN B  78      14.961  47.775  11.501  1.00  6.07           C  
ATOM   3146  C   GLN B  78      15.400  46.469  10.918  1.00  7.30           C  
ATOM   3147  O   GLN B  78      15.951  45.634  11.644  1.00  8.82           O  
ATOM   3148  CB  GLN B  78      13.527  47.694  11.888  1.00  6.24           C  
ATOM   3149  CG  GLN B  78      13.375  46.685  13.002  1.00  7.28           C  
ATOM   3150  CD  GLN B  78      11.952  46.336  13.333  1.00  6.81           C  
ATOM   3151  OE1 GLN B  78      11.612  45.143  13.364  1.00  8.00           O  
ATOM   3152  NE2 GLN B  78      11.129  47.333  13.626  1.00  5.05           N  
ATOM   3153  N   ASP B  79      15.193  46.259   9.618  1.00  7.94           N  
ATOM   3154  CA  ASP B  79      15.665  45.032   8.976  1.00  7.54           C  
ATOM   3155  C   ASP B  79      17.180  44.908   9.114  1.00  6.59           C  
ATOM   3156  O   ASP B  79      17.724  43.834   9.409  1.00  6.56           O  
ATOM   3157  CB  ASP B  79      15.338  45.035   7.511  1.00  8.41           C  
ATOM   3158  CG  ASP B  79      13.905  44.989   7.002  1.00  9.14           C  
ATOM   3159  OD1 ASP B  79      12.961  44.792   7.765  1.00 10.40           O  
ATOM   3160  OD2 ASP B  79      13.737  45.140   5.790  1.00  9.96           O  
ATOM   3161  N   LEU B  80      17.905  46.031   8.954  1.00  6.00           N  
ATOM   3162  CA  LEU B  80      19.365  46.049   9.109  1.00  3.75           C  
ATOM   3163  C   LEU B  80      19.758  45.845  10.562  1.00  3.43           C  
ATOM   3164  O   LEU B  80      20.734  45.154  10.836  1.00  3.54           O  
ATOM   3165  CB  LEU B  80      19.896  47.359   8.614  1.00  2.00           C  
ATOM   3166  CG  LEU B  80      21.369  47.679   8.534  1.00  2.12           C  
ATOM   3167  CD1 LEU B  80      22.139  46.690   7.687  1.00  2.00           C  
ATOM   3168  CD2 LEU B  80      21.471  49.085   7.960  1.00  2.00           C  
ATOM   3169  N   GLU B  81      19.016  46.373  11.527  1.00  3.03           N  
ATOM   3170  CA  GLU B  81      19.341  46.131  12.918  1.00  2.55           C  
ATOM   3171  C   GLU B  81      19.213  44.654  13.227  1.00  2.87           C  
ATOM   3172  O   GLU B  81      20.143  44.081  13.789  1.00  2.84           O  
ATOM   3173  CB  GLU B  81      18.407  46.918  13.808  1.00  2.72           C  
ATOM   3174  CG  GLU B  81      18.793  48.363  13.706  1.00  4.28           C  
ATOM   3175  CD  GLU B  81      17.803  49.339  14.262  1.00  6.10           C  
ATOM   3176  OE1 GLU B  81      16.609  49.094  14.156  1.00  6.93           O  
ATOM   3177  OE2 GLU B  81      18.212  50.385  14.770  1.00  7.92           O  
ATOM   3178  N   LYS B  82      18.154  43.982  12.743  1.00  2.19           N  
ATOM   3179  CA  LYS B  82      17.964  42.579  13.031  1.00  2.64           C  
ATOM   3180  C   LYS B  82      19.037  41.766  12.342  1.00  3.29           C  
ATOM   3181  O   LYS B  82      19.603  40.863  12.943  1.00  4.56           O  
ATOM   3182  CB  LYS B  82      16.591  42.136  12.572  1.00  4.13           C  
ATOM   3183  CG  LYS B  82      15.500  43.044  13.109  1.00  6.13           C  
ATOM   3184  CD  LYS B  82      14.334  42.331  13.752  1.00  8.99           C  
ATOM   3185  CE  LYS B  82      13.305  41.875  12.720  1.00 11.52           C  
ATOM   3186  NZ  LYS B  82      11.977  42.426  13.061  1.00 15.24           N  
ATOM   3187  N   TYR B  83      19.418  42.100  11.109  1.00  3.56           N  
ATOM   3188  CA  TYR B  83      20.471  41.397  10.376  1.00  2.39           C  
ATOM   3189  C   TYR B  83      21.862  41.508  11.011  1.00  3.37           C  
ATOM   3190  O   TYR B  83      22.584  40.506  11.099  1.00  2.22           O  
ATOM   3191  CB  TYR B  83      20.537  41.944   8.993  1.00  2.00           C  
ATOM   3192  CG  TYR B  83      21.318  41.072   8.019  1.00  2.00           C  
ATOM   3193  CD1 TYR B  83      22.507  41.486   7.471  1.00  2.00           C  
ATOM   3194  CD2 TYR B  83      20.775  39.886   7.638  1.00  2.29           C  
ATOM   3195  CE1 TYR B  83      23.157  40.727   6.543  1.00  2.00           C  
ATOM   3196  CE2 TYR B  83      21.405  39.131   6.709  1.00  2.53           C  
ATOM   3197  CZ  TYR B  83      22.586  39.560   6.175  1.00  2.02           C  
ATOM   3198  OH  TYR B  83      23.130  38.735   5.219  1.00  2.00           O  
ATOM   3199  N   VAL B  84      22.295  42.704  11.449  1.00  3.76           N  
ATOM   3200  CA  VAL B  84      23.572  42.846  12.118  1.00  2.76           C  
ATOM   3201  C   VAL B  84      23.626  41.919  13.337  1.00  4.29           C  
ATOM   3202  O   VAL B  84      24.618  41.193  13.523  1.00  5.11           O  
ATOM   3203  CB  VAL B  84      23.741  44.279  12.542  1.00  2.08           C  
ATOM   3204  CG1 VAL B  84      24.840  44.466  13.553  1.00  2.00           C  
ATOM   3205  CG2 VAL B  84      24.034  45.060  11.286  1.00  2.00           C  
ATOM   3206  N   GLU B  85      22.552  41.845  14.121  1.00  3.31           N  
ATOM   3207  CA  GLU B  85      22.658  41.016  15.304  1.00  4.85           C  
ATOM   3208  C   GLU B  85      22.555  39.542  14.967  1.00  6.32           C  
ATOM   3209  O   GLU B  85      23.232  38.687  15.555  1.00  7.84           O  
ATOM   3210  CB  GLU B  85      21.577  41.397  16.325  1.00  3.33           C  
ATOM   3211  CG  GLU B  85      21.656  40.722  17.686  1.00  2.00           C  
ATOM   3212  CD  GLU B  85      22.842  41.097  18.495  1.00  3.54           C  
ATOM   3213  OE1 GLU B  85      23.521  42.067  18.212  1.00  3.62           O  
ATOM   3214  OE2 GLU B  85      23.108  40.463  19.506  1.00  5.66           O  
ATOM   3215  N   ASP B  86      21.753  39.176  13.985  1.00  7.87           N  
ATOM   3216  CA  ASP B  86      21.616  37.766  13.693  1.00  8.34           C  
ATOM   3217  C   ASP B  86      22.909  37.291  13.088  1.00  6.73           C  
ATOM   3218  O   ASP B  86      23.390  36.230  13.486  1.00  5.54           O  
ATOM   3219  CB  ASP B  86      20.460  37.546  12.753  1.00 10.33           C  
ATOM   3220  CG  ASP B  86      20.241  36.096  12.372  1.00 13.35           C  
ATOM   3221  OD1 ASP B  86      20.028  35.221  13.226  1.00 14.75           O  
ATOM   3222  OD2 ASP B  86      20.259  35.833  11.161  1.00 15.78           O  
ATOM   3223  N   THR B  87      23.612  38.122  12.300  1.00  6.63           N  
ATOM   3224  CA  THR B  87      24.846  37.568  11.775  1.00  7.58           C  
ATOM   3225  C   THR B  87      25.930  37.584  12.851  1.00  7.69           C  
ATOM   3226  O   THR B  87      26.831  36.742  12.852  1.00  7.50           O  
ATOM   3227  CB  THR B  87      25.349  38.294  10.446  1.00  8.19           C  
ATOM   3228  OG1 THR B  87      26.064  39.461  10.727  1.00 10.13           O  
ATOM   3229  CG2 THR B  87      24.171  38.623   9.545  1.00  7.33           C  
ATOM   3230  N   LYS B  88      25.865  38.482  13.846  1.00  8.02           N  
ATOM   3231  CA  LYS B  88      26.811  38.404  14.934  1.00  4.89           C  
ATOM   3232  C   LYS B  88      26.614  37.101  15.701  1.00  4.18           C  
ATOM   3233  O   LYS B  88      27.605  36.386  15.928  1.00  5.07           O  
ATOM   3234  CB  LYS B  88      26.594  39.557  15.828  1.00  4.35           C  
ATOM   3235  CG  LYS B  88      27.529  39.475  16.986  1.00  4.61           C  
ATOM   3236  CD  LYS B  88      27.111  40.665  17.739  1.00  6.06           C  
ATOM   3237  CE  LYS B  88      27.472  40.541  19.178  1.00  6.83           C  
ATOM   3238  NZ  LYS B  88      27.026  41.772  19.762  1.00  8.44           N  
ATOM   3239  N   ILE B  89      25.357  36.775  16.049  1.00  2.12           N  
ATOM   3240  CA  ILE B  89      25.071  35.580  16.811  1.00  2.00           C  
ATOM   3241  C   ILE B  89      25.505  34.336  16.094  1.00  2.00           C  
ATOM   3242  O   ILE B  89      26.200  33.516  16.693  1.00  2.00           O  
ATOM   3243  CB  ILE B  89      23.596  35.470  17.109  1.00  2.24           C  
ATOM   3244  CG1 ILE B  89      23.152  36.673  17.915  1.00  3.74           C  
ATOM   3245  CG2 ILE B  89      23.333  34.206  17.894  1.00  2.00           C  
ATOM   3246  CD1 ILE B  89      21.651  36.649  18.247  1.00  4.06           C  
ATOM   3247  N   ASP B  90      25.170  34.166  14.828  1.00  2.00           N  
ATOM   3248  CA  ASP B  90      25.586  32.952  14.149  1.00  4.38           C  
ATOM   3249  C   ASP B  90      27.099  32.810  14.058  1.00  4.51           C  
ATOM   3250  O   ASP B  90      27.650  31.703  14.163  1.00  5.01           O  
ATOM   3251  CB  ASP B  90      25.070  32.903  12.770  1.00  6.10           C  
ATOM   3252  CG  ASP B  90      23.601  32.684  12.498  1.00  8.35           C  
ATOM   3253  OD1 ASP B  90      22.765  32.325  13.338  1.00 10.51           O  
ATOM   3254  OD2 ASP B  90      23.287  32.844  11.325  1.00  9.91           O  
ATOM   3255  N   LEU B  91      27.816  33.929  13.927  1.00  4.38           N  
ATOM   3256  CA  LEU B  91      29.267  33.886  13.921  1.00  3.61           C  
ATOM   3257  C   LEU B  91      29.793  33.494  15.298  1.00  4.20           C  
ATOM   3258  O   LEU B  91      30.648  32.615  15.364  1.00  4.29           O  
ATOM   3259  CB  LEU B  91      29.785  35.240  13.479  1.00  2.95           C  
ATOM   3260  CG  LEU B  91      29.893  35.403  11.956  1.00  2.37           C  
ATOM   3261  CD1 LEU B  91      30.189  36.820  11.552  1.00  2.47           C  
ATOM   3262  CD2 LEU B  91      31.017  34.545  11.478  1.00  2.11           C  
ATOM   3263  N   TRP B  92      29.276  34.018  16.426  1.00  4.17           N  
ATOM   3264  CA  TRP B  92      29.787  33.567  17.708  1.00  3.72           C  
ATOM   3265  C   TRP B  92      29.406  32.137  18.021  1.00  3.82           C  
ATOM   3266  O   TRP B  92      30.181  31.426  18.658  1.00  4.04           O  
ATOM   3267  CB  TRP B  92      29.295  34.470  18.812  1.00  3.68           C  
ATOM   3268  CG  TRP B  92      30.283  35.619  18.895  1.00  4.61           C  
ATOM   3269  CD1 TRP B  92      29.957  36.875  18.441  1.00  3.92           C  
ATOM   3270  CD2 TRP B  92      31.589  35.516  19.336  1.00  4.02           C  
ATOM   3271  NE1 TRP B  92      31.073  37.557  18.586  1.00  4.50           N  
ATOM   3272  CE2 TRP B  92      32.053  36.799  19.113  1.00  3.90           C  
ATOM   3273  CE3 TRP B  92      32.425  34.559  19.864  1.00  4.04           C  
ATOM   3274  CZ2 TRP B  92      33.351  37.134  19.413  1.00  3.07           C  
ATOM   3275  CZ3 TRP B  92      33.732  34.883  20.171  1.00  3.74           C  
ATOM   3276  CH2 TRP B  92      34.182  36.161  19.937  1.00  3.47           C  
ATOM   3277  N   SER B  93      28.278  31.639  17.518  1.00  3.38           N  
ATOM   3278  CA  SER B  93      27.881  30.285  17.825  1.00  2.81           C  
ATOM   3279  C   SER B  93      28.768  29.314  17.091  1.00  2.00           C  
ATOM   3280  O   SER B  93      29.140  28.282  17.639  1.00  2.00           O  
ATOM   3281  CB  SER B  93      26.429  30.117  17.444  1.00  2.44           C  
ATOM   3282  OG  SER B  93      25.618  31.086  18.101  1.00  2.00           O  
ATOM   3283  N   TYR B  94      29.163  29.686  15.872  1.00  2.50           N  
ATOM   3284  CA  TYR B  94      30.067  28.863  15.088  1.00  2.53           C  
ATOM   3285  C   TYR B  94      31.358  28.796  15.853  1.00  3.59           C  
ATOM   3286  O   TYR B  94      31.872  27.713  16.108  1.00  3.21           O  
ATOM   3287  CB  TYR B  94      30.306  29.459  13.717  1.00  2.00           C  
ATOM   3288  CG  TYR B  94      31.386  28.740  12.944  1.00  2.54           C  
ATOM   3289  CD1 TYR B  94      32.658  29.207  13.010  1.00  4.05           C  
ATOM   3290  CD2 TYR B  94      31.163  27.605  12.223  1.00  2.94           C  
ATOM   3291  CE1 TYR B  94      33.683  28.579  12.342  1.00  5.22           C  
ATOM   3292  CE2 TYR B  94      32.186  26.956  11.554  1.00  3.45           C  
ATOM   3293  CZ  TYR B  94      33.462  27.435  11.632  1.00  4.95           C  
ATOM   3294  OH  TYR B  94      34.552  26.811  11.035  1.00  6.26           O  
ATOM   3295  N   ASN B  95      31.833  29.942  16.313  1.00  5.22           N  
ATOM   3296  CA  ASN B  95      33.053  29.977  17.086  1.00  6.74           C  
ATOM   3297  C   ASN B  95      32.980  29.100  18.311  1.00  8.40           C  
ATOM   3298  O   ASN B  95      33.858  28.242  18.439  1.00  9.61           O  
ATOM   3299  CB  ASN B  95      33.404  31.393  17.541  1.00  7.32           C  
ATOM   3300  CG  ASN B  95      33.990  32.278  16.424  1.00  7.83           C  
ATOM   3301  OD1 ASN B  95      34.009  31.879  15.262  1.00  6.85           O  
ATOM   3302  ND2 ASN B  95      34.430  33.522  16.652  1.00  7.48           N  
ATOM   3303  N   ALA B  96      31.940  29.182  19.172  1.00  7.72           N  
ATOM   3304  CA  ALA B  96      31.906  28.345  20.365  1.00  6.47           C  
ATOM   3305  C   ALA B  96      31.861  26.862  19.996  1.00  7.44           C  
ATOM   3306  O   ALA B  96      32.548  26.025  20.618  1.00  7.68           O  
ATOM   3307  CB  ALA B  96      30.713  28.720  21.167  1.00  5.58           C  
ATOM   3308  N   GLU B  97      31.202  26.520  18.879  1.00  7.88           N  
ATOM   3309  CA  GLU B  97      31.067  25.117  18.478  1.00  7.52           C  
ATOM   3310  C   GLU B  97      32.372  24.552  17.946  1.00  6.01           C  
ATOM   3311  O   GLU B  97      32.746  23.414  18.281  1.00  7.19           O  
ATOM   3312  CB  GLU B  97      29.984  25.019  17.442  1.00  7.49           C  
ATOM   3313  CG  GLU B  97      29.653  23.661  16.916  1.00  9.56           C  
ATOM   3314  CD  GLU B  97      28.879  22.709  17.832  1.00 12.02           C  
ATOM   3315  OE1 GLU B  97      29.329  21.558  17.997  1.00 12.98           O  
ATOM   3316  OE2 GLU B  97      27.808  23.048  18.365  1.00 12.74           O  
ATOM   3317  N   LEU B  98      33.128  25.333  17.183  1.00  4.34           N  
ATOM   3318  CA  LEU B  98      34.376  24.817  16.678  1.00  4.04           C  
ATOM   3319  C   LEU B  98      35.383  24.754  17.805  1.00  5.63           C  
ATOM   3320  O   LEU B  98      36.179  23.815  17.864  1.00  7.10           O  
ATOM   3321  CB  LEU B  98      34.956  25.682  15.571  1.00  3.86           C  
ATOM   3322  CG  LEU B  98      36.335  25.283  15.023  1.00  4.04           C  
ATOM   3323  CD1 LEU B  98      36.272  24.097  14.085  1.00  3.67           C  
ATOM   3324  CD2 LEU B  98      36.859  26.428  14.246  1.00  3.75           C  
ATOM   3325  N   LEU B  99      35.351  25.721  18.736  1.00  6.74           N  
ATOM   3326  CA  LEU B  99      36.296  25.814  19.845  1.00  4.77           C  
ATOM   3327  C   LEU B  99      36.175  24.562  20.651  1.00  5.42           C  
ATOM   3328  O   LEU B  99      37.161  23.826  20.632  1.00  5.20           O  
ATOM   3329  CB  LEU B  99      36.017  27.008  20.786  1.00  3.68           C  
ATOM   3330  CG  LEU B  99      36.858  27.145  22.041  1.00  2.80           C  
ATOM   3331  CD1 LEU B  99      38.266  27.364  21.623  1.00  2.01           C  
ATOM   3332  CD2 LEU B  99      36.439  28.321  22.884  1.00  2.74           C  
ATOM   3333  N   VAL B 100      34.997  24.206  21.224  1.00  5.37           N  
ATOM   3334  CA  VAL B 100      34.996  22.998  22.059  1.00  5.56           C  
ATOM   3335  C   VAL B 100      35.355  21.740  21.268  1.00  5.42           C  
ATOM   3336  O   VAL B 100      36.043  20.857  21.784  1.00  5.34           O  
ATOM   3337  CB  VAL B 100      33.649  22.774  22.769  1.00  4.47           C  
ATOM   3338  CG1 VAL B 100      33.312  24.112  23.384  1.00  4.46           C  
ATOM   3339  CG2 VAL B 100      32.565  22.223  21.882  1.00  5.49           C  
ATOM   3340  N   ALA B 101      34.997  21.682  19.984  1.00  4.99           N  
ATOM   3341  CA  ALA B 101      35.383  20.558  19.158  1.00  5.17           C  
ATOM   3342  C   ALA B 101      36.905  20.394  19.049  1.00  5.08           C  
ATOM   3343  O   ALA B 101      37.433  19.319  19.346  1.00  4.89           O  
ATOM   3344  CB  ALA B 101      34.796  20.771  17.806  1.00  4.15           C  
ATOM   3345  N   LEU B 102      37.639  21.449  18.686  1.00  5.41           N  
ATOM   3346  CA  LEU B 102      39.089  21.361  18.579  1.00  6.02           C  
ATOM   3347  C   LEU B 102      39.666  21.019  19.967  1.00  7.10           C  
ATOM   3348  O   LEU B 102      40.348  20.004  20.142  1.00  6.36           O  
ATOM   3349  CB  LEU B 102      39.669  22.673  18.136  1.00  5.61           C  
ATOM   3350  CG  LEU B 102      39.298  23.241  16.818  1.00  6.39           C  
ATOM   3351  CD1 LEU B 102      39.739  24.683  16.742  1.00  7.88           C  
ATOM   3352  CD2 LEU B 102      40.042  22.545  15.731  1.00  7.00           C  
ATOM   3353  N   GLU B 103      39.291  21.812  20.973  1.00  7.83           N  
ATOM   3354  CA  GLU B 103      39.695  21.625  22.333  1.00  8.40           C  
ATOM   3355  C   GLU B 103      39.524  20.170  22.820  1.00 10.48           C  
ATOM   3356  O   GLU B 103      40.503  19.554  23.291  1.00 12.12           O  
ATOM   3357  CB  GLU B 103      38.875  22.570  23.189  1.00  8.20           C  
ATOM   3358  CG  GLU B 103      39.291  24.019  23.106  1.00  9.00           C  
ATOM   3359  CD  GLU B 103      40.604  24.361  23.793  1.00 10.01           C  
ATOM   3360  OE1 GLU B 103      40.761  25.465  24.309  1.00 11.43           O  
ATOM   3361  OE2 GLU B 103      41.511  23.536  23.816  1.00 10.50           O  
ATOM   3362  N   ASN B 104      38.334  19.560  22.616  1.00  9.22           N  
ATOM   3363  CA  ASN B 104      38.034  18.229  23.097  1.00  7.04           C  
ATOM   3364  C   ASN B 104      38.864  17.202  22.407  1.00  6.45           C  
ATOM   3365  O   ASN B 104      39.377  16.261  23.012  1.00  6.81           O  
ATOM   3366  CB  ASN B 104      36.597  17.871  22.877  1.00  6.94           C  
ATOM   3367  CG  ASN B 104      35.702  18.597  23.849  1.00  8.42           C  
ATOM   3368  OD1 ASN B 104      36.132  18.963  24.941  1.00  8.01           O  
ATOM   3369  ND2 ASN B 104      34.430  18.863  23.598  1.00 10.47           N  
ATOM   3370  N   GLN B 105      39.080  17.423  21.127  1.00  6.85           N  
ATOM   3371  CA  GLN B 105      39.851  16.512  20.336  1.00  8.08           C  
ATOM   3372  C   GLN B 105      41.255  16.511  20.900  1.00  7.60           C  
ATOM   3373  O   GLN B 105      41.806  15.460  21.227  1.00  7.03           O  
ATOM   3374  CB  GLN B 105      39.819  17.001  18.930  1.00  9.59           C  
ATOM   3375  CG  GLN B 105      40.554  16.111  17.968  1.00 12.68           C  
ATOM   3376  CD  GLN B 105      39.829  14.807  17.668  1.00 14.18           C  
ATOM   3377  OE1 GLN B 105      38.777  14.789  17.023  1.00 13.62           O  
ATOM   3378  NE2 GLN B 105      40.381  13.673  18.087  1.00 16.03           N  
ATOM   3379  N   HIS B 106      41.776  17.700  21.168  1.00  7.75           N  
ATOM   3380  CA  HIS B 106      43.127  17.802  21.684  1.00  7.91           C  
ATOM   3381  C   HIS B 106      43.207  17.264  23.108  1.00  8.88           C  
ATOM   3382  O   HIS B 106      44.233  16.640  23.401  1.00 10.74           O  
ATOM   3383  CB  HIS B 106      43.577  19.249  21.622  1.00  7.02           C  
ATOM   3384  CG  HIS B 106      44.931  19.546  22.219  1.00  6.48           C  
ATOM   3385  ND1 HIS B 106      45.079  20.436  23.199  1.00  6.89           N  
ATOM   3386  CD2 HIS B 106      46.093  18.989  21.820  1.00  6.15           C  
ATOM   3387  CE1 HIS B 106      46.380  20.439  23.414  1.00  6.00           C  
ATOM   3388  NE2 HIS B 106      46.960  19.587  22.598  1.00  6.44           N  
ATOM   3389  N   THR B 107      42.210  17.439  24.005  1.00  7.77           N  
ATOM   3390  CA  THR B 107      42.282  16.856  25.334  1.00  6.97           C  
ATOM   3391  C   THR B 107      42.344  15.345  25.229  1.00  7.52           C  
ATOM   3392  O   THR B 107      43.196  14.740  25.902  1.00  9.78           O  
ATOM   3393  CB  THR B 107      41.080  17.244  26.212  1.00  5.70           C  
ATOM   3394  OG1 THR B 107      41.169  18.667  26.350  1.00  6.07           O  
ATOM   3395  CG2 THR B 107      41.057  16.569  27.582  1.00  4.31           C  
ATOM   3396  N   ILE B 108      41.564  14.701  24.361  1.00  6.83           N  
ATOM   3397  CA  ILE B 108      41.692  13.254  24.266  1.00  7.20           C  
ATOM   3398  C   ILE B 108      43.056  12.819  23.721  1.00  8.64           C  
ATOM   3399  O   ILE B 108      43.577  11.823  24.249  1.00  9.95           O  
ATOM   3400  CB  ILE B 108      40.550  12.706  23.412  1.00  5.16           C  
ATOM   3401  CG1 ILE B 108      39.273  12.958  24.176  1.00  5.00           C  
ATOM   3402  CG2 ILE B 108      40.700  11.231  23.154  1.00  4.47           C  
ATOM   3403  CD1 ILE B 108      37.996  12.648  23.400  1.00  4.78           C  
ATOM   3404  N   ASP B 109      43.705  13.537  22.785  1.00  8.15           N  
ATOM   3405  CA  ASP B 109      45.016  13.075  22.332  1.00  7.91           C  
ATOM   3406  C   ASP B 109      46.100  13.401  23.313  1.00  8.14           C  
ATOM   3407  O   ASP B 109      47.057  12.651  23.470  1.00  7.80           O  
ATOM   3408  CB  ASP B 109      45.407  13.680  21.008  1.00  8.15           C  
ATOM   3409  CG  ASP B 109      44.507  13.231  19.881  1.00  9.13           C  
ATOM   3410  OD1 ASP B 109      43.993  12.108  19.901  1.00  9.35           O  
ATOM   3411  OD2 ASP B 109      44.291  14.012  18.963  1.00 10.43           O  
ATOM   3412  N   LEU B 110      45.982  14.508  24.029  1.00  8.67           N  
ATOM   3413  CA  LEU B 110      46.942  14.901  25.056  1.00  8.91           C  
ATOM   3414  C   LEU B 110      46.981  13.851  26.169  1.00  9.23           C  
ATOM   3415  O   LEU B 110      48.044  13.385  26.553  1.00 10.09           O  
ATOM   3416  CB  LEU B 110      46.487  16.250  25.537  1.00  8.28           C  
ATOM   3417  CG  LEU B 110      46.994  17.006  26.711  1.00  8.70           C  
ATOM   3418  CD1 LEU B 110      46.438  18.397  26.557  1.00 10.18           C  
ATOM   3419  CD2 LEU B 110      46.494  16.489  28.027  1.00  8.58           C  
ATOM   3420  N   THR B 111      45.835  13.412  26.691  1.00  8.95           N  
ATOM   3421  CA  THR B 111      45.833  12.396  27.725  1.00  8.63           C  
ATOM   3422  C   THR B 111      46.270  11.035  27.168  1.00  9.37           C  
ATOM   3423  O   THR B 111      46.905  10.253  27.890  1.00 10.35           O  
ATOM   3424  CB  THR B 111      44.432  12.350  28.340  1.00  8.18           C  
ATOM   3425  OG1 THR B 111      43.486  12.251  27.265  1.00  8.28           O  
ATOM   3426  CG2 THR B 111      44.150  13.580  29.184  1.00  6.73           C  
ATOM   3427  N   ASP B 112      45.992  10.741  25.879  1.00  8.71           N  
ATOM   3428  CA  ASP B 112      46.494   9.515  25.236  1.00  8.54           C  
ATOM   3429  C   ASP B 112      48.035   9.562  25.223  1.00  7.53           C  
ATOM   3430  O   ASP B 112      48.745   8.631  25.619  1.00  5.92           O  
ATOM   3431  CB  ASP B 112      45.968   9.405  23.778  1.00  9.34           C  
ATOM   3432  CG  ASP B 112      46.126   8.020  23.158  1.00 11.00           C  
ATOM   3433  OD1 ASP B 112      46.744   7.137  23.741  1.00 11.31           O  
ATOM   3434  OD2 ASP B 112      45.597   7.760  22.074  1.00 11.85           O  
ATOM   3435  N   SER B 113      48.559  10.738  24.872  1.00  7.06           N  
ATOM   3436  CA  SER B 113      49.960  11.010  24.870  1.00  7.48           C  
ATOM   3437  C   SER B 113      50.569  10.754  26.234  1.00  8.90           C  
ATOM   3438  O   SER B 113      51.514   9.946  26.297  1.00 10.73           O  
ATOM   3439  CB  SER B 113      50.183  12.447  24.456  1.00  7.33           C  
ATOM   3440  OG  SER B 113      51.500  12.960  24.659  1.00  6.97           O  
ATOM   3441  N   GLU B 114      50.062  11.354  27.324  1.00  9.09           N  
ATOM   3442  CA  GLU B 114      50.662  11.152  28.632  1.00  9.05           C  
ATOM   3443  C   GLU B 114      50.690   9.691  29.011  1.00  9.09           C  
ATOM   3444  O   GLU B 114      51.727   9.248  29.519  1.00  9.15           O  
ATOM   3445  CB  GLU B 114      49.924  11.888  29.722  1.00  9.95           C  
ATOM   3446  CG  GLU B 114      50.048  13.403  29.696  1.00 11.52           C  
ATOM   3447  CD  GLU B 114      51.466  13.932  29.550  1.00 12.97           C  
ATOM   3448  OE1 GLU B 114      51.669  14.873  28.767  1.00 13.31           O  
ATOM   3449  OE2 GLU B 114      52.396  13.406  30.166  1.00 13.35           O  
ATOM   3450  N   MET B 115      49.635   8.917  28.693  1.00  7.76           N  
ATOM   3451  CA  MET B 115      49.654   7.500  28.983  1.00  7.11           C  
ATOM   3452  C   MET B 115      50.815   6.851  28.272  1.00  7.04           C  
ATOM   3453  O   MET B 115      51.674   6.219  28.896  1.00  6.70           O  
ATOM   3454  CB  MET B 115      48.382   6.831  28.526  1.00  7.76           C  
ATOM   3455  CG  MET B 115      48.326   5.333  28.772  1.00  8.44           C  
ATOM   3456  SD  MET B 115      48.126   4.981  30.520  1.00 11.12           S  
ATOM   3457  CE  MET B 115      49.740   4.359  30.919  1.00 10.23           C  
ATOM   3458  N   ASN B 116      50.892   7.066  26.961  1.00  7.83           N  
ATOM   3459  CA  ASN B 116      51.958   6.493  26.155  1.00  8.11           C  
ATOM   3460  C   ASN B 116      53.333   6.970  26.615  1.00  8.95           C  
ATOM   3461  O   ASN B 116      54.281   6.193  26.647  1.00  9.98           O  
ATOM   3462  CB  ASN B 116      51.738   6.878  24.737  1.00  7.56           C  
ATOM   3463  CG  ASN B 116      52.763   6.233  23.848  1.00  7.56           C  
ATOM   3464  OD1 ASN B 116      52.741   5.059  23.484  1.00  7.06           O  
ATOM   3465  ND2 ASN B 116      53.691   7.089  23.498  1.00  8.18           N  
ATOM   3466  N   LYS B 117      53.491   8.212  27.054  1.00  7.92           N  
ATOM   3467  CA  LYS B 117      54.773   8.662  27.538  1.00  7.30           C  
ATOM   3468  C   LYS B 117      55.172   7.921  28.808  1.00  9.36           C  
ATOM   3469  O   LYS B 117      56.331   7.550  28.925  1.00 10.73           O  
ATOM   3470  CB  LYS B 117      54.746  10.113  27.862  1.00  5.50           C  
ATOM   3471  CG  LYS B 117      54.479  11.039  26.721  1.00  4.59           C  
ATOM   3472  CD  LYS B 117      54.712  12.337  27.382  1.00  3.75           C  
ATOM   3473  CE  LYS B 117      54.568  13.535  26.516  1.00  4.39           C  
ATOM   3474  NZ  LYS B 117      53.826  14.459  27.358  1.00  6.17           N  
ATOM   3475  N   LEU B 118      54.277   7.682  29.787  1.00 10.58           N  
ATOM   3476  CA  LEU B 118      54.617   6.905  30.974  1.00 10.03           C  
ATOM   3477  C   LEU B 118      55.063   5.527  30.505  1.00 11.14           C  
ATOM   3478  O   LEU B 118      56.092   5.008  30.950  1.00 12.00           O  
ATOM   3479  CB  LEU B 118      53.440   6.657  31.897  1.00  9.28           C  
ATOM   3480  CG  LEU B 118      53.549   6.844  33.396  1.00  8.99           C  
ATOM   3481  CD1 LEU B 118      52.408   6.092  34.079  1.00  8.96           C  
ATOM   3482  CD2 LEU B 118      54.846   6.286  33.904  1.00  8.76           C  
ATOM   3483  N   PHE B 119      54.335   4.943  29.560  1.00 11.24           N  
ATOM   3484  CA  PHE B 119      54.673   3.633  29.090  1.00 12.62           C  
ATOM   3485  C   PHE B 119      56.089   3.598  28.565  1.00 14.87           C  
ATOM   3486  O   PHE B 119      56.879   2.753  28.964  1.00 17.64           O  
ATOM   3487  CB  PHE B 119      53.736   3.213  28.001  1.00 11.58           C  
ATOM   3488  CG  PHE B 119      54.007   1.764  27.690  1.00 11.39           C  
ATOM   3489  CD1 PHE B 119      53.443   0.809  28.499  1.00 11.42           C  
ATOM   3490  CD2 PHE B 119      54.837   1.413  26.639  1.00 11.38           C  
ATOM   3491  CE1 PHE B 119      53.724  -0.514  28.253  1.00 11.30           C  
ATOM   3492  CE2 PHE B 119      55.105   0.087  26.408  1.00 10.71           C  
ATOM   3493  CZ  PHE B 119      54.547  -0.867  27.216  1.00 10.65           C  
ATOM   3494  N   GLU B 120      56.447   4.519  27.709  1.00 16.26           N  
ATOM   3495  CA  GLU B 120      57.753   4.569  27.132  1.00 16.87           C  
ATOM   3496  C   GLU B 120      58.816   4.845  28.140  1.00 16.80           C  
ATOM   3497  O   GLU B 120      59.909   4.316  28.036  1.00 18.07           O  
ATOM   3498  CB  GLU B 120      57.701   5.619  26.091  1.00 19.66           C  
ATOM   3499  CG  GLU B 120      56.932   5.126  24.891  1.00 23.24           C  
ATOM   3500  CD  GLU B 120      57.854   4.202  24.150  1.00 26.31           C  
ATOM   3501  OE1 GLU B 120      58.794   4.726  23.515  1.00 28.49           O  
ATOM   3502  OE2 GLU B 120      57.740   2.974  24.298  1.00 27.53           O  
ATOM   3503  N   LYS B 121      58.539   5.658  29.139  1.00 18.28           N  
ATOM   3504  CA  LYS B 121      59.512   6.032  30.165  1.00 20.01           C  
ATOM   3505  C   LYS B 121      59.829   4.809  30.999  1.00 20.45           C  
ATOM   3506  O   LYS B 121      60.999   4.548  31.282  1.00 21.45           O  
ATOM   3507  CB  LYS B 121      58.931   7.116  31.032  1.00 20.65           C  
ATOM   3508  CG  LYS B 121      59.767   7.575  32.183  1.00 23.05           C  
ATOM   3509  CD  LYS B 121      58.988   8.716  32.889  1.00 26.00           C  
ATOM   3510  CE  LYS B 121      59.659   9.236  34.197  1.00 27.85           C  
ATOM   3511  NZ  LYS B 121      59.826   8.172  35.199  1.00 29.82           N  
ATOM   3512  N   THR B 122      58.805   4.041  31.362  1.00 20.04           N  
ATOM   3513  CA  THR B 122      59.003   2.803  32.079  1.00 18.43           C  
ATOM   3514  C   THR B 122      59.743   1.818  31.203  1.00 17.75           C  
ATOM   3515  O   THR B 122      60.690   1.202  31.690  1.00 19.90           O  
ATOM   3516  CB  THR B 122      57.641   2.269  32.499  1.00 18.11           C  
ATOM   3517  OG1 THR B 122      57.143   3.257  33.398  1.00 17.70           O  
ATOM   3518  CG2 THR B 122      57.682   0.892  33.141  1.00 17.75           C  
ATOM   3519  N   ARG B 123      59.407   1.713  29.918  1.00 15.95           N  
ATOM   3520  CA  ARG B 123      60.069   0.800  29.019  1.00 14.99           C  
ATOM   3521  C   ARG B 123      61.566   1.075  28.995  1.00 15.07           C  
ATOM   3522  O   ARG B 123      62.366   0.156  29.180  1.00 15.63           O  
ATOM   3523  CB  ARG B 123      59.515   0.972  27.653  1.00 15.07           C  
ATOM   3524  CG  ARG B 123      60.058  -0.016  26.693  1.00 16.70           C  
ATOM   3525  CD  ARG B 123      59.829   0.550  25.314  1.00 17.78           C  
ATOM   3526  NE  ARG B 123      61.116   0.918  24.740  1.00 19.06           N  
ATOM   3527  CZ  ARG B 123      61.403   2.169  24.392  1.00 19.84           C  
ATOM   3528  NH1 ARG B 123      62.594   2.476  23.840  1.00 20.99           N  
ATOM   3529  NH2 ARG B 123      60.498   3.089  24.610  1.00 20.18           N  
ATOM   3530  N   ARG B 124      61.948   2.340  28.855  1.00 14.04           N  
ATOM   3531  CA  ARG B 124      63.339   2.697  28.764  1.00 13.71           C  
ATOM   3532  C   ARG B 124      64.133   2.385  29.984  1.00 14.85           C  
ATOM   3533  O   ARG B 124      65.303   2.045  29.853  1.00 16.38           O  
ATOM   3534  CB  ARG B 124      63.499   4.128  28.522  1.00 12.41           C  
ATOM   3535  CG  ARG B 124      63.363   4.205  27.077  1.00 11.52           C  
ATOM   3536  CD  ARG B 124      63.031   5.609  26.866  1.00 11.10           C  
ATOM   3537  NE  ARG B 124      63.171   5.734  25.457  1.00 10.57           N  
ATOM   3538  CZ  ARG B 124      62.411   6.492  24.723  1.00 11.70           C  
ATOM   3539  NH1 ARG B 124      62.654   6.490  23.418  1.00 12.35           N  
ATOM   3540  NH2 ARG B 124      61.497   7.268  25.320  1.00 14.60           N  
ATOM   3541  N   GLN B 125      63.509   2.528  31.146  1.00 15.13           N  
ATOM   3542  CA  GLN B 125      64.138   2.294  32.433  1.00 15.01           C  
ATOM   3543  C   GLN B 125      64.466   0.830  32.643  1.00 15.59           C  
ATOM   3544  O   GLN B 125      65.563   0.496  33.097  1.00 16.56           O  
ATOM   3545  CB  GLN B 125      63.168   2.824  33.442  1.00 14.85           C  
ATOM   3546  CG  GLN B 125      63.508   2.712  34.875  1.00 17.12           C  
ATOM   3547  CD  GLN B 125      62.682   3.713  35.678  1.00 19.39           C  
ATOM   3548  OE1 GLN B 125      63.271   4.612  36.273  1.00 22.15           O  
ATOM   3549  NE2 GLN B 125      61.352   3.713  35.759  1.00 18.79           N  
ATOM   3550  N   LEU B 126      63.560  -0.076  32.249  1.00 14.86           N  
ATOM   3551  CA  LEU B 126      63.783  -1.502  32.452  1.00 13.43           C  
ATOM   3552  C   LEU B 126      64.834  -2.102  31.535  1.00 13.86           C  
ATOM   3553  O   LEU B 126      65.208  -3.262  31.718  1.00 14.30           O  
ATOM   3554  CB  LEU B 126      62.484  -2.250  32.257  1.00 11.80           C  
ATOM   3555  CG  LEU B 126      61.454  -1.920  33.273  1.00 10.09           C  
ATOM   3556  CD1 LEU B 126      60.124  -2.455  32.854  1.00 10.11           C  
ATOM   3557  CD2 LEU B 126      61.885  -2.510  34.565  1.00 10.47           C  
ATOM   3558  N   ARG B 127      65.297  -1.353  30.544  1.00 14.13           N  
ATOM   3559  CA  ARG B 127      66.332  -1.779  29.636  1.00 15.34           C  
ATOM   3560  C   ARG B 127      66.214  -3.228  29.185  1.00 17.01           C  
ATOM   3561  O   ARG B 127      65.098  -3.599  28.796  1.00 18.88           O  
ATOM   3562  CB  ARG B 127      67.617  -1.483  30.317  1.00 14.37           C  
ATOM   3563  CG  ARG B 127      68.108  -0.204  29.740  1.00 14.81           C  
ATOM   3564  CD  ARG B 127      69.179  -0.465  28.714  1.00 15.51           C  
ATOM   3565  NE  ARG B 127      70.273   0.383  29.139  1.00 16.10           N  
ATOM   3566  CZ  ARG B 127      71.496   0.252  28.634  1.00 18.13           C  
ATOM   3567  NH1 ARG B 127      72.488   1.061  29.058  1.00 19.18           N  
ATOM   3568  NH2 ARG B 127      71.736  -0.666  27.710  1.00 19.30           N  
ATOM   3569  N   GLU B 128      67.213  -4.110  29.336  1.00 17.04           N  
ATOM   3570  CA  GLU B 128      67.088  -5.450  28.803  1.00 17.28           C  
ATOM   3571  C   GLU B 128      66.461  -6.431  29.763  1.00 16.62           C  
ATOM   3572  O   GLU B 128      66.454  -7.643  29.515  1.00 17.08           O  
ATOM   3573  CB  GLU B 128      68.463  -5.916  28.402  1.00 19.02           C  
ATOM   3574  CG  GLU B 128      68.528  -6.309  26.947  1.00 21.64           C  
ATOM   3575  CD  GLU B 128      68.269  -5.234  25.906  1.00 23.04           C  
ATOM   3576  OE1 GLU B 128      68.169  -5.600  24.734  1.00 24.60           O  
ATOM   3577  OE2 GLU B 128      68.178  -4.057  26.230  1.00 24.21           O  
ATOM   3578  N   ASN B 129      65.832  -5.941  30.819  1.00 15.45           N  
ATOM   3579  CA  ASN B 129      65.379  -6.818  31.886  1.00 14.50           C  
ATOM   3580  C   ASN B 129      63.908  -7.141  31.826  1.00 14.43           C  
ATOM   3581  O   ASN B 129      63.401  -7.940  32.628  1.00 13.67           O  
ATOM   3582  CB  ASN B 129      65.687  -6.186  33.233  1.00 14.52           C  
ATOM   3583  CG  ASN B 129      67.157  -5.786  33.413  1.00 16.24           C  
ATOM   3584  OD1 ASN B 129      68.057  -6.022  32.578  1.00 17.16           O  
ATOM   3585  ND2 ASN B 129      67.470  -5.087  34.495  1.00 16.02           N  
ATOM   3586  N   ALA B 130      63.169  -6.568  30.881  1.00 14.35           N  
ATOM   3587  CA  ALA B 130      61.746  -6.820  30.823  1.00 13.09           C  
ATOM   3588  C   ALA B 130      61.313  -6.935  29.398  1.00 13.34           C  
ATOM   3589  O   ALA B 130      62.069  -6.571  28.504  1.00 14.32           O  
ATOM   3590  CB  ALA B 130      61.007  -5.693  31.450  1.00 11.85           C  
ATOM   3591  N   GLU B 131      60.148  -7.492  29.158  1.00 14.60           N  
ATOM   3592  CA  GLU B 131      59.631  -7.568  27.819  1.00 16.93           C  
ATOM   3593  C   GLU B 131      58.217  -7.029  27.799  1.00 18.60           C  
ATOM   3594  O   GLU B 131      57.464  -7.112  28.780  1.00 17.08           O  
ATOM   3595  CB  GLU B 131      59.640  -8.999  27.314  1.00 17.06           C  
ATOM   3596  CG  GLU B 131      61.016  -9.356  26.805  1.00 18.60           C  
ATOM   3597  CD  GLU B 131      61.214 -10.769  26.317  1.00 19.94           C  
ATOM   3598  OE1 GLU B 131      60.444 -11.289  25.516  1.00 21.17           O  
ATOM   3599  OE2 GLU B 131      62.167 -11.402  26.745  1.00 20.44           O  
ATOM   3600  N   GLU B 132      57.850  -6.420  26.677  1.00 20.46           N  
ATOM   3601  CA  GLU B 132      56.510  -5.911  26.543  1.00 21.63           C  
ATOM   3602  C   GLU B 132      55.548  -7.046  26.331  1.00 23.38           C  
ATOM   3603  O   GLU B 132      55.835  -7.952  25.543  1.00 25.99           O  
ATOM   3604  CB  GLU B 132      56.402  -5.036  25.380  1.00 20.81           C  
ATOM   3605  CG  GLU B 132      55.476  -4.069  25.954  1.00 21.07           C  
ATOM   3606  CD  GLU B 132      54.845  -3.230  24.924  1.00 22.51           C  
ATOM   3607  OE1 GLU B 132      53.609  -3.189  24.970  1.00 24.41           O  
ATOM   3608  OE2 GLU B 132      55.549  -2.613  24.093  1.00 22.79           O  
ATOM   3609  N   MET B 133      54.451  -7.099  27.055  1.00 24.22           N  
ATOM   3610  CA  MET B 133      53.476  -8.125  26.772  1.00 26.26           C  
ATOM   3611  C   MET B 133      52.434  -7.568  25.826  1.00 27.53           C  
ATOM   3612  O   MET B 133      51.450  -8.242  25.512  1.00 28.19           O  
ATOM   3613  CB  MET B 133      52.835  -8.578  28.060  1.00 27.16           C  
ATOM   3614  CG  MET B 133      53.847  -9.300  28.941  1.00 28.20           C  
ATOM   3615  SD  MET B 133      53.248  -9.450  30.640  1.00 29.76           S  
ATOM   3616  CE  MET B 133      52.517 -11.043  30.438  1.00 28.67           C  
ATOM   3617  N   GLY B 134      52.601  -6.307  25.396  1.00 28.56           N  
ATOM   3618  CA  GLY B 134      51.714  -5.716  24.397  1.00 28.59           C  
ATOM   3619  C   GLY B 134      50.335  -5.318  24.892  1.00 27.90           C  
ATOM   3620  O   GLY B 134      49.452  -4.962  24.118  1.00 28.73           O  
ATOM   3621  N   ASN B 135      50.098  -5.374  26.175  1.00 26.77           N  
ATOM   3622  CA  ASN B 135      48.808  -4.961  26.693  1.00 26.11           C  
ATOM   3623  C   ASN B 135      49.056  -3.957  27.794  1.00 24.86           C  
ATOM   3624  O   ASN B 135      48.284  -3.863  28.752  1.00 24.36           O  
ATOM   3625  CB  ASN B 135      48.042  -6.128  27.288  1.00 28.30           C  
ATOM   3626  CG  ASN B 135      48.808  -6.761  28.435  1.00 29.84           C  
ATOM   3627  OD1 ASN B 135      50.043  -6.650  28.528  1.00 31.41           O  
ATOM   3628  ND2 ASN B 135      48.126  -7.428  29.345  1.00 30.27           N  
ATOM   3629  N   GLY B 136      50.180  -3.232  27.699  1.00 23.27           N  
ATOM   3630  CA  GLY B 136      50.503  -2.283  28.742  1.00 20.20           C  
ATOM   3631  C   GLY B 136      51.248  -2.921  29.910  1.00 19.05           C  
ATOM   3632  O   GLY B 136      51.640  -2.194  30.824  1.00 19.49           O  
ATOM   3633  N   CYS B 137      51.497  -4.234  29.935  1.00 16.93           N  
ATOM   3634  CA  CYS B 137      52.262  -4.848  31.007  1.00 15.42           C  
ATOM   3635  C   CYS B 137      53.655  -5.267  30.633  1.00 15.21           C  
ATOM   3636  O   CYS B 137      53.832  -5.895  29.592  1.00 16.46           O  
ATOM   3637  CB  CYS B 137      51.620  -6.094  31.501  1.00 15.75           C  
ATOM   3638  SG  CYS B 137      49.880  -5.798  31.954  1.00 16.04           S  
ATOM   3639  N   PHE B 138      54.660  -4.933  31.419  1.00 15.09           N  
ATOM   3640  CA  PHE B 138      55.979  -5.480  31.208  1.00 15.54           C  
ATOM   3641  C   PHE B 138      56.097  -6.775  32.006  1.00 16.80           C  
ATOM   3642  O   PHE B 138      55.554  -6.868  33.106  1.00 15.30           O  
ATOM   3643  CB  PHE B 138      57.066  -4.543  31.693  1.00 13.18           C  
ATOM   3644  CG  PHE B 138      57.046  -3.265  30.897  1.00 11.83           C  
ATOM   3645  CD1 PHE B 138      56.334  -2.185  31.371  1.00 10.94           C  
ATOM   3646  CD2 PHE B 138      57.723  -3.200  29.703  1.00 11.32           C  
ATOM   3647  CE1 PHE B 138      56.297  -1.024  30.648  1.00 10.18           C  
ATOM   3648  CE2 PHE B 138      57.682  -2.028  28.984  1.00 11.33           C  
ATOM   3649  CZ  PHE B 138      56.973  -0.944  29.453  1.00 11.13           C  
ATOM   3650  N   LYS B 139      56.740  -7.799  31.446  1.00 18.83           N  
ATOM   3651  CA  LYS B 139      57.125  -8.961  32.202  1.00 20.21           C  
ATOM   3652  C   LYS B 139      58.556  -8.701  32.656  1.00 21.25           C  
ATOM   3653  O   LYS B 139      59.447  -8.611  31.796  1.00 22.97           O  
ATOM   3654  CB  LYS B 139      57.124 -10.184  31.357  1.00 21.76           C  
ATOM   3655  CG  LYS B 139      57.650 -11.363  32.145  1.00 24.55           C  
ATOM   3656  CD  LYS B 139      57.266 -12.581  31.349  1.00 28.11           C  
ATOM   3657  CE  LYS B 139      57.400 -13.839  32.203  1.00 30.28           C  
ATOM   3658  NZ  LYS B 139      58.785 -14.278  32.284  1.00 32.50           N  
ATOM   3659  N   ILE B 140      58.815  -8.549  33.961  1.00 21.13           N  
ATOM   3660  CA  ILE B 140      60.166  -8.294  34.471  1.00 20.58           C  
ATOM   3661  C   ILE B 140      60.831  -9.652  34.662  1.00 21.56           C  
ATOM   3662  O   ILE B 140      60.288 -10.515  35.348  1.00 20.82           O  
ATOM   3663  CB  ILE B 140      60.047  -7.503  35.786  1.00 18.57           C  
ATOM   3664  CG1 ILE B 140      59.331  -6.205  35.506  1.00 17.67           C  
ATOM   3665  CG2 ILE B 140      61.409  -7.203  36.353  1.00 17.94           C  
ATOM   3666  CD1 ILE B 140      59.000  -5.345  36.699  1.00 17.02           C  
ATOM   3667  N   TYR B 141      61.957  -9.908  33.997  1.00 22.25           N  
ATOM   3668  CA  TYR B 141      62.587 -11.212  34.005  1.00 22.61           C  
ATOM   3669  C   TYR B 141      63.631 -11.392  35.084  1.00 24.11           C  
ATOM   3670  O   TYR B 141      64.782 -11.744  34.798  1.00 24.56           O  
ATOM   3671  CB  TYR B 141      63.213 -11.437  32.652  1.00 22.78           C  
ATOM   3672  CG  TYR B 141      62.238 -11.849  31.588  1.00 22.26           C  
ATOM   3673  CD1 TYR B 141      61.645 -10.898  30.804  1.00 22.47           C  
ATOM   3674  CD2 TYR B 141      61.993 -13.179  31.396  1.00 22.20           C  
ATOM   3675  CE1 TYR B 141      60.789 -11.287  29.802  1.00 22.80           C  
ATOM   3676  CE2 TYR B 141      61.144 -13.563  30.393  1.00 22.40           C  
ATOM   3677  CZ  TYR B 141      60.551 -12.614  29.605  1.00 22.60           C  
ATOM   3678  OH  TYR B 141      59.715 -13.021  28.592  1.00 23.99           O  
ATOM   3679  N   HIS B 142      63.304 -11.112  36.334  1.00 25.66           N  
ATOM   3680  CA  HIS B 142      64.261 -11.269  37.437  1.00 26.94           C  
ATOM   3681  C   HIS B 142      63.448 -11.046  38.692  1.00 29.13           C  
ATOM   3682  O   HIS B 142      62.330 -10.509  38.594  1.00 28.83           O  
ATOM   3683  CB  HIS B 142      65.433 -10.240  37.397  1.00 25.25           C  
ATOM   3684  CG  HIS B 142      65.078  -8.802  37.682  1.00 24.55           C  
ATOM   3685  ND1 HIS B 142      64.688  -8.347  38.855  1.00 23.79           N  
ATOM   3686  CD2 HIS B 142      65.092  -7.772  36.774  1.00 25.23           C  
ATOM   3687  CE1 HIS B 142      64.448  -7.073  38.712  1.00 24.04           C  
ATOM   3688  NE2 HIS B 142      64.692  -6.734  37.472  1.00 24.82           N  
ATOM   3689  N   LYS B 143      63.942 -11.438  39.869  1.00 32.19           N  
ATOM   3690  CA  LYS B 143      63.164 -11.326  41.093  1.00 33.54           C  
ATOM   3691  C   LYS B 143      63.041  -9.859  41.436  1.00 32.92           C  
ATOM   3692  O   LYS B 143      64.038  -9.172  41.624  1.00 33.43           O  
ATOM   3693  CB  LYS B 143      63.863 -12.077  42.227  1.00 36.03           C  
ATOM   3694  CG  LYS B 143      62.996 -12.201  43.483  1.00 38.71           C  
ATOM   3695  CD  LYS B 143      63.849 -12.266  44.772  1.00 41.23           C  
ATOM   3696  CE  LYS B 143      63.031 -12.446  46.084  1.00 42.36           C  
ATOM   3697  NZ  LYS B 143      62.227 -11.289  46.481  1.00 43.20           N  
ATOM   3698  N   CYS B 144      61.828  -9.346  41.487  1.00 32.89           N  
ATOM   3699  CA  CYS B 144      61.632  -7.935  41.788  1.00 33.87           C  
ATOM   3700  C   CYS B 144      60.638  -7.733  42.924  1.00 35.20           C  
ATOM   3701  O   CYS B 144      59.411  -7.712  42.763  1.00 33.41           O  
ATOM   3702  CB  CYS B 144      61.159  -7.242  40.518  1.00 32.91           C  
ATOM   3703  SG  CYS B 144      61.025  -5.443  40.662  1.00 30.50           S  
ATOM   3704  N   ASP B 145      61.206  -7.666  44.131  1.00 37.30           N  
ATOM   3705  CA  ASP B 145      60.429  -7.525  45.371  1.00 37.99           C  
ATOM   3706  C   ASP B 145      59.771  -6.156  45.407  1.00 37.02           C  
ATOM   3707  O   ASP B 145      60.061  -5.305  44.548  1.00 37.75           O  
ATOM   3708  CB  ASP B 145      61.374  -7.696  46.575  1.00 40.23           C  
ATOM   3709  CG  ASP B 145      62.391  -6.560  46.652  1.00 42.30           C  
ATOM   3710  OD1 ASP B 145      63.379  -6.569  45.911  1.00 44.65           O  
ATOM   3711  OD2 ASP B 145      62.163  -5.627  47.399  1.00 42.28           O  
ATOM   3712  N   ASN B 146      58.980  -5.856  46.424  1.00 35.78           N  
ATOM   3713  CA  ASN B 146      58.260  -4.594  46.438  1.00 34.67           C  
ATOM   3714  C   ASN B 146      59.165  -3.379  46.450  1.00 34.43           C  
ATOM   3715  O   ASN B 146      58.765  -2.317  45.974  1.00 35.38           O  
ATOM   3716  CB  ASN B 146      57.346  -4.456  47.627  1.00 34.75           C  
ATOM   3717  CG  ASN B 146      56.119  -5.344  47.560  1.00 35.87           C  
ATOM   3718  OD1 ASN B 146      55.413  -5.525  46.551  1.00 36.97           O  
ATOM   3719  ND2 ASN B 146      55.813  -5.966  48.674  1.00 36.28           N  
ATOM   3720  N   ALA B 147      60.404  -3.454  46.914  1.00 33.18           N  
ATOM   3721  CA  ALA B 147      61.255  -2.282  46.870  1.00 32.12           C  
ATOM   3722  C   ALA B 147      61.790  -2.111  45.473  1.00 31.31           C  
ATOM   3723  O   ALA B 147      62.009  -0.979  45.010  1.00 30.08           O  
ATOM   3724  CB  ALA B 147      62.443  -2.409  47.781  1.00 33.61           C  
ATOM   3725  N   CYS B 148      61.991  -3.247  44.793  1.00 30.62           N  
ATOM   3726  CA  CYS B 148      62.395  -3.195  43.398  1.00 30.62           C  
ATOM   3727  C   CYS B 148      61.253  -2.556  42.624  1.00 29.91           C  
ATOM   3728  O   CYS B 148      61.473  -1.553  41.928  1.00 30.12           O  
ATOM   3729  CB  CYS B 148      62.677  -4.593  42.915  1.00 30.16           C  
ATOM   3730  SG  CYS B 148      62.846  -4.693  41.136  1.00 31.09           S  
ATOM   3731  N   ILE B 149      60.008  -3.003  42.835  1.00 28.71           N  
ATOM   3732  CA  ILE B 149      58.875  -2.390  42.161  1.00 28.54           C  
ATOM   3733  C   ILE B 149      58.798  -0.904  42.480  1.00 29.52           C  
ATOM   3734  O   ILE B 149      58.598  -0.083  41.583  1.00 29.88           O  
ATOM   3735  CB  ILE B 149      57.557  -3.094  42.565  1.00 27.34           C  
ATOM   3736  CG1 ILE B 149      57.532  -4.518  42.024  1.00 26.53           C  
ATOM   3737  CG2 ILE B 149      56.353  -2.329  41.999  1.00 27.71           C  
ATOM   3738  CD1 ILE B 149      57.493  -4.689  40.483  1.00 25.25           C  
ATOM   3739  N   GLU B 150      59.030  -0.503  43.716  1.00 31.50           N  
ATOM   3740  CA  GLU B 150      58.984   0.909  44.057  1.00 32.97           C  
ATOM   3741  C   GLU B 150      60.083   1.680  43.372  1.00 31.08           C  
ATOM   3742  O   GLU B 150      59.817   2.792  42.940  1.00 30.50           O  
ATOM   3743  CB  GLU B 150      59.134   1.146  45.545  1.00 36.65           C  
ATOM   3744  CG  GLU B 150      57.986   1.911  46.214  1.00 41.55           C  
ATOM   3745  CD  GLU B 150      57.831   3.399  45.854  1.00 45.18           C  
ATOM   3746  OE1 GLU B 150      58.848   4.095  45.693  1.00 46.90           O  
ATOM   3747  OE2 GLU B 150      56.672   3.862  45.741  1.00 46.16           O  
ATOM   3748  N   SER B 151      61.266   1.110  43.137  1.00 30.23           N  
ATOM   3749  CA  SER B 151      62.297   1.891  42.474  1.00 30.61           C  
ATOM   3750  C   SER B 151      61.958   2.136  41.005  1.00 30.35           C  
ATOM   3751  O   SER B 151      62.396   3.135  40.411  1.00 30.53           O  
ATOM   3752  CB  SER B 151      63.658   1.207  42.560  1.00 30.78           C  
ATOM   3753  OG  SER B 151      63.782  -0.100  41.993  1.00 32.21           O  
ATOM   3754  N   ILE B 152      61.191   1.227  40.366  1.00 28.81           N  
ATOM   3755  CA  ILE B 152      60.789   1.439  38.976  1.00 27.04           C  
ATOM   3756  C   ILE B 152      59.843   2.622  38.971  1.00 27.77           C  
ATOM   3757  O   ILE B 152      59.987   3.560  38.178  1.00 28.24           O  
ATOM   3758  CB  ILE B 152      60.085   0.187  38.413  1.00 24.36           C  
ATOM   3759  CG1 ILE B 152      61.072  -0.955  38.364  1.00 23.79           C  
ATOM   3760  CG2 ILE B 152      59.547   0.471  37.030  1.00 23.35           C  
ATOM   3761  CD1 ILE B 152      60.524  -2.308  37.919  1.00 22.97           C  
ATOM   3762  N   ARG B 153      58.928   2.599  39.929  1.00 27.86           N  
ATOM   3763  CA  ARG B 153      57.910   3.612  40.009  1.00 28.74           C  
ATOM   3764  C   ARG B 153      58.495   4.943  40.389  1.00 29.99           C  
ATOM   3765  O   ARG B 153      57.992   5.942  39.892  1.00 30.76           O  
ATOM   3766  CB  ARG B 153      56.849   3.286  41.038  1.00 28.23           C  
ATOM   3767  CG  ARG B 153      56.243   1.918  40.906  1.00 28.59           C  
ATOM   3768  CD  ARG B 153      54.866   2.048  41.481  1.00 29.33           C  
ATOM   3769  NE  ARG B 153      54.557   1.028  42.458  1.00 30.19           N  
ATOM   3770  CZ  ARG B 153      54.711   1.292  43.764  1.00 30.78           C  
ATOM   3771  NH1 ARG B 153      54.385   0.342  44.637  1.00 31.38           N  
ATOM   3772  NH2 ARG B 153      55.150   2.481  44.189  1.00 30.45           N  
ATOM   3773  N   ASN B 154      59.507   5.036  41.249  1.00 31.76           N  
ATOM   3774  CA  ASN B 154      60.051   6.354  41.576  1.00 33.00           C  
ATOM   3775  C   ASN B 154      61.283   6.684  40.760  1.00 32.15           C  
ATOM   3776  O   ASN B 154      62.090   7.533  41.127  1.00 31.81           O  
ATOM   3777  CB  ASN B 154      60.393   6.462  43.053  1.00 36.28           C  
ATOM   3778  CG  ASN B 154      61.538   5.600  43.549  1.00 40.41           C  
ATOM   3779  OD1 ASN B 154      62.318   5.023  42.791  1.00 40.06           O  
ATOM   3780  ND2 ASN B 154      61.648   5.462  44.863  1.00 44.62           N  
ATOM   3781  N   GLY B 155      61.498   5.968  39.661  1.00 31.31           N  
ATOM   3782  CA  GLY B 155      62.536   6.303  38.720  1.00 30.06           C  
ATOM   3783  C   GLY B 155      63.956   6.043  39.142  1.00 29.58           C  
ATOM   3784  O   GLY B 155      64.871   6.644  38.582  1.00 31.06           O  
ATOM   3785  N   THR B 156      64.223   5.175  40.100  1.00 28.59           N  
ATOM   3786  CA  THR B 156      65.594   4.954  40.488  1.00 27.66           C  
ATOM   3787  C   THR B 156      66.052   3.541  40.188  1.00 27.49           C  
ATOM   3788  O   THR B 156      67.053   3.084  40.746  1.00 27.32           O  
ATOM   3789  CB  THR B 156      65.717   5.284  41.996  1.00 27.86           C  
ATOM   3790  OG1 THR B 156      64.900   4.389  42.745  1.00 28.35           O  
ATOM   3791  CG2 THR B 156      65.242   6.679  42.300  1.00 28.30           C  
ATOM   3792  N   TYR B 157      65.374   2.781  39.337  1.00 27.59           N  
ATOM   3793  CA  TYR B 157      65.732   1.386  39.106  1.00 27.59           C  
ATOM   3794  C   TYR B 157      67.074   1.225  38.385  1.00 28.96           C  
ATOM   3795  O   TYR B 157      67.247   1.777  37.286  1.00 29.85           O  
ATOM   3796  CB  TYR B 157      64.593   0.752  38.305  1.00 26.17           C  
ATOM   3797  CG  TYR B 157      64.806  -0.658  37.754  1.00 24.69           C  
ATOM   3798  CD1 TYR B 157      65.325  -0.813  36.486  1.00 24.59           C  
ATOM   3799  CD2 TYR B 157      64.451  -1.750  38.501  1.00 23.50           C  
ATOM   3800  CE1 TYR B 157      65.479  -2.071  35.971  1.00 24.97           C  
ATOM   3801  CE2 TYR B 157      64.600  -3.016  37.991  1.00 23.60           C  
ATOM   3802  CZ  TYR B 157      65.115  -3.172  36.728  1.00 24.58           C  
ATOM   3803  OH  TYR B 157      65.263  -4.443  36.181  1.00 23.66           O  
ATOM   3804  N   ASP B 158      68.026   0.479  38.943  1.00 30.01           N  
ATOM   3805  CA  ASP B 158      69.292   0.309  38.250  1.00 32.37           C  
ATOM   3806  C   ASP B 158      69.259  -0.994  37.487  1.00 32.22           C  
ATOM   3807  O   ASP B 158      69.348  -2.076  38.072  1.00 32.62           O  
ATOM   3808  CB  ASP B 158      70.471   0.262  39.198  1.00 34.84           C  
ATOM   3809  CG  ASP B 158      71.853   0.309  38.528  1.00 38.12           C  
ATOM   3810  OD1 ASP B 158      72.790   0.694  39.228  1.00 39.91           O  
ATOM   3811  OD2 ASP B 158      72.013  -0.039  37.344  1.00 39.18           O  
ATOM   3812  N   HIS B 159      69.180  -0.920  36.159  1.00 31.20           N  
ATOM   3813  CA  HIS B 159      69.028  -2.118  35.384  1.00 29.29           C  
ATOM   3814  C   HIS B 159      70.260  -2.996  35.479  1.00 30.54           C  
ATOM   3815  O   HIS B 159      70.103  -4.220  35.461  1.00 31.11           O  
ATOM   3816  CB  HIS B 159      68.723  -1.725  33.952  1.00 26.92           C  
ATOM   3817  CG  HIS B 159      69.934  -1.441  33.115  1.00 24.33           C  
ATOM   3818  ND1 HIS B 159      70.281  -2.334  32.233  1.00 23.99           N  
ATOM   3819  CD2 HIS B 159      70.831  -0.449  33.307  1.00 23.30           C  
ATOM   3820  CE1 HIS B 159      71.460  -1.910  31.852  1.00 24.63           C  
ATOM   3821  NE2 HIS B 159      71.784  -0.800  32.494  1.00 23.85           N  
ATOM   3822  N   ASP B 160      71.452  -2.422  35.687  1.00 31.25           N  
ATOM   3823  CA  ASP B 160      72.660  -3.219  35.711  1.00 31.52           C  
ATOM   3824  C   ASP B 160      72.646  -4.191  36.841  1.00 31.06           C  
ATOM   3825  O   ASP B 160      73.044  -5.350  36.672  1.00 31.80           O  
ATOM   3826  CB  ASP B 160      73.898  -2.359  35.835  1.00 33.20           C  
ATOM   3827  CG  ASP B 160      74.420  -2.174  34.431  1.00 36.46           C  
ATOM   3828  OD1 ASP B 160      74.712  -3.185  33.772  1.00 37.63           O  
ATOM   3829  OD2 ASP B 160      74.471  -1.027  33.961  1.00 38.19           O  
ATOM   3830  N   VAL B 161      72.051  -3.774  37.960  1.00 30.16           N  
ATOM   3831  CA  VAL B 161      71.922  -4.609  39.152  1.00 28.96           C  
ATOM   3832  C   VAL B 161      71.317  -5.944  38.793  1.00 29.09           C  
ATOM   3833  O   VAL B 161      71.731  -6.970  39.339  1.00 30.06           O  
ATOM   3834  CB  VAL B 161      71.026  -3.924  40.202  1.00 28.56           C  
ATOM   3835  CG1 VAL B 161      70.733  -4.809  41.377  1.00 27.79           C  
ATOM   3836  CG2 VAL B 161      71.758  -2.715  40.731  1.00 29.07           C  
ATOM   3837  N   TYR B 162      70.398  -5.973  37.820  1.00 28.49           N  
ATOM   3838  CA  TYR B 162      69.727  -7.227  37.513  1.00 27.35           C  
ATOM   3839  C   TYR B 162      69.991  -7.757  36.127  1.00 26.96           C  
ATOM   3840  O   TYR B 162      69.513  -8.845  35.798  1.00 27.03           O  
ATOM   3841  CB  TYR B 162      68.247  -7.089  37.645  1.00 26.56           C  
ATOM   3842  CG  TYR B 162      67.786  -6.420  38.920  1.00 26.96           C  
ATOM   3843  CD1 TYR B 162      67.451  -7.167  40.017  1.00 26.55           C  
ATOM   3844  CD2 TYR B 162      67.667  -5.050  38.939  1.00 27.40           C  
ATOM   3845  CE1 TYR B 162      66.978  -6.537  41.140  1.00 26.73           C  
ATOM   3846  CE2 TYR B 162      67.205  -4.414  40.058  1.00 27.73           C  
ATOM   3847  CZ  TYR B 162      66.856  -5.166  41.155  1.00 27.73           C  
ATOM   3848  OH  TYR B 162      66.341  -4.526  42.277  1.00 28.33           O  
ATOM   3849  N   ARG B 163      70.776  -7.064  35.310  1.00 26.58           N  
ATOM   3850  CA  ARG B 163      70.948  -7.469  33.937  1.00 27.37           C  
ATOM   3851  C   ARG B 163      71.349  -8.926  33.743  1.00 29.49           C  
ATOM   3852  O   ARG B 163      70.732  -9.609  32.919  1.00 29.68           O  
ATOM   3853  CB  ARG B 163      71.968  -6.575  33.278  1.00 26.16           C  
ATOM   3854  CG  ARG B 163      72.045  -6.773  31.782  1.00 24.79           C  
ATOM   3855  CD  ARG B 163      72.794  -5.589  31.301  1.00 25.17           C  
ATOM   3856  NE  ARG B 163      72.222  -5.138  30.062  1.00 25.17           N  
ATOM   3857  CZ  ARG B 163      72.708  -5.548  28.903  1.00 26.28           C  
ATOM   3858  NH1 ARG B 163      72.152  -5.090  27.786  1.00 27.02           N  
ATOM   3859  NH2 ARG B 163      73.757  -6.387  28.879  1.00 26.80           N  
ATOM   3860  N   ASP B 164      72.308  -9.458  34.504  1.00 31.83           N  
ATOM   3861  CA  ASP B 164      72.735 -10.833  34.287  1.00 34.36           C  
ATOM   3862  C   ASP B 164      71.634 -11.833  34.607  1.00 34.47           C  
ATOM   3863  O   ASP B 164      71.341 -12.741  33.813  1.00 35.52           O  
ATOM   3864  CB  ASP B 164      73.971 -11.130  35.124  1.00 36.93           C  
ATOM   3865  CG  ASP B 164      75.247 -10.399  34.664  1.00 40.67           C  
ATOM   3866  OD1 ASP B 164      75.783 -10.697  33.577  1.00 41.85           O  
ATOM   3867  OD2 ASP B 164      75.718  -9.522  35.423  1.00 42.14           O  
ATOM   3868  N   GLU B 165      70.940 -11.636  35.726  1.00 33.56           N  
ATOM   3869  CA  GLU B 165      69.847 -12.506  36.139  1.00 32.73           C  
ATOM   3870  C   GLU B 165      68.770 -12.495  35.089  1.00 32.43           C  
ATOM   3871  O   GLU B 165      68.395 -13.548  34.570  1.00 33.45           O  
ATOM   3872  CB  GLU B 165      69.254 -12.023  37.451  1.00 33.49           C  
ATOM   3873  CG  GLU B 165      68.119 -12.926  37.958  1.00 34.71           C  
ATOM   3874  CD  GLU B 165      67.388 -12.504  39.245  1.00 35.62           C  
ATOM   3875  OE1 GLU B 165      67.794 -11.532  39.912  1.00 35.24           O  
ATOM   3876  OE2 GLU B 165      66.373 -13.146  39.565  1.00 35.62           O  
ATOM   3877  N   ALA B 166      68.394 -11.274  34.704  1.00 31.71           N  
ATOM   3878  CA  ALA B 166      67.380 -11.041  33.704  1.00 30.21           C  
ATOM   3879  C   ALA B 166      67.718 -11.714  32.388  1.00 29.97           C  
ATOM   3880  O   ALA B 166      67.050 -12.664  31.971  1.00 29.15           O  
ATOM   3881  CB  ALA B 166      67.249  -9.560  33.491  1.00 30.05           C  
ATOM   3882  N   LEU B 167      68.827 -11.301  31.787  1.00 29.83           N  
ATOM   3883  CA  LEU B 167      69.290 -11.805  30.531  1.00 30.88           C  
ATOM   3884  C   LEU B 167      69.354 -13.328  30.515  1.00 33.78           C  
ATOM   3885  O   LEU B 167      68.910 -13.959  29.547  1.00 35.03           O  
ATOM   3886  CB  LEU B 167      70.629 -11.187  30.299  1.00 28.68           C  
ATOM   3887  CG  LEU B 167      70.822 -10.347  29.090  1.00 28.71           C  
ATOM   3888  CD1 LEU B 167      69.581  -9.576  28.693  1.00 28.51           C  
ATOM   3889  CD2 LEU B 167      71.968  -9.431  29.425  1.00 28.68           C  
ATOM   3890  N   ASN B 168      69.791 -13.947  31.613  1.00 35.95           N  
ATOM   3891  CA  ASN B 168      69.909 -15.382  31.649  1.00 38.22           C  
ATOM   3892  C   ASN B 168      68.559 -16.069  31.554  1.00 38.71           C  
ATOM   3893  O   ASN B 168      68.360 -16.902  30.666  1.00 38.99           O  
ATOM   3894  CB  ASN B 168      70.617 -15.808  32.923  1.00 40.35           C  
ATOM   3895  CG  ASN B 168      70.442 -17.305  33.181  1.00 42.10           C  
ATOM   3896  OD1 ASN B 168      69.589 -17.721  33.970  1.00 42.41           O  
ATOM   3897  ND2 ASN B 168      71.172 -18.178  32.490  1.00 43.10           N  
ATOM   3898  N   ASN B 169      67.590 -15.766  32.395  1.00 39.57           N  
ATOM   3899  CA  ASN B 169      66.355 -16.497  32.224  1.00 41.55           C  
ATOM   3900  C   ASN B 169      65.430 -15.866  31.207  1.00 41.87           C  
ATOM   3901  O   ASN B 169      64.285 -16.302  31.026  1.00 41.36           O  
ATOM   3902  CB  ASN B 169      65.614 -16.687  33.564  1.00 43.63           C  
ATOM   3903  CG  ASN B 169      65.325 -15.501  34.464  1.00 44.77           C  
ATOM   3904  OD1 ASN B 169      65.286 -15.642  35.688  1.00 44.92           O  
ATOM   3905  ND2 ASN B 169      65.083 -14.317  33.940  1.00 45.69           N  
ATOM   3906  N   ARG B 170      65.933 -14.844  30.509  1.00 42.76           N  
ATOM   3907  CA  ARG B 170      65.227 -14.266  29.384  1.00 43.23           C  
ATOM   3908  C   ARG B 170      65.572 -15.095  28.162  1.00 45.66           C  
ATOM   3909  O   ARG B 170      64.683 -15.502  27.406  1.00 45.45           O  
ATOM   3910  CB  ARG B 170      65.656 -12.811  29.219  1.00 40.59           C  
ATOM   3911  CG  ARG B 170      65.031 -12.051  28.072  1.00 37.95           C  
ATOM   3912  CD  ARG B 170      64.714 -10.630  28.499  1.00 34.49           C  
ATOM   3913  NE  ARG B 170      65.449  -9.588  27.795  1.00 32.40           N  
ATOM   3914  CZ  ARG B 170      65.148  -9.143  26.567  1.00 31.07           C  
ATOM   3915  NH1 ARG B 170      65.883  -8.132  26.080  1.00 30.35           N  
ATOM   3916  NH2 ARG B 170      64.146  -9.674  25.867  1.00 30.35           N  
ATOM   3917  N   PHE B 171      66.847 -15.397  27.963  1.00 49.57           N  
ATOM   3918  CA  PHE B 171      67.260 -16.206  26.840  1.00 54.53           C  
ATOM   3919  C   PHE B 171      67.563 -17.657  27.272  1.00 60.01           C  
ATOM   3920  O   PHE B 171      68.567 -18.302  26.956  1.00 60.57           O  
ATOM   3921  CB  PHE B 171      68.437 -15.450  26.216  1.00 51.71           C  
ATOM   3922  CG  PHE B 171      68.029 -14.101  25.609  1.00 49.77           C  
ATOM   3923  CD1 PHE B 171      66.846 -13.947  24.909  1.00 49.12           C  
ATOM   3924  CD2 PHE B 171      68.856 -13.007  25.747  1.00 49.35           C  
ATOM   3925  CE1 PHE B 171      66.500 -12.733  24.353  1.00 48.64           C  
ATOM   3926  CE2 PHE B 171      68.506 -11.793  25.187  1.00 48.92           C  
ATOM   3927  CZ  PHE B 171      67.329 -11.649  24.491  1.00 48.38           C  
ATOM   3928  N   GLN B 172      66.575 -18.216  27.974  1.00 66.90           N  
ATOM   3929  CA  GLN B 172      66.559 -19.570  28.526  1.00 73.33           C  
ATOM   3930  C   GLN B 172      66.259 -20.581  27.423  1.00 76.92           C  
ATOM   3931  O   GLN B 172      65.113 -20.979  27.236  1.00 77.26           O  
ATOM   3932  CB  GLN B 172      65.484 -19.558  29.624  1.00 75.22           C  
ATOM   3933  CG  GLN B 172      65.056 -20.800  30.428  1.00 77.38           C  
ATOM   3934  CD  GLN B 172      63.648 -20.656  31.046  1.00 78.56           C  
ATOM   3935  OE1 GLN B 172      62.729 -21.413  30.730  1.00 79.19           O  
ATOM   3936  NE2 GLN B 172      63.353 -19.717  31.951  1.00 78.85           N  
ATOM   3937  N   ILE B 173      67.224 -21.014  26.618  1.00 81.67           N  
ATOM   3938  CA  ILE B 173      66.865 -21.945  25.552  1.00 85.80           C  
ATOM   3939  C   ILE B 173      66.717 -23.357  26.100  1.00 88.56           C  
ATOM   3940  O   ILE B 173      67.687 -23.995  26.574  1.00 88.94           O  
ATOM   3941  CB  ILE B 173      67.927 -21.858  24.411  1.00 85.99           C  
ATOM   3942  CG1 ILE B 173      67.847 -20.458  23.769  1.00 85.87           C  
ATOM   3943  CG2 ILE B 173      67.692 -22.949  23.356  1.00 86.12           C  
ATOM   3944  CD1 ILE B 173      66.464 -20.055  23.212  1.00 85.54           C  
ATOM   3945  N   LYS B 174      65.452 -23.771  26.087  1.00 92.01           N  
ATOM   3946  CA  LYS B 174      64.931 -25.056  26.529  1.00 95.48           C  
ATOM   3947  C   LYS B 174      63.425 -24.880  26.665  1.00 97.45           C  
ATOM   3948  O   LYS B 174      62.988 -23.979  27.392  1.00 97.87           O  
ATOM   3949  CB  LYS B 174      65.449 -25.498  27.916  1.00 96.06           C  
ATOM   3950  CG  LYS B 174      66.394 -26.704  27.874  1.00 96.66           C  
ATOM   3951  CD  LYS B 174      67.227 -26.872  29.157  1.00 96.98           C  
ATOM   3952  CE  LYS B 174      68.209 -25.718  29.438  1.00 96.88           C  
ATOM   3953  NZ  LYS B 174      69.121 -25.488  28.331  1.00 96.59           N  
ATOM   3954  N   GLY B 175      62.646 -25.750  26.022  1.00 99.32           N  
ATOM   3955  CA  GLY B 175      61.204 -25.674  26.123  1.00101.54           C  
ATOM   3956  C   GLY B 175      60.539 -26.883  25.467  1.00102.87           C  
ATOM   3957  O   GLY B 175      60.821 -27.199  24.308  1.00103.59           O  
ATOM   3958  OXT GLY B 175      59.667 -27.492  26.077  1.00103.65           O  
TER    3959      GLY B 175                                                      
