#!/usr/bin/env bash



for file in /Users/evanedelstein/Desktop/Research_Evan/Raji_Summer2019_atom/Data_Files/PymolPredus/Scripts/*
do
  if [[ "$file" == *script_* ]];then
    open -a "pymol" $file
  fi
done
