#!/bin/sh
cd /Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/predus_outputfiles

FILES=/Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/predus_outputfiles/*
for f in $FILES
do
  echo "Processing $f file..."
  fileid=`echo $f | awk -F/ '{print toupper $11}' | awk -F. '{print $2}' | sed 's/\_/./g'`
  echo "protien id"
  echo $fileid
  cat $f | awk '{print $4,$5,$6,$11}' | uniq | sort -k4 -nr > /Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/Predus_Score/P_score_${fileid}.txt
  file1=/Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/testquery30_interface/${fileid}
  file2=/Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/Predus_Score/P_score_${fileid}.txt
  file3=/Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/Predus_Score/P_score_${fileid}.txthead.txt
N=`cat "$file1" | awk 'END{print NR}'`
echo $N
cat "$file2" | head -n"$N" | awk '{print $3, $1}' > "$file3"
cat "$file1" >> "$file3"
TP=`cat "$file3" | awk '{print $1}' | sort | uniq -d | awk 'END{print NR}' `
echo $TP
F_score=`echo "scale=3; $TP/$N" | bc -l `
FP=$((N-TP))
echo $F_score
echo "file id" $fileid " |" "true positives" $TP " |"  "False positives" $FP  " |"  "F Score" $F_score >> ../F_score_only_unix.txt
done
