#!/bin/sh
: '
input -> dowloaded pdb files from Predus
output -> text file containing residues sorted from most conserved to least conserved
notes -> can easly add a command to only output top number of scores by changing the final sort command
'
cd /Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/predus_outputfiles

FILES=/Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/predus_outputfiles/*
for f in $FILES
do
  echo "Processing $f file..."
  ProtienID=`echo $f | awk -F/ '{printf $11}'`
  echo $ProtienID
  chainid=`cat $f | awk '{print $5;exit;}'`
  echo $chainid
  fileid=`echo $ProtienID | awk -F. '{print $2}'`
  fileid+=."$chainid"
  echo $fileid
  cat $f | awk '{print $4,$5,$6,$11}' | uniq | sort -k4 -nr > /Users/evanedelstein/Desktop/LAB/Raji_Summer2019_atom/Code/Data_files/Predus/Predus_Score/P_score_${fileid}.txt
done
